### ISSUE TITLE
keyname returns "??" fot Shift_L if you also press arrow keys

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1092] opened 2020-07-18 14:20 UTC
After [keyname] outputs an arrow key (Up/Down/Left/Right) - either from a key press or a key release - it will output "??" when you press "shift" instead of "Shift_L" (be it from a key press or a key release).

macOS mojave

**Comment by porres** [comment] 2020-07-18 14:35
on the other hand, if you pressed shift first and then press arrow keys, you also get "??"... now, I tried this in Purr Data, if I do this I get keynames such as "ShiftLeft"/"ShiftRight"/"ShiftUp"/"ShiftDown", which was the kind of thing I was hoping to get in vanilla

**Comment by porres** [comment] 2020-07-18 15:36
not sure if "shiftleft" is a thing though, and one can make a patch that knows when the shift is pressed prior to an arrow key, the problem is that the "??" bug complicates things, this is how I'm dealing with it now.
<img width="476" alt="Screen Shot 2020-07-18 at 12 36 06" src="https://user-images.githubusercontent.com/5360142/87856138-46e14d00-c8f3-11ea-9ccb-f00c698e9508.png">

**Comment by umlaeute** [comment] 2020-07-18 18:54
dupe of #773

**Closed by umlaeute** 2020-07-18 18:54 UTC
