### ISSUE TITLE
readsf doesn't handle header with marker meta

### ISSUE THREAD

**Issue by patricecolet** [pure-data/pure-data#2225] opened 2024-03-18 19:07 UTC
[test-readsf~meta.zip](https://github.com/pure-data/pure-data/files/14641207/test-readsf.meta.zip)

When a marker is added to wav file's meta, readsf~ seems to read after the end of the file.

In the attached example the sound ends up with a pop

tested on pd-0.54-1 on macos m1 and linux arm64

**Comment by patricecolet** [comment] 2024-03-18 19:32
Notice that not giving arguments to [readsf~] reads the wav file correctly

**Comment by Spacechild1** [comment] 2024-03-18 19:42
Can confirm the pop in "voice2-marker.wav" and that it only happens when you override the arguments.

**Comment by Spacechild1** [comment] 2024-03-18 19:43
I think @danomatika is most familiar with the soundfile parsing logic.

**Comment by danomatika** [comment] 2024-03-18 20:10
> I think @danomatika is most familiar with the soundfile parsing logic.

That may be overly-optimistic... I think I purged my memory banks on this topic!

**Comment by danomatika** [comment] 2024-03-18 21:37
Note: All assumptions I made are listed in the WAV reader implementation -> https://github.com/pure-data/pure-data/blob/master/src/d_soundfile_wave.c#L9

Additionally, debugging can be eased by enabling parser prints: https://github.com/pure-data/pure-data/blob/master/src/d_soundfile.h#L48

**Comment by danomatika** [comment] 2024-03-18 21:47
Parser debug info is:

voice2.wav:
~~~
RIFF 78186
  WAVE
fmt  16
  format 1 (PCM)
  channels 1
  sample rate 44100
  bytes per sec 88200
  block align 2
  bits per sample 16
data 78150
skipped reading frames
~~~


voice2-marker.wav:
~~~
RIFF 78894
  WAVE
fmt  16
  format 1 (PCM)
  channels 1
  sample rate 44100
  bytes per sec 88200
  block align 2
  bits per sample 16
bext 602
junk 28
data 78150
skipped reading frames
~~~

voice2-tempo.wav:
~~~
RIFF 78864
  WAVE
fmt  16
  format 1 (PCM)
  channels 1
  sample rate 44100
  bytes per sec 88200
  block align 2
  bits per sample 16
bext 602
acid 24
junk 28
data 78150
skipped reading frames
~~~

They all have the data chunk at the end, which is good. The marker and tempo versions both have an additional metadata chunks, but tempo has an `acid` chunk while marker does not...

**Comment by danomatika** [comment] 2024-03-18 22:08
voice2-marker.wav seems to have the wrong overall file length in it's initial file chunk: `RIFF 78894`. It's 30 bytes larger than voice2-tempo.wav, even though the latter has the same meta chunks *and* an additional `acid` chunk. Irregardless, the reader should only read the data length from the data chunk ie. `78150` bytes.

**Comment by patricecolet** [comment] 2024-03-18 22:12
For additionnal informations, voice2-marker.wav and voice2-tempo.wav has been rendered with reaper, and this behavior has been discovered with wav files rendered with logic audio containing a marker in meta data.

**Comment by danomatika** [comment] 2024-03-18 22:14
What is "marker" meta data, in this case?

**Comment by danomatika** [comment] 2024-03-18 22:18
Never mind, I see it's a `cue` chunk appended to the end:

~~~
cue dataLISTadtllabl
~~~

**Comment by umlaeute** [comment] 2024-03-18 22:22
Afaict, the data chunk size is correctly pressed when the file is opened (in the main thread), but when it gets opened again (in the reading thread) the size parsing is shortcut with a simple `fseek(END)`, which does not give the correct length.

**Comment by patricecolet** [comment] 2024-03-18 22:22
It's hard to say, I never use them, but some people uses daws that are embedding markers metadata into wav files.

It's supposed to add playlist chunks so you can play parts of the audio in the wav out of order.

**Comment by umlaeute** [comment] 2024-03-18 22:23
> Never mind, I see it's a cue chunk appended to the end:

Which aligns with my observation of wrongly reading the sore of the data chunk. The content of the `cue` chunk is probably what we hear.

**Comment by danomatika** [comment] 2024-03-18 22:23
> Afaict, the data chunk size is correctly pressed when the file is opened (in the main thread), but when it gets opened again (in the reading thread) the size parsing is shortcut with a simple `fseek(END)`, which does not give the correct length.

Correct. The parser sets the correct bytelimit for each file, however this doesn't appear to be used when the sound data is actually read.

**Comment by danomatika** [comment] 2024-03-18 22:30
Also, the `cue` chunk is not printed in the debug posts after `data` since the parser stops when it finds the sound data. Basically, after reading the sf struct should contain the offset to sound data *and* the bytelimit set to the data chunk size. Then anything reading should read bytes up to the limit and the `cue` chunk should be ignored. If something is ignoring this and just using the EOF, well that's a bug.

**Comment by danomatika** [comment] 2024-03-18 22:39
I think it comes from here: https://github.com/pure-data/pure-data/blob/master/src/d_soundfile.c#L328

...and I don't think it is a bug. You explicitly override header detection, so the bytelimit is set to the file size...

**Comment by patricecolet** [comment] 2024-03-18 22:43
That's what I was afraid of, I'm already changing my patching design to not override readsf arguments, sorry for the mess.

**Comment by danomatika** [comment] 2024-03-18 22:43
> Notice that not giving arguments to [readsf~] reads the wav file correctly

...as expected: the header is not overridden.

**Comment by patricecolet** [comment] 2024-03-18 22:45
> I think it comes from here: https://github.com/pure-data/pure-data/blob/master/src/d_soundfile.c#L328
> 
> ...and I don't think it is a bug. You explicitly override header detection, so the bytelimit is set to the file size...

That's what I was afraid of, I'm already changing my patching design to not override readsf arguments, sorry for the mess. 

May be the issue should be closed?

**Comment by danomatika** [comment] 2024-03-18 22:48
Well, it depends... do we support piping the output of soundfiler's sf info into readsf~? I never actually thought of that as a possibility but kept the original behavior of "if you give header info, the real header will not be read."

**Comment by patricecolet** [comment] 2024-03-18 22:55
soundfiler doesn't provide the bytes to read explicitly unless we fill an array, but this wouldn't crash pd with large files and small memory amount.

**Comment by Lucarda** [comment] 2024-03-18 23:04
iirc [soundfiler] will give you the size just reading the header without specifying (or loading into) an array. (just don't supply an array)

**Comment by danomatika** [comment] 2024-03-18 23:06
No, I mean we don't really support exactly what the test patch is doing, if the assumption is "`[readsf~]` will always only read the sound data":
1. [`soundfiler]` reads the file without a table which basically does the WAVE parser header detection to output the file info: `0 690 1 2 l` for voice-marker.wav
2. This output is appended to the filename when opening with `[readsf~]`: `open voice2-marker.wav 0 690 1 2 l`
3. The `690` tells `[readsf~]` where the header ends and the sound data begins, however `[readsf~]` no longer parses the WAVE header itself, so it assumes the end of the file is the end of the sound data.... in this case, it's not since the `cue` chunk was lazily appended by the DAW.

**Comment by danomatika** [comment] 2024-03-18 23:07
> iirc [soundfiler] will give you the size just reading the header without specifying (or loading into) an array. (just don't supply an array)

The test patch does this already:
<img width="562" alt="Screenshot 2024-03-19 at 12 06 45 AM" src="https://github.com/pure-data/pure-data/assets/480637/5c9fdf19-0a53-4625-8c7d-bb097d784cf6">

**Comment by danomatika** [comment] 2024-03-18 23:13
>iirc [soundfiler] will give you the size just reading the header without specifying (or loading into) an array. (just don't supply an array)

Actually, I'm wrong and @patricecolet is correct: `[soundfiler]` does *not* give you the length of the sound data in bytes, only the header offset to the start of the sound data.

If you want the actually length of the sound data, in this case the byte length in the sound data chunk for WAVE, then open a feature request.

**Comment by Lucarda** [comment] 2024-03-18 23:50
> If you want the actual length of the sound data, in this case the byte length in the sound data chunk for WAVE, then open a feature request.

i'll open one as this is an important thing if you need to pre-measure playing time.

**Comment by umlaeute** [comment] 2024-03-19 07:45
> Actually, I'm wrong and @patricecolet is correct: `[soundfiler]` does not give you the length of the sound data in bytes, only the header offset to the start of the sound data.

however, `[soundfiler]` gives you the length of the sound data in sampleframes (which is more useful anyhow).

it would probably be nice if `[readsf~]` would have a "maxframes" option (a named option would probably be better, e.g. `-maxframes`, `-nframes` or `-maxsize`; but then, `[readsf~]` currently has no named options...)

**Comment by danomatika** [comment] 2024-03-19 08:48
Ah right. Then, yes, this approach does work if playback is stopped manually using the sample rate and number of samples. There is just no built-in handling, as you mention:

![Screenshot 2024-03-19 at 9 46 48 AM](https://github.com/pure-data/pure-data/assets/480637/87736128-973d-49d7-9b88-3fa52668357f)

**Comment by umlaeute** [comment] 2024-03-19 08:51
the problem with manually stopping is, that you are bound to 64 sample blocks (block boundary).

**Comment by danomatika** [comment] 2024-03-19 08:58
True. In practical usage, for me at least, this wouldn't bother me, but would not be *exact*. I suppose adding an additional message to set this is preferable to appending an additional, optional argument to open?

**Comment by umlaeute** [comment] 2024-03-19 10:53
1. i think, adding another anonymous value is a bad idea (the list of values really just provide the info from the skipped header)
2. i think that specifying the number of frames to play back is interesting for *normal* opening as well (where the meta-information is read directly from the header)
4. i'm not a big fan of messages with named options (`[read -ascii -resize 10 test.txt(`), but both `[soundfiler]` and `[writesf~]` already use this pattern, so I don't see a reason why `[readsf~]` should not.
5. actually, we might just be able to re-use the same argument parsing code for both `[soundfiler]`'s *read* and `[readsf~]`, thus reducing the set of options one has to learn

| flag | in readsf~ |
|---|---|
| `-skip <n>` | start playing after *n* sampleframes (same as the first number after the filename) |
| `-resize` | (ignored) |
| `-maxsize` | maximum number of sampleframes that are being read |
| `-ascii` | play back a text file |
| `-raw` | header info (same as the trailing list) |

if both flags and anoynmous args are given, they must not collide (e.g. `[open -skip 10 test.wav 20(` would be illegal, but 
`[open test.wav 10(`, `[open -skip 10 test.wav(`, and `[open -skip 10 test.wav 10(` are all valid and do the same thing.

**Comment by danomatika** [comment] 2024-04-01 17:35
I'm closing this as the original behavior is as designed and ideas for additional control, as mentioned by IOhannes, can be added in a separate feature issue.

**Closed as completed by danomatika** 2024-04-01 17:35 UTC
Labels: severity:bug/fix, subject:core
