### ISSUE TITLE
repeating 'vis 1' 'vis 0' decreases vertical window size

### ISSUE THREAD

**Issue by rolfmeesters** [pure-data/pure-data#1250] opened 2020-12-26 11:03 UTC
when showing and hiding a subpatch by using `vis 1` `vis 0` repeatedly, the vertical size of the subpatch window is decreasing more and more.

windows 10, Pd 51.3

rolf meesters

**Comment by Spacechild1** [comment] 2021-01-02 20:54
Does it only happen if the menu bar doesn't fit in a single row and wraps around? If yes, then it's a duplicate of https://github.com/pure-data/pure-data/issues/348?

**Comment by rolfmeesters** [comment] 2021-01-03 10:32
Christof Ressi schreef op 02-01-2021 21:55:

> Does it only happen if the menu bar doesn't fit in a single row and wraps around? If yes, then it's a duplicate of #348 [1]? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

no 

rolf 

Links:
------
[1] https://github.com/pure-data/pure-data/issues/348
[2]
https://github.com/pure-data/pure-data/issues/1250#issuecomment-753528490
[3]

**Comment by Spacechild1** [comment] 2021-01-04 16:33
could you share a screenshot of a subpatch window which has this problem?

**Comment by rolfmeesters** [comment] 2021-01-05 12:51
Christof Ressi schreef op 04-01-2021 17:34:

> could you share a screenshot of a subpatch window which has this problem? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

sorry christof, i was to quick to say no. 

i resized the window to undo the wrap around of the menu bar (w1.png). 

after vis 0, vis 1  scroll bars appeared (w2.png). 

but the scroll bars are not persistent and no decreasing of the vertical
size. 

repeating the vis 0, vis 1 is intermittendly giving scroll bars. 

the opposite is sometimes happening also: 

no scroll bars when they should be there. 

tl1.png - complete view of the patch 

tl2.png - reduced window size 

tl3.png - after going to full screen and back 

the no-scroll bars are also not persistent. 

rolf 

Links:
------
[1]
https://github.com/pure-data/pure-data/issues/1250#issuecomment-754078493
[2]

**Comment by Spacechild1** [comment] 2021-01-05 13:46
Somehow I don't see the PNGs in your comment. It just says:

> tl1.png - complete view of the patch
> 
> tl2.png - reduced window size
> 
> tl3.png - after going to full screen and back

Anyway, the shrinking bug is a duplicate of #348. Maybe you can open a new issue just for the scrollbar issue?

**Closed** 2021-01-05 15:04 UTC
