### ISSUE TITLE
Can't input Tilde (~) character on Mac specific Keyboard layouts in pd 0.51-1

### ISSUE THREAD

**Issue by emviveros** [pure-data/pure-data#1138] opened 2020-08-27 19:47 UTC
I'm in OSx 10.13.6 High Sierra and after upgrading Pd to version 0.51-1 I'm experiencing strange behavior when inputing tilde in pd objects. In Pd 0.51-0 all works great!

To input tilde I press Shift+Tilde and after this press Spacebar.

Tested with 3 different Keyboards Layouts:
![Captura de Tela 2020-08-27 às 16 46 59](https://user-images.githubusercontent.com/3089536/91487965-f7dcef00-e884-11ea-801c-54cabb1647ad.png)

edit:
Text description

When trying to input tilde character, it failed in EUA Internacional - PC and Brasileiro Pro keyboard layouts. After press Shift + tilde key, a little tilde is displayed in pd object, to consolidate a big tilde, normal behavior is press spacebar, but   little tilde persist and the big tilde is added.

In Brasileiro keyboard layout everything is working as expected.

**Comment by umlaeute** [comment] 2020-08-27 19:59
iirc, in this bugfix release, Tcl/Tk was upgraded from 8.5.9 to 8.6.10.

apart from that: you could please add a text-description of *what happens* after you press the keys?

**Comment by emviveros** [comment] 2020-08-27 20:13
Of course! :) but.. I don't know how to iirc and/or add text description of what happened here from tcl...

**Comment by emviveros** [comment] 2020-08-27 20:19
Don't know if helps.. But the xev entry in all keyboard layouts is the same:

```
KeyPress event, serial 34, synthetic NO, window 0x600001,
    root 0x111, subw 0x0, time 831232456, (415,439), root:(654,1541),
    state 0x0, keycode 64 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0x600001,
    root 0x111, subw 0x0, time 831232856, (415,439), root:(654,1541),
    state 0x1, keycode 58 (keysym 0x7e, asciitilde), same_screen YES,
    XLookupString gives 1 bytes: (7e) "~"
    XmbLookupString gives 1 bytes: (7e) "~"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x600001,
    root 0x111, subw 0x0, time 831232995, (415,439), root:(654,1541),
    state 0x1, keycode 58 (keysym 0x7e, asciitilde), same_screen YES,
    XLookupString gives 1 bytes: (7e) "~"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x600001,
    root 0x111, subw 0x0, time 831233296, (415,439), root:(654,1541),
    state 0x1, keycode 64 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

FocusOut event, serial 34, synthetic NO, window 0x600001,
    mode NotifyNormal, detail NotifyNonlinear
```

**Comment by porres** [comment] 2020-08-27 20:23
hi, I noticed nothing different in Pd 0.51-1, but I was using "ABC", I'm in Mojave.

> "When trying to input tilde character, it failed in EUA Internacional - PC and Brasileiro Pro keyboard layouts. After press Shift + tilde key, a little tilde is displayed in pd object, to consolidate a big tilde, normal behavior is press spacebar, but little tilde persist and the big tilde is added."

I can confirm this behaviour for "U.S. International PC", but not for "ABC" or plain "US"

**Comment by emviveros** [comment] 2020-08-27 20:27
If helps in xev the entry for Shift + tilde outputs for:

### EUA Internacional layout

```
KeyPress event, serial 34, synthetic NO, window 0x600001,
    root 0x111, subw 0x0, time 832032872, (124,-16), root:(363,1086),
    state 0x0, keycode 64 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0x600001,
    root 0x111, subw 0x0, time 832033216, (124,-16), root:(363,1086),
    state 0x1, keycode 58 (keysym 0x7e, asciitilde), same_screen YES,
    XLookupString gives 1 bytes: (7e) "~"
    XmbLookupString gives 1 bytes: (7e) "~"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x600001,
    root 0x111, subw 0x0, time 832033352, (124,-16), root:(363,1086),
    state 0x1, keycode 58 (keysym 0x7e, asciitilde), same_screen YES,
    XLookupString gives 1 bytes: (7e) "~"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x600001,
    root 0x111, subw 0x0, time 832033520, (124,-16), root:(363,1086),
    state 0x1, keycode 64 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

### Brasileiro layout

```
KeyPress event, serial 34, synthetic NO, window 0x600001,
    root 0x111, subw 0x0, time 832074079, (145,-13), root:(384,1089),
    state 0x0, keycode 64 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0x600001,
    root 0x111, subw 0x0, time 832074391, (145,-13), root:(384,1089),
    state 0x1, keycode 58 (keysym 0x7e, asciitilde), same_screen YES,
    XLookupString gives 1 bytes: (7e) "~"
    XmbLookupString gives 1 bytes: (7e) "~"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x600001,
    root 0x111, subw 0x0, time 832074559, (145,-13), root:(384,1089),
    state 0x1, keycode 58 (keysym 0x7e, asciitilde), same_screen YES,
    XLookupString gives 1 bytes: (7e) "~"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x600001,
    root 0x111, subw 0x0, time 832074615, (145,-13), root:(384,1089),
    state 0x1, keycode 64 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

### Brasileiro Pro layout

```
KeyPress event, serial 34, synthetic NO, window 0x600001,
    root 0x111, subw 0x0, time 832122270, (125,-14), root:(364,1088),
    state 0x0, keycode 64 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0x600001,
    root 0x111, subw 0x0, time 832122566, (125,-14), root:(364,1088),
    state 0x1, keycode 58 (keysym 0x7e, asciitilde), same_screen YES,
    XLookupString gives 1 bytes: (7e) "~"
    XmbLookupString gives 1 bytes: (7e) "~"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x600001,
    root 0x111, subw 0x0, time 832122694, (125,-14), root:(364,1088),
    state 0x1, keycode 58 (keysym 0x7e, asciitilde), same_screen YES,
    XLookupString gives 1 bytes: (7e) "~"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x600001,
    root 0x111, subw 0x0, time 832122782, (125,-14), root:(364,1088),
    state 0x1, keycode 64 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

**Comment by emviveros** [comment] 2020-08-27 22:36
Now I see in comments tilde generate unexpected behaviors to Shift + tilde and Spacebar to. They are:

### EUA Internacional layout
generates -> ˜ã
expected -> ã

### Brasileiro keyboard layout
generate -> ~a
expected -> ã

### Brasileiro Pro keyboard Layout
generates -> ˜ã
expected -> ã

**Comment by mschebella** [comment] 2020-09-21 08:42
I have similar problems with a German keyboard layout and OSX 10.15.6.
Usually, on a German keyboard, I create the tilde with ALT+n, followed by a space.
Pd creates two tildes (~~).
*~ 0.5 -> *~~ 0.5

**Comment by mschebella** [comment] 2020-09-21 08:44
`*~ 0.5 -> *~~0.5`

**Comment by porres** [comment] 2020-09-21 22:42
this might be related, but I can't also type now on 51-1 (macOS) words like "café" in symbol box, objects, messages - it comes out as "caf´é"

it still works if I'm doing it for a gui label

**Comment by porres** [comment] 2020-09-21 22:46
yeah, I'm having the same issue typing words with "~", like "não" - I get "n˜ão"

it is fine for creating objects, as I said before since I'm using "ABC" keyboard layout and a single "~" character doesn't give me trouble

**Comment by emviveros** [comment] 2020-09-22 22:23
> this might be related, but I can't also type now on 51-1 (macOS) words like "café" in symbol box, objects, messages - it comes out as "caf´é"

comments are also exhibiting the same behavior here.  

OSx 10.13.6 Pd 0.51-2

**Comment by danomatika** [comment] 2020-10-16 10:22
> iirc, in this bugfix release, Tcl/Tk was upgraded from 8.5.9 to 8.6.10.

Just to note: On macOS, we are using Tk 8.5.15 starting with 0.48 or 0.49 as Tk 8.5.9 has *so many* issues. I feel I need to clarify this to avoid any misunderstanding regarding bugs which are attributable to 8.5.9.

**Comment by danomatika** [comment] 2020-10-16 10:24
This problem might be something I fixed in a custom key input handling patch which was applied when building Tk 8.5.19. I might need to port it forward to 8.6+. The Tk mac dev was involved with the previous discussion, but I guess that work has not been ported over to Tk...

**Comment by emviveros** [comment] 2020-10-16 15:33
@porres ask me for test this weird behavior on GUI

I tried it in canvas GUI and all works as it should..

~ + a = ã
' + c = ç
' + e = é
^ + o = ô

**Comment by umlaeute** [comment] 2020-10-16 18:57
what's the "canvas GUI"?

**Comment by porres** [comment] 2020-10-16 19:11
> what's the "canvas GUI"?

[cnv]

**Comment by umlaeute** [comment] 2020-10-16 19:34
since [cnv] is only a display object, how do you type anything in it?

(i genuinely do not understand what you tested; just in case you tried to open the properties-editor and then typed some text into the label field: this would be unrelated to the problems we are seeing)

**Comment by porres** [comment] 2020-10-16 19:59
yes, it's the label. I also saw that gui's labels don't have this issue. I don't see how unrelated it is, as it doesn't have any issues when typing in it and this is the only place there's no issue (seems relevant to point it out to me). But I get gui's labels are probably treated differently so they don't have any issue.

**Comment by umlaeute** [comment] 2020-10-16 20:26
unfortunately it is really unrelated:
the problem we are having is getting single key-strokes into the communication GUI->core.

however, editing anything in a "native text-widget" (e.g. the "label" in a property box; or a [text] window) will not send *any* keystrokes (instead it will send the full text, once it is done).

the problem is not about communicating text, but about getting keystrokes.

**Comment by millerpuckette** [comment] 2020-10-17 18:41
Since typing tilde characters is likely always to be a pain for non-US keyboards, what if we make a key accelerator to insert a tilde?  (Could use control-T but would have to then reassign "triggerize" to a different accelerator).  It should be an alphabetic character that's easy to find on any Roman keyboard :)

**Comment by umlaeute** [comment] 2020-10-17 18:55
i don't think that such a hack should go into Pd itself.

afaict (though i never used 'cos i never needed it), you can create such shortcuts on a *system level* for every OS (probably focused on a single application as well).

this is has the added benefit, that the user can chose whatever shortcut pleases them (and fits with their keyboard layout, without having people to second guess which keys are "easily available on *any* Roman keyboard").

we could of course make it easier to implement such hacks - e.g. by documenting how it is done on the various OSs.

**Comment by danomatika** [comment] 2020-10-17 18:56
I will look at this shortly. At the least, it may just need the existing patch applied to 8.6.

**Comment by danomatika** [comment] 2020-10-17 21:13
It looks like most of what the patch was doing is present in TK 8.6.10.

I think the bug is related to the dead key handling in pd_bindings.tcl as Pd-0.50-2 doesn't show the interim characters when composing, ie. the ¨ shown when pressing opt+u then u to compose a ü in the English layout. Pd-0.51 is showing this.

**Comment by danomatika** [comment] 2020-10-17 21:41
Nevermind, the logic was just moved around a bit and I think it just needs the patch after all.

**Comment by danomatika** [comment] 2020-10-17 23:20
Ok. The patch fixes key repeat by sending key releases to match key repeat presses and adds checking for the system key repeat settings. This is, however, something different from the issue.

The composition problem is actually handled by Tk 8.6 on macOS and the text entry widgets listen for Tk *IMEMarkedText events, for example entry: https://github.com/tcltk/tk/blob/master/library/entry.tcl#L275

What the Pd GUI needs to do is listen for these events as well and handle clearing the interim composition characters. I imagine that's something to do with editing/removing items in the `::pd_bindings::key2iso` in `tcl/pd_bindings.tcl`.

As it's late and @umlaeute wrote most of the dead key / compose handing code, I ask him to weigh in next.

**Comment by millerpuckette** [comment] 2020-10-18 17:22
Cool... thanks for messing with this - it would have taken me a long time to get even this far...

**Comment by danomatika** [comment] 2020-10-18 20:41
Here is a test build for newer macOS versions: http://docs.danomatika.com/pdbuilds/0.51/Pd-0.51-3-keyfix.zip

It has the adapted key release patch and a basic solution which sends a virtual BackSpace key event to the pd core on `TkClearIMEMarkedText` and `TkAccentBackspace`:

```tcl
::pd_bindings::sendkey %W 1 BackSpace "" 0
::pd_bindings::sendkey %W 0 BackSpace "" 0
```

This seems to work but I'd like some testing on confirm before making a PR.

**Comment by porres** [comment] 2020-10-18 20:53
I'm getting debug posts on the terminal and things work in messages/objects but in symbol boxes I get "cafÂé" instead of "café"

**Comment by emviveros** [comment] 2020-10-18 20:55
Here works perfectly !! Only with some messages in pd console
![Captura de Tela 2020-10-18 às 18 53 42](https://user-images.githubusercontent.com/3089536/96385532-ed472380-116a-11eb-901c-e78b766d9fa1.png)

**Comment by porres** [comment] 2020-10-18 20:57
yeah, doing some tests with "~" and those keyboard layouts that had a problem, I can create something like [osc~] just fine. So, the only problem is in the symbol box, which besides the other problem I mentioned, I get something lke pdË~ instead of pd~

**Comment by emviveros** [comment] 2020-10-18 20:59
> Here works perfectly !!

In "Brasileiro - Pro" and "EUA Internacional - PC" keyboard layouts

**Comment by porres** [comment] 2020-10-18 21:04
@emviveros , is the atom symbol box working for you?

**Comment by emviveros** [comment] 2020-10-18 21:08
Here works atm symbol box works fine in "Brasileiro - Pro" and "EUA Internacional - PC" keyboard layouts

**Comment by danomatika** [comment] 2020-10-18 21:12
I probably needs to bypass `::pd_bindings::sendkey` and send directly too the pd core without adding to the dead keys dict.

**Comment by porres** [comment] 2020-10-18 21:23
By discussing with @emviveros via telegram, he's applying accents in a different way.

I'm used with some apple's shortcuts, like using "option + e" to get "´" and then "e" to get "é"... and this is not working for symbol boxes only.

**Comment by porres** [comment] 2020-10-18 21:24
> this is not working for symbol boxes only.

and it used to work, of course ;)

**Comment by danomatika** [comment] 2020-10-18 21:28
>I'm used with some apple's shortcuts, like using "option + e" to get "´" and then "e" to get "é"... and this is not working for symbol boxes only.

It's working for me in symbols, but maybe because I'm on macOS 10.14. Not sure. There should be no difference between inputing text in object, symbols, etc as they all are fed characters in the same way.

**Comment by porres** [comment] 2020-10-18 22:24
I'm on 10.14.6

So as crazy as it may be, testing Pd-0.51-3-keyfix with any keyboard layout I have this issue only in symbol boxes with the mac shortcuts for accents. Let me be as descriptive as I can be.

For instance, using the "US" layout (no "us international pc") I can only use such shortcuts to get accents. And this is how I learned how to use macs so I still do it. And I've always had laptops so I just use the keyboard from it and all the layouts were always the one you get in USA.

So, for the tilde, I can use shift + the key to the left of "1", that gives me the tilde character right away (no need to hit space). So I have no issue to create tilde objects like [osc~]. That also works fine for symbol boxes, so I can type "osc~" as a symbol, and equally fine in comments and messages.

The problem occurs when actually using tilde as an accents for portuguese words like "não" (no).

Then I have to use "option + n" to get tilde as an accent and then hit "a" key to get "ã".

This works for object boxes, messages, comments, **but not the symbol box**!!!

Same happens for other accents in other words like "café" (coffe). For this, the shortcut is "option + e" and then "e" again.

@emviveros  tried the same thing as me and could reproduce the error/bug!

<img width="593" alt="Screen Shot 2020-10-18 at 19 19 23" src="https://user-images.githubusercontent.com/5360142/96387222-d9a1ba00-1176-11eb-905c-4e3ae5321b37.png">

Now, if I use other layouts that allow me to use other keys for accents, it's fine. For example, if I use "US international PC", I can use the apostrophe key to the left of return, and it allows me to hit "e" afterwards to get "é". The plain "US" doesn't give me that possibility, so the only option to get "é" is with that shortcut.

Nonetheless, with "US international PC" I can try it both ways. And if using the apostrophe works, using the shortcut doesn't work either, and only for the symbol box as well.

See if you can reproduce this over there @danomatika .

I actually don't like using "US international PC" and wish I could keep using plain "US" ;)

**Comment by porres** [comment] 2020-10-18 22:40
But I can say the remaining issue is not as important as the others which got fixed. 

It's rare to need to type in words in symbol boxes in portuguese that make use of accents. I actually never do... and if i HAVE, ok, I can switch the layout to "us international pc" or something. 

That is to say that this fix can be taken right away for an acceptable 0.51-3 bugfix release in my opinion ;)

**Comment by porres** [comment] 2020-10-18 22:43
I'll basically just suffer from a psychological torture of being aware of the existence of the bug, but I won't really face it in any use case.

**Comment by danomatika** [comment] 2020-10-19 09:07
>I'll basically just suffer from a psychological torture of being aware of the existence of the bug, but I won't really face it in any use case.

That is a description of software development in general.

**Comment by danomatika** [comment] 2020-10-23 19:08
@porres Can you confirm this fix works? If so, I'll make the PR and Miller can add it.

**Comment by porres** [comment] 2020-10-23 22:05
which one? what's new? I was talking earlier about my tests with your latest thing in https://github.com/pure-data/pure-data/issues/1138#issuecomment-711419657

**Comment by danomatika** [comment] 2020-10-23 22:06
Yes, that test build.

**Comment by porres** [comment] 2020-10-23 23:27
So yeah, I can confirm, the only issue is with symbol box and macOS shortcut for accents!

**Comment by danomatika** [comment] 2020-10-23 23:54
> So yeah, I can confirm, the only issue is with

So you can confirm it's not 100% working.

> symbol box

Ok, by "symbol box" you mean the "symbol atom" GUI. I was thinking you meant the "symbol object." Yes, there is a problem with the symbol atom as it is not telling the GUI to clear the compose character for some reason.

> and macOS shortcut for accents!

This is actually another event that is sent that the GUI needs to handle, you can see it in the console: "accent backspace". Currently, the test build only sends a virtual backspace when it receives a "clear marked text" event so I need to add the other event handling.

More work todo then.

**Comment by porres** [comment] 2020-10-24 00:38
> So you can confirm it's not 100% working.

yeah, actually that, but I thought you were aware my previous posts were on my tests with that build.

> Ok, by "symbol box" you mean the "symbol atom" GUI.

yeah, the "atom box".

so, well, my tests for this are described in depth in here, just to make it sure https://github.com/pure-data/pure-data/issues/1138#issuecomment-711432763

> you can see it in the console: "accent backspace"

I don't actually see "accent backspace" anywhere when I do the accents via the keyboard shortcuts I know. Maybe I said something stupid - I meant like "option + e" for ´

**Comment by danomatika** [comment] 2020-10-25 22:26
@porres I don't have a fix for the symbol atom yet, but I can make the following with the "US" layout:

* é: opt+e, e
* è: opt+`, e

**Comment by danomatika** [comment] 2020-10-25 22:30
@umlaeute Is the symbol atom text buffer handled differently than object or message boxes? It doesn't seem to be as far as I could tell after a quick look in g_text.c, etc. The char composition handling I put in works fine in objects and messages but symbols are getting leftover/extra chars.

**Comment by danomatika** [comment] 2020-10-25 22:57
I've put the code I have now into #1192 however it is still a work in progress. You will need to (re)build a  Tcl/Tk 8.6.10 Wish app to include the patch and use this to build the .app bundle in order to see the key release fixes.

**Comment by porres** [comment] 2020-10-26 00:32
> @umlaeute Is the symbol atom text buffer handled differently than object or message boxes?

maybe it is => https://github.com/pure-data/pure-data/issues/1101

**Comment by danomatika** [comment] 2020-10-26 10:19
>maybe it is => #1101

Ah, yes. That is probably it, basically a related issue but not caused by the key handling. WHat's probably going on is that the backspace is only deleting the last character (aka byte), except that some larger Unicode code points are multi-byte so multiple characters need to be deleted. It just requires checking the byte width of the previous code point and removing enough.

**Comment by porres** [comment] 2020-10-28 01:54
ok, this is fixed, we can close it ;)

**Closed** 2020-10-28 04:03 UTC

**Comment by umlaeute** [comment] 2024-07-01 16:08
Note to myself: I think I might have broken deadkeys again with https://github.com/pure-data/pure-data/commit/c570e57171ef7aeb5616b6c77d87d5499de68bad
(I did test edit-mode, but I might have broken run-mode)
