### ISSUE TITLE
Slider position incorrect when set via loadbang on a zoomed-canvas

### ISSUE THREAD

**Issue by nyponen** [pure-data/pure-data#2327] opened 2024-05-23 19:54 UTC
I defined an hslider with a range of 1-10 and Receive symbol: init. In the example patch, loadbang sends 8 to init, but the slider position is set to 4, even though the correct value is sent out of the slider. Other methods of sending a number to the slider position it correctly. This occurs in version 0.54.1 on Windows 10.

![image](https://github.com/pure-data/pure-data/assets/17462467/e56a2c33-c1c3-483c-924f-d32a9b57782e)

![image](https://github.com/pure-data/pure-data/assets/17462467/ba4516d6-2844-4ed4-84e8-70689e28fd25)

**Comment by porres** [comment] 2024-05-23 20:33
can you post the zipped patch here?

**Comment by porres** [comment] 2024-05-23 20:40
seems to work fine on macOS

**Comment by porres** [comment] 2024-05-23 20:51
yeah, loads completely fine here, hard to believe 
![Screen Shot 2024-05-23 at 17 50 47](https://github.com/pure-data/pure-data/assets/5360142/ee6bf21a-6de7-4374-98b7-259337ebea28)

**Comment by nyponen** [comment] 2024-05-23 20:52
Try it on Windows 10.

**Comment by porres** [comment] 2024-05-23 20:57
I can't :) don't have it

**Comment by umlaeute** [comment] 2024-05-24 08:46
i can reproduce this, if I tell Pd to start new windows in "zoomed" mode.

since I'm running on Debian, i think this is not specific to Windows.

also, it seems that this has been fixed in the upcoming Pd-0.55 (although I can briefly see the slider jumping from the wrong ("4") value to the corrent ("8") one on startup...)

**Closed by umlaeute** 2024-05-24 08:46 UTC
Labels: bug/fix, subject:GUI

**Comment by umlaeute** [comment] 2024-05-24 08:59
note: it seems that this "fix" is a side-effect of df7e86a0db4ac76927575c03d9f93f9b4eecf39f (which forces a re-draw).

i haven't investigated whether there's a *real (better) fix* (and i don't intend to for now)

**Comment by porres** [comment] 2024-05-25 01:35
I confirm it happens with zoom in macOS, now it's all believable :)
