### ISSUE TITLE
request: resizing GUIs by mouse

### ISSUE THREAD

**Issue by H-MLim** [pure-data/pure-data#1130] opened 2020-08-19 15:44 UTC
personally thinking, I just found much convenience a function of resizing GUIs (bang, toggle, etc.) by mouse without going property nor sending message on Purr-data (for example when you locate the corner of bang, the two headed arrow is appeared and can resizable). would it be also reflected in vanilla in the future?

**Comment by porres** [comment] 2020-08-19 16:46
I already have the same request (that also includes atom boxes) here: https://github.com/pure-data/pure-data/issues/1010

**Comment by umlaeute** [comment] 2020-08-19 19:28
closing this as it appears to be a duplicate of #1010

**Closed by umlaeute** 2020-08-19 19:28 UTC
