### ISSUE TITLE
Pd 0.54-0 test1 macOS unable to open preferences

### ISSUE THREAD

**Issue by danomatika** [pure-data/pure-data#2006] opened 2023-06-20 20:26 UTC
On my macOS 13.4 system and Miller's Pd 0.54-0 test 1 build, I am unable to open the audio dialog or tabbed preferences due to a format issue with, I think, one of the sound device names:

~~~
(Tcl) UNHANDLED ERROR: floating point value is Not a Number
    while executing
"expr int("${_}")"
    (procedure "::dialog_audio::set_configuration" line 3)
    invoked from within
"::dialog_audio::set_configuration {{Core Audio: ThinkPad Thunderbolt 3 Dock USB Audio} {Core Audio: MacBook Pro Microphone} } {-0.007812 -0.007813 0.0..."
    ("uplevel" body line 10)
    invoked from within
"uplevel #0 $docmds"
~~~

Output of `pd -listdev` is:
~~~
% pd -listdev
audio input devices:
0. Core Audio: ThinkPad Thunderbolt 3 Dock USB Audio
1. Core Audio: MacBook Pro Microphone
audio output devices:
0. Core Audio: ThinkPad Thunderbolt 3 Dock USB Audio
1. Core Audio: MacBook Pro Speakers
API number 4
~~~

**Comment by umlaeute** [comment] 2023-06-20 22:03
is this by accident a double-precision Pd (there might be a glitch in the CI that would install Pd-double in stead of Pd-single).
the easiest way to check is what the deken-specifier says. (something like `Darwin-arm64-64`)

if it *is* a Pd-double, then this is most likely a dupe of #2000

**Comment by umlaeute** [comment] 2023-06-20 22:11
ah i've just seen https://lists.puredata.info/pipermail/pd-list/2023-06/132330.html, where @porres confirms that the app includes a double-precision Pd.

**Closed** 2023-06-23 16:37 UTC
Labels: bug/fix
