### ISSUE TITLE
Tcl/Tk error when opening multiple properties of the same canvas

### ISSUE THREAD

**Issue by fholzm** [pure-data/pure-data#1881] opened 2023-01-30 09:23 UTC
I'm currently facing the issue, that the right-click context menu isn't visible after some time. I am starting from a blank canvas and working on a subpatch. In the beginning, the context menu is available, but after some time no longer. With guessing the position, I can still open e.g. the help patch. I can't narrow down, what operation or object is triggering this behaviour. After tinkering around a bit I get the following error message:

```
(Tcl) UNHANDLED ERROR: bad window path name ".gfxstub6000023dd950"
    while executing
"wm transient $mytoplevel $::focused_window"
    (procedure "create_dialog" line 6)
    invoked from within
"create_dialog $mytoplevel"
    (procedure "pdtk_canvas_dialog" line 7)
    invoked from within
"pdtk_canvas_dialog {.gfxstub6000023dc990} 1 -1 0 0 -1 1 1 0 0 0 0 "
    ("uplevel" body line 2)
    invoked from within
"uplevel #0 $docmds"
```

I have this issue on an Intel MacBook Pro (2016) with macOS 12.6.3 with pd vanilla 0.52-2, 0.53-0 (via puredata.info) and 0.53-1 (via homebrew). I've attached a small [demo](https://github.com/pure-data/pure-data/files/10534226/demo.pd.zip) where this problem occurs on my computer

**Comment by umlaeute** [comment] 2023-01-30 12:55
it seems that Pd thinks that some other dialog (property-window,...) is focused, but this dialog no longer exists.

here on Linux (xfce4), it's practically impossible to interact with a window without it having the focus, thus the window that Pd thinks is currently in focus always exists.
i guess things are slightly different on macOS, where you can right-click a window without it having the focus, something like this:

1. create a patch, with an iemgui
2. open the properties window of the iemgui
   - this will make the properties-window the *focused* window
4. make sure the properties window is *above* the patch window
5. close the properties window
   - **here** i think that no new window gets the focus, so a (stale) handle to the properties is still stored as the *focused* window
6. right-click the patch window  to open the context-menu
  - i *think* that the patch window still does not gain focus, but creating the context-menu references the (stale) properties window

does this sound plausible? (can you reproduce it like this?)

**Comment by umlaeute** [comment] 2023-01-30 13:17
ah i stand corrected:

1. create a patch
2. open the patch properties (right-click -> Properties)
3. move the properties so that you can see the patch-canvas behind it
4. on the (backgrounded) patch-canvas do a right-click
5. :boom:

**Comment by umlaeute** [comment] 2023-01-30 13:29
the quick fix is to replace the line https://github.com/pure-data/pure-data/blob/f924fc45f4a56ba7df29ddbe609ff88133e68358/tcl/dialog_canvas.tcl#L145 with 

```tcl
if { [winfo exists $::focused_window] } {wm transient $mytoplevel $::focused_window}
```

**Comment by fholzm** [comment] 2023-01-30 15:46
I just found out how to reproduce the issue! It's occurring on multi-display setups. The right-click menu is only available in patches opened on the _primary_ display, not on other displays

**Comment by umlaeute** [comment] 2023-01-30 16:03
Ah. But that is somewhat untamed to the error message (and I think a duplicate of an issue already reported here...)

**Comment by umlaeute** [comment] 2023-01-30 18:56
Though I have to admit, I can't find the duplicate..

**Comment by fholzm** [comment] 2023-01-30 20:01
Well it's actually a quadruplicate...
#1303 #1802 #1807

**Comment by umlaeute** [comment] 2023-01-30 21:00
thanks. seems my androind app isn't that good in searching...
in any case, i think I'll take the opportunity to turn *this* issue into the one about the "Unhandled Tcl/Tk error" :-)

**Closed** 2023-02-02 22:10 UTC
Labels: bug/fix, pending, subject:GUI, os:macOS
