### ISSUE TITLE
command line flags parsing bug

### ISSUE THREAD

**Issue by chainjazz** [pure-data/pure-data#1218] opened 2020-11-12 14:26 UTC
putting general flags either into a .lnk Windows shortcut, the Startup options dialog, or editing the registry entry results in very inconsistent behavior, especially with regards to fonts.

`-font-face` parameters triggers externals search if there is a space between the flag name and value (i.e. `-font-face Arial`), 

it also doesn't accept quotation marks since the gui engine will interpret any starting quotation mark as an ending mark for an implied starting quotation mark; thus, it forces font face names with spaces to be escaped with `\ `; any quotation marks will effectively disable the Startup options dialog from opening

`-font-size 16`, for example will trigger `ignoring invalid font metrics from GUI`, as well as `-font-weight normal` being ignored.

so for example adding flags (either cmd line, .lnk shortcut or flags registry value) like this

`-font-size 16 -font-faceIBM\ Flex\ Sans -font-weight normal` would result in the loading of the font, but ignoring the size and weight

if there is a space between -font-face and name of the font, the Pd will search for extenals for each name component

`-font-face=IBM\ Flex\ Sans` (the equal sign will be accepted/ignored)

so what is going on here?

**Comment by Spacechild1** [comment] 2020-11-12 20:26
This is a duplicate of https://github.com/pure-data/pure-data/issues/579 and will be fixed with https://github.com/pure-data/pure-data/pull/741

**Closed by Spacechild1** 2020-11-12 20:26 UTC
