### ISSUE TITLE
abs~ doesn't work with multichannel audio from snake~

### ISSUE THREAD

**Issue by jrdooley** [pure-data/pure-data#2403] opened 2024-08-21 11:23 UTC
Pd 0.55.0
Tested one: macOS 14.5 (Macbook Pro M1)

**Where and when issue was discovered**
The `sqrt~`, `rqrt~`, `wrap~`, and `expr~` help patch containing the `pd multichannel` subpatch with an example of two `snake~` objects being used with `abs~`.

**Expected**
`abs~` to process the multichannel input coming from `snake~` and output a signal that is received and successfully process by a receiving `snake~` object.

**Actual**
No multichannel signal appears to be processed by the `abs~` object and the following error message appears in the console window: "object abs~ can't take multichannel inputs"

**Comment by Spacechild1** [comment] 2024-08-21 12:17
`abs~` does accept multichannel signals.

I'm pretty sure the problem is that you have loaded `zexy` which registers its own `abs~` object, overriding the built-in `abs~` object. (This is from a time when Pd didn't have `abs~`.)  `zexy`'s does not support `abs~`, that's why you get the error.

The problem is that you can't really opt out of `zexy`... Once `zexy` is loaded, the original `abs~` is gone - for all patches!

Now, @umlaeute might update `zexy` and add multichannel support to `abs~` (or remove the object altogether), but this is not a general solution. I think there should be a way to disable overriding of built-in objects. This could be global setting. Note that with https://github.com/pure-data/pure-data/pull/630 the object would still be available as `zexy/abs~`.

**Comment by porres** [comment] 2024-08-21 13:59
In cyclone we prevent overriding internals, it can be done! 

By the way, I removed abs~ from cyclone :)

**Comment by porres** [comment] 2024-08-21 14:00
I think we can close this and maybe add a new issue to discuss if we want to disable this feature. I have mixed feelings about it

**Comment by porres** [comment] 2024-08-28 18:52
I'm just closing this and we can create a new issue if one feels it's important to suggest a configuration that doesn't overwrite internals (I think I'll do that)

**Closed by porres** 2024-08-28 18:52 UTC
