### ISSUE TITLE
undo could also work with properties window

### ISSUE THREAD

**Issue by jmmmp** [pure-data/pure-data#856] opened 2019-12-31 12:37 UTC
The recent undo changes are very helpful. It would be even more interesting if the settings changes made in all properties windows would be accounted for.
Here is what I could find:
- undo works for canvas properties (patch, not cnv) if used with right-click on the background, the entry "undo apply" appears
- it doesn't work for the same dialogue if right-clicked on a subpatch e.g. [pd test], there is no undo entry either in the main patch or in the subpatch
- all GUI properties don't count for undo.
(- undo doesn't work with messages sent to the canvas (clear, add objects, ...) - but I myself don't have a problem with that)

**Comment by umlaeute** [comment] 2019-12-31 15:07
> all GUI properties don't count for undo.

that's a side-effect of `undo` not undoing the internal state of arbitrary objects.

i don't see any proper solution for this and am inclined to close this as `wontfix`

**Comment by umlaeute** [comment] 2020-01-01 19:49
> it doesn't work for the same dialogue if right-clicked on a subpatch

this i cannot reproduce. i get an `Undo` action on the subpatch-canvas (just as i get when calling the dialog from the subpatch-canvas itself).

this is how i do it:
- start with a patch that contains an empty `[pd test]` subpatch.
- right-click on `[pd test]` and select `Properties`
- enable the `Graph-on-Parent` flag and click <kbd>Apply</kbd>
  - the `[pd test]` is now a GOP
- open `[pd test]` (right-clicking it and selecting `Open`)
- call `undo` with <kbd>Control</kbd>+<kbd>z</kbd> on the `test` canvas.
  - the `[pd test]` is back to normal (non-GOP)


this is with Pd-0.50.2 on Debian/GNU linux.

**Comment by jmmmp** [comment] 2020-01-02 10:23
What I meant to say was to click inside the subpatch - it seems that operations in the parent canvas are saved, but in the sub-patches they aren't.

Regarding object settings:
If undoing the internal state of arbitrary objects couldn't be done for technical reasons, I would have no problem to say "there are more important things to do, and it's unsolvable undtil tck/tk improves or [insert issue here]". But I don't see a difference between "patching" and "not-really-serious-patching", specially when:
- all objects have send and receive settings which are vital for a patch to work (it's illogical to consider patching to add a [r xxx] above the object, but not inside it, although both have the same result)
- when preparing a GUI, all the internal "aesthetic" settings are as important as any other. E.g. it's considered "patching" to move an object around so that it doesn't clash with other objects, but it's not patching if the size of that object is improved (which has the same effect in the end, not to clash with other objects)

I don't see much of a grey area, as what is visible from the outside is as important for the person patching as it is the content inside. Even a color scheme is important for a patch to work, although it doesn't calculate any dsp.

(This could be also stretched to dynamic patching with internal messages, but I have no issue if someone says "that's irrealistic and hard to do, and it will crash all the time")

**Comment by Spacechild1** [comment] 2020-01-02 11:41
> What I meant to say was to click inside the subpatch - it seems that operations in the parent canvas are saved, but in the sub-patches they aren't.

I'm not sure I understand. Can you show the exact problem?

> Regarding object settings:

I agree that it's counter-intuitive that changes from the properties dialogs (both GUI and canvas properties) don't go to the undo queue.

**Comment by Spacechild1** [comment] 2020-01-02 11:53
@umlaeute 

> i don't see any proper solution for this and am inclined to close this as wontfix

I imagine we could add a generic undo type for objects in a glist whose data is just a binbuf containing the message(s) and the index of the object in the list. AFAICT, undo for object creation/destruction preserves the object positions within the glist, so saving the index makes sure that the message(s) always go to the right target.

This could even be exposed in the API for custom GUI externals. I'm not saying it's a must have, but it could be a nice addition. What do you think?

**Comment by jmmmp** [comment] 2020-01-02 17:54
> I'm not sure I understand. Can you show the exact problem?

I can't get it myself anymore - with that I notice that undo seems to be canvas-related, and probably I was looking at the wrong canvas or something. It might be not very intuitive if someone is retracing steps in programming on several canvases simultaneously and isn't fully aware of this. But also a centralized undo has its own perks for a patch that is active on many fronts, so I don't know exactly what is better here.

> I agree that it's counter-intuitive that changes from the properties dialogs (both GUI and canvas properties) don't go to the undo queue.

If it would be a technical issue or just too much work, I have no problem. If it's a design decision, it seems a bit arbitrary.

**Comment by porres** [comment] 2020-01-03 15:06
Hi, I was checking on this and just realized that when you change GUI's properties on the properties window, the changes are applied immediately. I remember it didn't use to be like this and I guess I remember when it changed. I'm assuming this was intentional and for some reason I don't know/remember. The thing is that if you make a change you didn't really want to, you can't undo it. For example, you spent a good amount of time fine tuning a nice color you liked, then accidentally changed it and now it's lost!

Also, the way things are now, the cancel button in the properties window isn't really good for anything, because changes are automatically reflected on the GUI. That also makes the 'ok' button pointless.

If we can't make undo revert the changes, maybe we could use the cancel button to revert them, then the 'cancel' and 'ok' buttons would make sense.

**Comment by umlaeute** [comment] 2020-01-03 15:48
(i'm not trying to defend anything, mainly trying to recap the decision-making process, not even done by me)

the behaviour @porres describes is due to the macOS design principles, where changes in property dialogs take effect immediately.
therefore this behaviour is *only* present on macOS (not on linux, windows or FreeBSD). the <kbd>cancel</kbd> button shouldn't be there on this system at all...
also i don't think that you can undo other (eg system-)properties on macOS.

**Comment by porres** [comment] 2020-01-03 16:00
well, I see now that the truth is that this is only for the color scheme in macOS, so 'ok' and 'cancel' still make sense for the other things - sorry for the noise

**Comment by umlaeute** [comment] 2020-01-03 18:52
i guess the behaviour should be consistent (that is: both color-scheme and *other* properties are applied immediately xor not)

**Comment by umlaeute** [comment] 2020-01-07 13:43
for what it is worth: #858 implements <kbd>undo</kbd>/<kbd>redo</kbd> for the properties of iemguis and numberboxes/symbolboxes.

are there any other properties that i've missed and which should be undoable?

**Comment by umlaeute** [comment] 2020-01-07 13:44
> for what it is worth: #858 implements

this is of course a call-for-testing: if you have compile-powers, please checkout the PR and see whether it does what you expect.

**Comment by danomatika** [comment] 2020-01-10 15:45
> the behaviour @porres describes is due to the macOS design principles, where changes in property dialogs take effect immediately.
> therefore this behaviour is only present on macOS (not on linux, windows or FreeBSD). the cancel button shouldn't be there on this system at all...

Yes, I added this only for macOS, but it *could* be enabled for the other platforms. This issue was pointed after after I did the initial work and we basically would need to cache the *initial* object state when the dialog was opened, then reapply it if the cancel button was pressed. It would also be good to have the undo action only be applied when the dialog was closed and not during a "hot update" which the dialog is open.

**Comment by umlaeute** [comment] 2020-01-10 17:55
> Yes, I added this only for macOS, but it could be enabled for the other platforms.

i don't think that this would be a good idea.
as was discussed previously: on other platforms, dialogs usually have an <kbd>Apply</kbd>-button that send all requested changes at once. The notion of a properties-window that will apply each change immediately is *uncommon* on these platforms

i agree with the <kbd>Cancel</kbd>-idea.

**Comment by danomatika** [comment] 2020-01-10 18:06
One thing: It’s really nice to make changes and see the result without having to close and reopen the dialog. But this is really another issue.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by umlaeute** [comment] 2020-01-10 18:55
oh sure. but on windows & linux we use <kbd>Apply</kbd> (which *applies* the current settings while leaving the dialog open, as opposed do <kbd>OK</kbd> which *applies* the settings and *closes* the dialog)

**Comment by danomatika** [comment] 2020-01-10 20:31
I know how not works on other platforms as I have used those same platforms. I’m only saying: “try it sometime.”

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by umlaeute** [comment] 2020-01-10 20:45
not sure i can parse this :-)

anyhow, i'm only saying: i'm sure it's nice to see changes immediately, but the way this is done on macOS (in general) is different from how it is done on other platforms, and i'd rather have my chosen platform to behave consistently than have different application pick different behaviours (if i want my computer to behave like macOS, i probably should get me a mac)

**Closed** 2021-07-12 23:16 UTC
Labels: feature, pending, subject:GUI, subject:patching
