### ISSUE TITLE
shortcuts issue on french keyboard

### ISSUE THREAD

**Issue by LucienRapilly** [pure-data/pure-data#1322] opened 2021-05-24 20:15 UTC
The shortcuts create two objects at once. They appear connected. Same behaviour for messages, number boxes, every shortcut. French keyboard, pd runs on osx 11.2.3.

**Comment by porres** [comment] 2021-05-24 22:17
is CAPS LOCK on?

**Comment by LucienRapilly** [comment] 2021-05-25 18:14
No it's not. I wrote about this on pdpatchrepo.info, it seems to be an issue for german and french users.

**Comment by umlaeute** [comment] 2021-05-25 19:08
weird, as i am a German-speaking user and don't have any such problems

**Comment by pierreguillot** [comment] 2021-05-25 20:00
Hello, I encounter the exact same issue with the newest Pd versions (Pd 0.51.4 and macOS 11.3.1 but the problem appeared a while ago) I think the problem is related to https://github.com/pure-data/pure-data/issues/239.

**Comment by umlaeute** [comment] 2021-05-26 07:27
ah, i obviously missed the part about macOS.

however, isn't this problem an *exact duplicate* of #239 (instead of just "related")?

so, i'm closing this in favour of the original issue (if you think this is a mistake and the issues are really separate, just add additional info to this ticket and we can open it again)

**Closed by umlaeute** 2021-05-26 07:27 UTC
Labels: bug/fix, regression, subject:GUI
