### ISSUE TITLE
"ç" character not giving the right number in [list fromsymbol]

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1089] opened 2020-07-16 07:46 UTC
"ç" is famous character in portuguese and here on my mac we type it by using "option" + c

Pd gets this character just fine in comments/messages and stuff, but if I type it this way in Pd and then ask [list fromsymbol] to give me the char nuymber, it gives us a wrong number of 195 (for "Ã") instead of 231.

Now, if I type "Ã" (btw, "ã"is also common in portuguese), I do get the right value of 195, no funny business. 

Weirdly enough, if I send "231" to [list tosymbol] I get "ç" and it converts back to 231 just fine.

Feels like a very weird bug...

here's a screenshot.

<img width="469" alt="Screen Shot 2020-07-16 at 04 37 47" src="https://user-images.githubusercontent.com/5360142/87641951-37a9a600-c71f-11ea-8a80-a1f89cc94f19.png">

**Comment by porres** [comment] 2020-07-16 07:52
ok, this happens to a bunch of other characters used in portuguese, like "ê" and "é"... they mistakenly become "195" in [list fromsymbol]

**Comment by Spacechild1** [comment] 2020-07-16 08:34
Welcome to the world of unicode ;-) Pd unicode strings use the very common UTF-8 encoding, which is a variable multi-byte encoding. This means that a single 32-bit unicode *codepoint* is represented using 1-4 *bytes*. This means that there is *no* 1:1 correspondence between bytes and codepoints/characters!

Let's take your `ç` example: the correct unicode byte sequence is `0xC3 0xA7`. Since you only looked at the first byte, you would only see the value 195. https://www.compart.com/de/unicode/U+00E7

> Weirdly enough, if I send "231" to [list tosymbol] I get "ç" and it converts back to 231 just fine.

UTF-8 has some fallback mechanism for incorrect input, e.g. to maintain backwards compatibility with 8-bit ("extended") ASCII. See the explanation in https://en.wikipedia.org/wiki/UTF-8#Invalid_byte_sequences:

> UTF-8 provided backwards compatibility for 7-bit ASCII, but much software and data uses 8-bit extended ASCII encodings designed prior to the adoption of Unicode to represent the character sets of European languages. Part of the popularity of UTF-8 is due to the fact that it provides a form of backward compatibility for these as well. A UTF-8 processor which erroneously receives an extended ASCII file as input can "fall back" or replace 8-bit bytes using the appropriate code-point in the Unicode Latin-1 Supplement block, when the 8-bit byte appears outside a valid multi-byte sequence.

If you need to map every unicode codepoint to a single number, you would need something like UTF-32. Generally, UTF-8 is fine because you can still split strings, search for substrings, etc.

I'm closing this as it is expected behavior.

**Closed by Spacechild1** 2020-07-16 08:34 UTC

**Comment by umlaeute** [comment] 2020-07-16 08:35
the utf-8 representation (which is what Pd uses internally)  of ç is "195 167" (that's two bytes).
this is also what ´[list fromsymbol]` (which converts strings to *bytes*) gives you (your patch is buggy assuming that you only get a single number for a single character input).

`[makefilename]` (or rather the underlying `sprintf()` function) is a bit weirder.

quoting a [StackOverflow answer](https://stackoverflow.com/a/35209977/1169096):

> Converting a value outside the range of of a signed char to char invokes:
> 
> >    the new type is signed and the value cannot be represented in it; either the result is implementation-defined or an implementation-defined signal is raised. C11dr §6.3.1.3 3

in practice, it seems to use ISO-8859 (on your system), which happens to map `231` to `ç`.  ISO-8859 itself has various variants, some of which will map `231` to other chars (like `į` (ISO-8859-4 - Scandinavia/Baltic), `ч` (ISO-8859-5 - Cyrillic) or `ח` (ISO-8859-8 - Hebrew)).

this is because most utf8 decoders (like the one used by TclTk) have a fallback mechanism:

quoting the [Wikipedia article on UTF-8](https://en.wikipedia.org/wiki/UTF-8#Description)
> *Fallback and auto-detection*: UTF-8 provided backwards compatibility for 7-bit ASCII, but much software and data uses 8-bit extended ASCII encodings designed prior to the adoption of Unicode to represent the character sets of European languages. Part of the popularity of UTF-8 is due to the fact that it provides a form of backward compatibility for these as well. A UTF-8 processor which erroneously receives an extended ASCII file as input can "fall back" or replace 8-bit bytes using the appropriate code-point in the Unicode Latin-1 Supplement block, when the 8-bit byte appears outside a valid multi-byte sequence

(so it seems that this fallback mechanism will mostly always use "ISO-8859-1", which will indeed render  `231` as `ç`.)


## so what's the point?

- don't assume that `[list fromsymbol]` will output one single number per input character
- don't use `[makefilename]`'s `%c` to generate non-ASCII characters (input must follow `0<=x<128`)
- if you cannot guarantee the latter, then you shouldn't mix `[list fromsymbol]` and `[makefilename]`.


i'm closing this as it is likely to not be resolveable.
While it would be possible to extend `[makefilename]` to produce proper UTF-8 encoded non-ASCII strings, it would deviate from all the `printf()`-implementations out there; such a deviation would cause more confusion rather than less (i'm totally for [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), but we shouldn't try to reduce suprises for the naïve users at the cost of breaking expectations of "expert" users).
if you really want this fixed, i guess you should bring the cause to the attention of either the *C-standard consortium* or the *Unicode Consortium* (though they are probably too busy getting the latest dog-pooh emoji into the standard) ;-)

**Comment by umlaeute** [comment] 2020-07-16 08:35
argh. after researching and writing this text for ages, @Spacechild1 beats me by 41 seconds!!!

**Comment by porres** [comment] 2020-07-16 16:32
> Don't assume that [list fromsymbol] will output one single number per input character

Ok, I now realize "ç" prints a list of "195 167" and not just "195"!!!!! Lesson learned!

> If you cannot guarantee the latter, then you shouldn't mix [list fromsymbol] and [makefilename].

Ok, it's just that [list tosymbol] works the same way for me... 231 prints "ç".

By the way, I found out "ç" = 231 from the [key] object, that outputs "231" when I press "ç".

**Comment by Spacechild1** [comment] 2020-07-16 17:41
> 231 prints "ç".

Again, this is "extended" ASCII, but not valid unicode. As @umlaeute has pointed out, the fallback mechanism might depend on your OS settings. I can imagine that on a Russian or Japanese laptop, the printout would look different, but I haven't tried.

**Comment by Spacechild1** [comment] 2020-07-16 18:56
> I found out "ç" = 231 from the [key] object

`[key]` outputs the numeric unicode codepoint (= 231), while `[keyname]` outputs the actual utf-8 string.

**Comment by Spacechild1** [comment] 2020-07-16 19:14
> Ok, it's just that [list tosymbol] works the same way for me... 231 prints "ç".

Again, that's implementation-defined behavior. Don't feed invalid UTF-8 sequences to `[list tosymbol]` or numbers outside 0-127 to `[makefilename %c]` if you want portable results.

**Comment by porres** [comment] 2020-07-16 19:49
I know, I was just explaining the source of my confusion, I get it now ;)

**Comment by porres** [comment] 2020-07-28 01:00
Wow, I now realize I'm using list fromsymbol to count the number of characters in a symbol and, as you just taught me, that doesn't really work when using "ç" and stuff... 

so, dear wizards, how can one count the number of characters in a symbol?

**Comment by Spacechild1** [comment] 2020-07-28 01:22
depends on how you define "character" ;-) https://engineering.linecorp.com/en/blog/the-7-ways-of-counting-characters/

if you want to count code points (i. e. ignoring grapheme clusters), you can do something like this: https://stackoverflow.com/a/7298149/6063908

**Comment by porres** [comment] 2020-07-28 01:53
> depends on how you define "character" ;-) 

"ç" is a character, but list fromsymbol (and "strlen") gives me "2" of them.

> if you want to count code points (i. e. ignoring grapheme clusters)

i guess that's what I want?

> you can do something like this: https://stackoverflow.com/a/7298149/6063908

ok, count only if [list fromsymbol] gives me a number less than 128 and greater than 191!

Seems to work.

Thanks

<img width="402" alt="Screen Shot 2020-07-27 at 22 47 09" src="https://user-images.githubusercontent.com/5360142/88610009-e624e380-d05b-11ea-9caa-650240d718b7.png">

**Comment by umlaeute** [comment] 2020-07-28 08:20
> > depends on how you define "character" ;-)
> 
> "ç" is a character, but list fromsymbol (and "strlen") gives me "2" of them.

no.
`[list fromsymbol]` gives you  two bytes. a byte is not a character. it's an 8bit number.

also there's a distinction between *ç* and *ç* even though both look the same (they *should* look the same; some browsers might render the two glyphs differently though).
the former is two bytes, the latter three bytes.

> 
> ok, count only if [list fromsymbol] gives me a number less than 128 or greater than 191!
> 

if you wanted to convert utf-8 bytes to unicode codepoints, there's also [this little abstraction](http://svn.code.sf.net/p/pure-data/svn/trunk/externals/iem/unicode/) (which i built together maya back then at the PdCon in São Paulo ;-)
