### ISSUE TITLE
Cursor icon of outlets is a "forbidden" sign

### ISSUE THREAD

**Issue by php4fan** [pure-data/pure-data#1923] opened 2023-03-18 19:43 UTC
Pd 0.53-2 freshly downloaded and built from source.

When I move the mouse cursor over any outlet (signal or data), the cursor looks like this:

![image](https://user-images.githubusercontent.com/13969584/226134037-3865e2c3-568c-494d-918f-869b8b297a99.png)

That makes no sense.

**Comment by Spacechild1** [comment] 2023-03-18 20:03
Which OS?

**Comment by php4fan** [comment] 2023-03-18 21:10
Sorry I forgot to specify, Manjaro Linux with KDE

**Comment by umlaeute** [comment] 2023-03-19 16:38
iirc this is more an issue with the underlying cursor icons (which are somewhat ill-defined).

So what do you think would make sense?
(I understand it's weird at the beginning, but it's one of those things that I think you get accustomed very quickly and stop seeing...)

**Comment by php4fan** [comment] 2023-03-19 20:33
> iirc this is more an issue with the underlying cursor icons (which are somewhat ill-defined).

I don't understand what you mean.

> So what do you think would make sense?

Do you mean what icons I think would make sense?

I seem to remember (the last time I previously used Pd was like 10 years ago) it used to be a circle, I'm not entirely sure. Certainly it wasn't a forbidden sign. A circle makes sense.

The question "which os"? kind of suggests this is only broken on Linux, perhaps not even in all Linux distributions. What is the icon currently in Mac OS and Windows?

**Comment by sebshader** [comment] 2023-03-19 20:49
It certainly isn't the case on xfwm (mx-linux). For me it's still a circle.
I would think it has something to do with tk calling for a certain cursor and the wm providing one back that isn't just 'circle'

**Comment by umlaeute** [comment] 2023-03-19 21:04
>  A circle makes sense.

:tada: you have won.

currently, the cursor for editing is `circle`.

> I don't understand what you mean.

unfortunately, the `circle` cursor shows up as a :no_entry_sign: icon.

you can verify this by simple script with `wish` (and hover over the window):
```tcl
. configure -cursor circle
```

This is because your icon theme contains a forbidden-sign for the `circle` cursor.
E.g. here (where I use the Adwaita theme), the `/usr/share/icons/Adwaita/cursors/circle` contains this:

![circle](https://user-images.githubusercontent.com/214034/226208199-cc2924c8-aca3-4046-b210-150bcbc23071.png)

I don't know why the `circle` cursor should have anything to do with :no_entry_sign: , but i would take this to the designers of your theme.
if they have a convincing argument that `circle` should indeed be  :no_entry_sign:, and that we should instead use `left_ptr_help` (or whatever) to get a ⭕, we might reconsider.
(and then there's the additional problem with TclTk cursors not being the same as the normal cursors. in TclTk there are weirdo [cursors](https://www.tcl.tk/man/tcl/TkCmd/cursors.html) like `gobbler` and `coffee_mug`, but we cannot access other cursors like `left_ptr_help`.)

i did spend some time trying to get more sensible cursors in the past (and found no apparent solution), and I do not intend to repeat this effort (for which I think the actual benefit is not *that* big).
so my current stance is: yes, this is a bug, but not in Pd.

**Comment by umlaeute** [comment] 2023-03-19 21:07
Anyhow, closing this as a duplicate of https://github.com/pure-data/pure-data/issues/1202
(please [check the issue database](https://github.com/pure-data/pure-data/issues?q=is%3Aissue+cursor) before submitting new bug)

**Closed by umlaeute** 2023-03-19 21:07 UTC
