### ISSUE TITLE
pd~ on windows

### ISSUE THREAD

**Issue by chikashimiyama** [pure-data/pure-data#251] opened 2017-11-11 08:39 UTC
I'm trying to run a very heavy patch using pd~ on windows 10. The version of Pd is 0.48-0.
I opened simply pd~ help patch with DSP on, clicked "pd~ start pd~subprocess.pd" message box, 
then the second pd window opens and the application freezes. (all windows do not react to my mouse clicks)

**Comment by Lucarda** [comment] 2017-11-13 02:44
Strange!
I couldn't replicate the issue. I opened [pd~] help patch, start the sub-process and everything is working as expected.

Win10
Pd 0.48.0

**Comment by Spacechild1** [comment] 2017-11-21 20:37
hi, what's the output from the console? in which directory does your Pd live? pd~ doesn't like directory paths with whitespace. try to move your Pd folder to a path without whitespace and see if it solves the problem.

**Comment by Spacechild1** [comment] 2019-10-08 16:24
@chikashimiyama is this still a problem with Pd 0.50 or can we close this?

**Comment by Spacechild1** [comment] 2020-04-18 23:22
Closing because can't reproduce and OP doesn't respond. This has likely been fixed by one of my pd~ bugfixes.

**Closed by Spacechild1** 2020-04-18 23:22 UTC
Labels: crash
