### ISSUE TITLE
difference in loading via startup and [declare -lib]

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1271] opened 2021-02-16 03:07 UTC
Hi, this is somehow related to https://github.com/pure-data/pure-data/issues/1257

I found out about this when trying to manage how to load both an object from ELSE and CEAMMC that have the same name (xfade~).

As discussed in  https://github.com/pure-data/pure-data/issues/1257 once ceammc is loaded, it'll always call xfade~ from there, even if I use [declare -lib ceammc] and I'm using a separate patch without [declare] and have ELSE's path in my preferences path.

I can use [else/xfade~] to call mine instead, but this is what I found out: If I'm using [declare] I can have some control of which object I open in different patches, if I have no prefixes it opens the one from ceammc, even though I had created [else/xfade~] before.

now if you have ceammc loaded in Pd via startup, once I load "else/xfade~", I can't load the one from ceammc anymore. That's the difference.

**Comment by umlaeute** [comment] 2021-02-16 08:03
so what is the issue?
or rather: how *should* it behave? how do you propose 

the problem is, that (as i have written in #1257):
> we don't have a per-canvas (or per-patch) resolution of objectnames.

so what happens in your last example is:
1. you have *ELSE* in your startup paths
2. you start Pd (and *ELSE* gets added to the search paths)
3. you load the *CEAMMC* library
  - the *CEAMMC* library's `setup` function registers the `xfade~` object name
4. if you know create an `[xfade~]` object (*anywhere* in the running Pd instance), it will be the one from *CEAMMC* -  because the object registry is *global* (see #1257)
5. now you create an object `[else/xfade~]`
  - Pd doesn't know about `else/xfade~` (it only knows about `xfade~` but those are quite different names), so it starts the loading mechanism
6. the *else/xfade~.dll*'s `setup` function (which is called by the loader) registers the `xfade~` object name
  - it doesn't care about whether the name is already registered and happily overwrites it
  - however, it *does* print out a warning on the console (at high verbosity) that the old classname has been overwritten
5. if you know create an `[xfade~]` object (*anywhere* in the running Pd instance), it will be the one from *ELSE* -  because the object registry is *global* (see #1257) and the last objectclass that registered the name `xfade~` was from *ELSE*.


what happens in your first observation is:
1. you create your first object `[else/xfade~]`
  - this will trigger the loading mechanism, which eventually calls the object's `setup` function
  - this in turn will register the `xfade~` objectname
 2. Pd also notes that you invoked the object as `[else/xfade~]` rather than just `[xfade~]`, so as a service for you it will also *automatically* register the `else/xfade~` name for the same objectclass.
 3. henceforth, whenever you create an `[else/xfade~]` object, it will be the one from *ELSE*
 4. henceforth, whenever you create an `[xfade~]` object, it will also be the one from *ELSE*
 5. now you load *CEAMMC* using e.g. `[declare -lib ceammc]`
  - this - as always for not-yet-loaded libraries - will trigger the loading mechanism, which in turn calls *CEAMMC*s `setup` function 
 6. ... which in turn registers the `xfade~` objectname  
  - it doesn't care about whether the name is already registered and happily overwrites it
  - however, it *does* print out a warning on the console (at high verbosity) that the old classname has been overwritten
5. if you know create an `[xfade~]` object (*anywhere* in the running Pd instance), it will be the one from *CEAMMC* -  because the object registry is *global* (see #1257) and the last objectclass that registered the name `xfade~` was from *CEAMMC*.
5. if you know create an `[else/xfade~]` object (*anywhere* in the running Pd instance), it will be the one from *ELSE* -  because the object registry is *global* (see #1257) and the last objectclass that registered the name `else/xfade~` was from *ELSE*.

that's about it.

i'm closing this ticket as:
- you can trigger this behaviour both from "startup" and via `[declare -lib]` (the only important thing is the order in which objectnames are registered), so I think the bug-report *as such* is invalid
- the real *bug* (if you want) is that Pd's object name registry is *global* rather than *canvas-local* (or *patch-local*). if you think this needs fixing i think you should just create a feature request for *exactly* this: a local object name registry. 

as a conclusion i'll just repeat what i've written in #1257 
> currently it is practically impossible to change this, as we don't have a per-canvas (or per-patch) resolution of objectnames.
iirc, there has been attempts a couple of years ago to add per-canvas resolution of objectnames, but this requires a major rewrite of the object instantiating code, and afair didn't come to a proper solution.
>
> so I'm pretty sure this is a "won't fix" for now.

**Closed by umlaeute** 2021-02-16 08:03 UTC

**Comment by umlaeute** [comment] 2021-02-16 08:05
sidenotes:

i'm suggesting a new "clean" feature request (as opposed to turning this bug-report into a feature request), because i think it is already muddled too much with the peculiarities of specific examples.
for something as grand as a change from global to local name resolution, we probably need a clean slate to start thinking.

and of course: if you are convinced that this is ticket is an issue on its own (with respect to #1257 and the potential new feature request), please say so so we can re-open it...

**Comment by porres** [comment] 2021-02-16 17:59
thanks for clarifying, I see it now.

So we can think of this feature of adding it locally instead of globally, but like you said, that's a bit complicated.

The issue is that we need a better way to control what objects to load and now that I think of it, this PR seems like a solution https://github.com/pure-data/pure-data/pull/630
