### ISSUE TITLE
nsis script fails with path issues while building on native windows

### ISSUE THREAD

**Issue by sebshader** [pure-data/pure-data#2073] opened 2023-08-01 21:54 UTC
When creating a windows installer using the provided nsis scripts (using msys2), it fails with something like:
```
!include: could not find: "/tmp/tmp.EWn40Bymzk/license_page.nsh"
Error in script "C:/msys64/tmp/tmp.EWn40Bymzk/pd.nsi" on line 142 -- aborting creation process
```
(this was using UCRT64 but also occurs w/ mingw iirc)
the actual file generated is at ```C:/msys64/tmp/tmp.WvWpL8Vj1h/license_page.nsh```

this isn't even remedied by manually putting the correct path into ```build-nsi.sh```, or by 06d66324e5c89e9dd1b4388c10ff8522d5b8acd6, even though then the 'could not find' error references the correct file location above, that the file does exist at.

however, as mentioned in ```pd.nsi``` everything works fine if:
-```/tmp/``` is taken out of the paths in ```pd.nsi```, except for ```OutFile``` and
-```C:/tmp``` is created in order to use default output file (haven't tested trying to change the output file too much)

There could be some kind of configuration to set this, or it should at least be documented outside of ```pd.nsi``` itself.

**Comment by Lucarda** [comment] 2023-08-02 08:39
following @umlaeute intention on 06d6632 whats happening is that nsis (on Windows) expects the path written in the file as windows paths not unix paths.

so:

```
# if we are on mingw/cygwin, we have to unmangle the directories
WWORKDIR=$(cygpath -m "${WORKDIR}\\" | sed 's|/|\\\\|g'   || echo "${WORKDIR}/")
WOUTDIR=$(cygpath -m "${OUTDIR}\\" | sed 's|/|\\\\|g'   || echo "${OUTDIR}/")
echo ${WWORKDIR}

# uninstall/license/... information into pd.nsi script
cat "${SCRIPTDIR}/pd.nsi" | sed \
	-e "s|include \"/tmp/|include \"${WWORKDIR}|" \
	-e "s|OutFile \"/tmp/|OutFile \"${WOUTDIR}|" \
	> "${NSIFILE}"
```

works but I think we are going in the wrong direction because there's no need to change `/tmp/` at the `.nsi` file, at least for the `include`s, the `Outfile` might be another story.

the thing is that the `.nsh` files are created in the right place from the start

https://github.com/pure-data/pure-data/blob/c0a7c16c63e86ccc8ce05c8273ccd8aec7ae044c/msw/build-nsi.sh?plain=1#L48-L55

 in the $tmp dir and also here the copy of the `.nsi` file.

so in the `.nsi` we could just go with `!include "foo.nsh"`.

**Comment by umlaeute** [comment] 2023-08-02 10:14
> so in the .nsi we could just go with `!include "foo.nsh"`.

that sound's  certainly preferable.

i think we would still mangle the `${OUTDIR}` with `cygpath` though...

sidenote: `cygpath` also has a `-w` option that directly outputs paths with forward-slashes.

**Comment by umlaeute** [comment] 2023-08-02 10:48
the problem is, that if you pipe the result of a failing command (`cygpath`) through another command (`sed`), you lose the exit code of the first one.

so it should really read:

```sh
WOUTDIR=$((cygpath -m "${OUTDIR}/" || echo "${OUTDIR}/") | sed 's|\\|\\\\|g')
```

**Comment by Lucarda** [comment] 2023-08-02 12:02
@sebshader it should be fixed with [be6da96](https://github.com/pure-data/pure-data/pull/2067/commits/be6da96705e036b6521013eb5a0677936799228f) on pull #2067

Please test.

lets keep this issue open so it auto closes on merge.

**Comment by sebshader** [comment] 2023-08-02 14:23
Yes, it works! Looks like the output file is at c:/msys64/tmp now by default

**Comment by Lucarda** [comment] 2023-08-02 15:08
@sebshader 

> (this was using UCRT64 but also occurs w/ mingw iirc)

may be you should not care about this but if iiuc things you built with UCRT* might only work with win11, or really up-to-date win10, win8, win7.

**Closed** 2023-10-23 10:29 UTC
