### ISSUE TITLE
Graphical UI problem on MacOSX 10.13.4

### ISSUE THREAD

**Issue by punktik** [pure-data/pure-data#353] opened 2018-04-28 15:39 UTC
On MacOSX 10.13.4 and Pure Data 0.48-1 (Vanilla) It is not possible "catch the mouse position. It will always sow the pointer some pixels away. So if i need to make a "cable connection" between objects - i need to figure out where would i need to put the mouse pointer to be able to "snap" to a right place. 
Extremely uncomfortable and impossible to work on a bigger patches. 
With bigger patches - the windows would just slide down the screen when on every mouse move making any kind of work impossible.

**Comment by megrimm** [comment] 2018-05-28 20:40
i can verify this behavior. although it seems to be most apparent when patch is put into "fullscreen" / space mode after clicking upper left green fullscreen button. screenshot in fullscreen shows mouse change for drawing cable well below outlet.
<img width="1680" alt="screen shot 2018-05-28 at 4 38 57 pm" src="https://user-images.githubusercontent.com/134831/40628906-d9aa4c98-6295-11e8-9dee-70d7eda7cca9.png">

**Comment by megrimm** [comment] 2018-05-28 20:46
hmmm... i guess i can not screen capture pointer so screenshot is useless.... anyway. for me the behavior is only after putting a patch into fullscreen.

**Comment by punktik** [comment] 2018-05-31 12:55
For me it is permanent, so i cannot use pd 0.48.1 at all. 
I did not try to put in fullscreen, as i never use it in full screen, so i am just hoping t is possible to resolve somehow.

**Comment by danomatika** [comment] 2018-06-14 22:32
Are you hiding your menubar or doing anything non-standard to the desktop, ie. custom window manager settings, some app configurator, etc? I've not seen this behavior.

**Comment by punktik** [comment] 2018-08-14 09:39
No, i do not hide or do something unusual.

**Comment by punktik** [comment] 2018-08-14 09:41
In the patch i am using is a lot of graph-on-parent and subpatches.

**Comment by umlaeute** [comment] 2018-08-14 09:57
@punktik so the problem only exists with specific patches (rather than *always*)?

**Comment by punktik** [comment] 2018-08-23 17:59
Actually any patch i open is behaving as described above. For now i am just not wrking with vanilla version, rather using purr-data. But this is not a good solution.

**Comment by danomatika** [comment] 2018-09-11 16:07
These seems very strange as we've not had any other reports of this kind of behavior. I've also not seen it on multiple macOS systems.

**Comment by jarmitage** [comment] 2018-10-16 14:53
Hi, I can confirm this behaviour since 0.48 as well. The Pd cursor is ~2cm above the actual mouse position.

My assumption was that this was introduced when macOS changed the default windowing system to use tabs for all applications by default.

**Comment by umlaeute** [comment] 2018-10-16 16:59
@jarmitage  is it still the case with 0.49?

**Comment by jarmitage** [comment] 2018-10-16 17:05
@umlaeute yes. Another momentary UI glitch occurs when you detach a new tabbed window from the Pd window.

**Comment by danomatika** [comment] 2020-12-17 09:37
This should be fixed in 0.51-3 and the upcoming 0.51.4 as both now use Tk 8.6.10 which improves Tks usage of the Cocoa API.

**Comment by danomatika** [comment] 2020-12-17 09:41
Also, this was most likely due to Pd handling the menubar offset manually for most windows. In fullscreen, the menubar doesn't show so the offset was wrong, ie clicks are performed 26 pixels higher than the mouse. Tk 8.6.10 seems to have corrected this.

**Comment by danomatika** [comment] 2020-12-17 09:59
I may be wrong about Pd 0.51-3 but mouse offset in fullscreen or tabs seems to working with 0.51-4. Please try this build: http://docs.danomatika.com/pdbuilds/0.52/Pd-0.51-4-macupdates2.zip

**Comment by danomatika** [comment] 2021-11-09 23:16
On my M1 MBP macOS 11.6.1 system:

* Pd 0.51-4 release: cursor positioning in a fullscreen canvas seems accurate
* Pd 0.52-0 custom prerelease build: same

It appears this issue is fixed with newer versions of Tk, thankfully. Closing for now.

**Closed by danomatika** 2021-11-09 23:16 UTC
Labels: bug/fix, os:macOS
