### ISSUE TITLE
Pd opening weird on mac, all in same window (missing information, will update later)

### ISSUE THREAD

**Issue by abreubacelar** [pure-data/pure-data#1207] opened 2020-11-04 16:56 UTC
[bug abas mac.zip](https://github.com/pure-data/pure-data/files/5489303/bug.abas.mac.zip)

i am opening this issue because one friend of mine is having trouble with pd, his pd opens all in the same window, and as he tries to detach each window pd gives this strange behaviour.

i don't have good information about his OS and his pd version, but i will update here as soon as i receive these information, just reporting if maybe someone has experienced this before and knows what is this

**Comment by umlaeute** [comment] 2020-11-04 22:11
looks like a dupe of #353

**Closed by umlaeute** 2020-11-04 22:11 UTC

**Comment by abreubacelar** [comment] 2020-11-07 00:33
thanks iohannes!, the solution there worked!
