### ISSUE TITLE
Means to set [receive] 

### ISSUE THREAD

**Issue by trancetelevision** [pure-data/pure-data#1932] opened 2023-03-24 12:07 UTC
Hi, Is there a reason for not providing means to set [receive] as with [send]'s right inlet ? It would be extremely useful and more consistent with it's signal counterpart.

**Comment by Spacechild1** [comment] 2023-03-24 15:25
Duplicate of https://github.com/pure-data/pure-data/issues/603 resp. https://github.com/pure-data/pure-data/pull/604

**Closed by Spacechild1** 2023-03-24 15:25 UTC
