### ISSUE TITLE
Request: modify other built-in objects to be consistent with [symbol] and [number]

### ISSUE THREAD

**Issue by dfkettle** [pure-data/pure-data#1254] opened 2021-01-02 23:42 UTC
Why is it that you can specify send/receive symbols with dollar variables as part of the name in the properties box for numbers and symbols, but not for any of the other built-in objects? If you try, you get an error message like "bang-$0-$1-s: argument number out of range" and the dollar sign gets replaced with a pound sign ('#') in the properties box.

Would it be possible to modify the other built-in objects to accept $ variables as part of the name in the properties box, like [number] and [symbol] do? I know there are ways of getting around this, but IMHO it complicates the code. It would be much easier if they all worked like [number] and [symbol].

I can't see how this would break any existing patches, since nobody would be using $ variables as part of the message names (because it doesn't currently work).

![PureData2](https://user-images.githubusercontent.com/8409615/103468717-23d41980-4d2a-11eb-8b2e-bafa3e96b437.jpg)
![PureData3](https://user-images.githubusercontent.com/8409615/103468721-2afb2780-4d2a-11eb-853c-7b07e24bb3cd.jpg)
![PureData4](https://user-images.githubusercontent.com/8409615/103468722-2f274500-4d2a-11eb-81cc-914ebb12f075.jpg)

**Comment by Spacechild1** [comment] 2021-01-03 01:31
Duplicate of https://github.com/pure-data/pure-data/issues/558

Possible fix: https://github.com/pure-data/pure-data/pull/953

**Closed by Spacechild1** 2021-01-03 01:31 UTC
