### ISSUE TITLE
[netreceive -u] send-back broken

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#917] opened 2020-03-28 08:50 UTC
as @millerpuckette reported on the [Pd-Dev list](https://lists.puredata.info/pipermail/pd-dev/2020-03/022358.html):

> One thing that was possible in pd 0.50 was to "send" to `[netreceive -u]` ... this
> was added by Shahrokh Yadegari a year or so ago.  I think it gets used; for
> instance I don't see how to implement jacktrip without it (as @reduzent  
> did in his netpd system and as I'm now trying to do in a Camomile plugin).

> Would it be onerous to bring that capability back?  For the moment we can
> fall back to 0.50 but we'd need a way to do this, even if it's impossible to
> do exactly compatibly with 0.50.

**Comment by Spacechild1** [comment] 2020-03-28 10:25
I just tried with Pd 0.50.2 - that's before the netobject updates - and `[send(` doesn't work with `[netreceive -u]` neither on Windows nor on Linux. Did this feature really exist at some point in time? 

The help patch explicitly says:

> "send" (for TCP connections only) sends back to connected netreceive objects

Note that I first send messages from `[netsend -u]` to `[netreceive -u]` before trying to send back (otherwise it wouldn't work in any case).

Does anyone know the commit where this feature has been apparantly introduced? Or can point me to a Pd version where this seems to work?

Anyway, it's still a nice feature to have, so we can build UDP servers.

**Comment by millerpuckette** [comment] 2020-03-28 16:12
I have this...

commit 33627264be356096ff132272dbaaf7c5cdb44145
Author: Miller Puckette <msp@ucsd.edu>
Date:   Sun Mar 20 11:23:14 2016 -0700

backward connections allowed for UDP netsend objects (thanks Shahrokh Yadegari)
 

... so 3.5 years ago, oops.  I thought it was working in 0.50 but maybe it
fell off the rails before that - will check later.

thanks
Miller

**Comment by Spacechild1** [comment] 2020-03-28 16:59
Ah! This feature is only about `[netsend -u]` - it allows to receive message sent back to its socket. This still works as expected: connect with `[connect localhost 9999 9998(` and the socket should be bound to 9998 (instead of a random port number), now you can use another `[netsend -u]` to send messages back. It didn't implement `[send(` for `[netreceive -u]`, though!

Actually, you can now also use the new outlet for `[netreceive -u]` to automatically get the IP address + port of the client and then reply to it with a `[netsend -u]` object. As I already mentioned, it would be nice if `[netreceive -u]` had something like a `[sendto(` message, so the reply could come from the same socket.

Using `[connect(` + `[netsend -u]` has another problem: it always creates a new socket and does some additional initialization, which is not necessary and could be optimized for UDP sockets... Or also add a `[sendto(` method...

**Comment by millerpuckette** [comment] 2020-03-28 20:18
Aha... thanks - I was just imagining that netreceive -u could do that.

What I'm looking for now is a way to reply to UDP messages that might come
from behind a NAT router.  Specifically, I'd like to make a vanilla-pd jacktrip
client that can hide behind NAT but still send audio bidirectionally to a
jacktrip server (which, to start with, I'd assume to have a public IPv4
address).

Rman Haefeli appears to have done this using iemnet, not netsend/receive -
and it looks like it will work to have the client just use netsend -u (so
that it can be totally Pd vanilla; I think in a VST plugin this is a major
plus).

So now all I have to worry about is the server.  Roman's solution uses a python
script on the server to send/receive net packets.  I'd like to get this also
into Pd so that I can support point-to-point communications between two
VST plug-ins.  And then in a second step, try to figure out how to allow
both plug-ins to hide behind NAT, relying on a central server only to establish
connections between them.  

(Meanwhile I'm badly overdue trying to get Pd 0.15 together - I think I'll
have to content myself with merging PRs and put off my own dev ideas for
yet another round...)

stay safe&well -
Miller

**Comment by umlaeute** [comment] 2020-03-28 21:09
>  What I'm looking for now is a way to reply to UDP messages that might come from behind a NAT router.

i just did a few experiments, and i can do UDP hole punching nicely with `[netreceive -u]`.

setup is like:
- client A
   - will use listening port `10001`
   - private IP: `192.168.1.100`
   - public IP: `192.0.2.0.72`
- client B
   - will use listening port `10002`
   - private IP: `192.168.7.22`
   - public IP: `198.51.100.190`

both clients need to know the public IP (and listening port) of the peer beforehand.

initiate session:
1. clientA: initiate connection `[connect 198.51.100.190 10002 10001(` ->` [netsend -u]`
2. clientA: send some data
    - the data won't arrive on clientB yet
    - but the NATting routerA sets up the forwarding rules
3. clientB: initiate connection `[connect 192.0.2.0.72 10001 10002(` ->` [netsend -u]`
4. clientB: send some data
    - data should arrive at clientA (2nd outlet of `[netsend]`)
5. clientA: send more data
    - data should arrive at clientB (2nd outlet of `[netsend]`)

**Comment by umlaeute** [comment] 2020-03-28 21:27
but of course, the above only works if the clients know the public `IP:port` combination beforehand.
this is what a nat-hole-punching server actually does.

afaict, the python-script in TPF only does the UDP-proxying (shifting the heavy data load away from Pd)

**Comment by millerpuckette** [comment] 2020-03-28 21:35
All interesting....

i'm curious if udpclient/udpserver would work even in the case where one
user (the "client") doesn't know their router's IP address.  I was just
getting ready to try the experiment when I saw this.  Perhaps you know
already that it won't work?

My idea:  set udpserver up on a machine with a public IP addr (or even
NATted behind one perhaps) and try to get its "broadcast" method to kick
a message back to a client that has sent it packets.

Perhaps you know in advance that this eithe rwill or won't work :)

M

**Comment by umlaeute** [comment] 2020-03-28 21:57
well yes, `[udpserver]` reports the remote IP-address after NATting, so it reports the *public* IP-address.
You can use this info to notify the (other) clients of a new peer's public IP address.

in theory it's a bit more tricky with the ports, as the NATting gateway might do port-translation in an unpredictable way.
in practice i think most "home-office" style networks (that is: consumer grade network), will not mangle the outgoing (ephemeral) ports.

btw, i would suggest to do some *rudimentary form of authentication* with the server, mostly to not step on other people's shoes. just imagine that you give out your jacktrip-via-camomille VST-plugin to a couple of people, and they start using it on their own, still using your punch-hole-server (because it's the hardcoded default in the plugin), and all of a sudden two unrelated parties start mixing up, because they just "happen to be there" at the same time.
while this *could* be fun, it could also be annoying. so adding something like a "pre-shared token" (aka: channel-name) to organize sessions, might be helpful.

**Comment by umlaeute** [comment] 2020-03-28 22:11
on re-reading the above, i missed the general outline of a hole-punching server:

### setup
- serverX
  - reachable via a public `IP:port`
- clientA, clientB
  - live in (separate) private (NATted) networks
  - don't know the public IPs

### flow
1. *clientA* sends `<channel-token> <clientA-name> <portA>` to *serverX*
    - <channel-token>: some string known to all peers (e.g. "covid19")
    - `<clientA-name>`: some string identifying *clientA*
    - `<portA>`: the port where *clientA* listens for incoming payload data
2. *serverX* notes the public IP of *clientA* and remembers it along with the data-tuple.
3. *clientB* sends `<channel-token> <clientB-name> <portB>` to *serverX*
4. *serverX* notes the public IP of *clientB* and remembers it along with the data-tuple
5. *serverX* sends the public IP:port of *clientB* to *clientA*
6. *serverX* sends the public IP:port of *clientA* to *clientB*
   - in practice *serverX* might just "broadcast" the entire stored information (public IP, port, name) of all clients with the same channel-token to all clients with that same channel-token; clients will filter out their own public IP based on the client-name
7. *clientA* opens a UDP-connection to the public IP:port of *clientB*
8. *clientB* opens a UDP-connection to the public IP:port of *clientA*
10. :tada:

**Comment by Spacechild1** [comment] 2020-03-28 22:42
@umlaeute how are `<portA>` and `<portB>` chosen? can it simply be the ephemeral port the sender is automatically bound to (and which is already part of the sockaddr)?

@ritsch I think this thread might be also relevant for us ;-)

**Comment by millerpuckette** [comment] 2020-03-28 23:14
In a partil answer to my own question - I set up a udpserver object (from
iemlib) and managed to connect to it from behind a NAT router (using
udpclient) and get messages back and forth.  To get teh message back
to teh client I used the "broadcast" message to the server.

The server hangs if more than one client connect to it; I didn't see any
way to get it back working except to re-create the server object.

But it might prove usable as a point-to-point connection where one side
is behind NAT and doesn't know its public IP addr (but so far in my tests the
"server" side has to have arranged to have a publicly-visible port).

And maybe using Iohannes's procedure it can be made to punch holes in both
directions - I have to do some other stuff now but will get back to trying this
tomorrow.

If anyone wants my "quacktrip" abstraction (and VST plugin) as they are I can
slip you a very experimental version.

cheers
M

**Comment by Spacechild1** [comment] 2020-03-28 23:30
@millerpuckette Curiously, me and @ritsch have been developing a new simple streaming protocol for peer-to-peer audio streaming (uncompressed PCM or compressed Opus). We're currently using it successfully in an art project (live streaming sounds across the city of Graz - already running for 3 weeks non-stop :-) and we're planning to release an alpha version in a few days. It comes as a simple C++ library with an optional C interface + Pd externals. You'll see it anyway on pd-announce. Give it a try if you have time!

**Comment by millerpuckette** [comment] 2020-03-28 23:33
Cool - I'll definitely give that a look.  Maybe it's going to be a lot closer
to what I need than jacktrip :)

M

**Comment by umlaeute** [comment] 2020-03-29 08:56
>  The server hangs if more than one client connect to it

ah yes. i think that's why there's an error when you load the object:

~~~
[udpserver] does not work yet
~~~


iirc, TPF uses a `[tcpserver]` (that is: *TCP*) to do all the handshaking. that's probably the saner way :-)

**Comment by porres** [comment] 2020-04-10 15:11
> (Meanwhile I'm badly overdue trying to get Pd 0.51 together - I think I'll
> have to content myself with merging PRs and put off my own dev ideas for
> yet another round...)

Too bad :/ - but on the other hand, there's already a good amount of new things, plus plenty plenty more goodies from other PRs that can make a nice update to be content about. Anyway, I remember april was the next window and I hope you're well and safe, and that the pandemic doesn't get too much in the way.

**Comment by Spacechild1** [comment] 2020-04-18 16:59
Since there's no real bug/regression, I would close this now in favour of this feature request: https://github.com/pure-data/pure-data/issues/949

**Closed by Spacechild1** 2020-04-18 16:59 UTC
Labels: bug/fix, regression
