### ISSUE TITLE
setting iemgui-labels with spaces via the [label( message breaks property dialog

### ISSUE THREAD

**Issue by sinewave-sinewave** [pure-data/pure-data#1194] opened 2020-10-27 12:09 UTC
There is an error in a  [pd display-example] subpatch. When trying to see the canvas properties (after displacing the number box 2), the popup dialog does not open and I get this message instead: 

~~~
(Tcl) UNHANDLED ERROR: wrong # args: should be "pdtk_iemgui_dialog mytoplevel mainheader dim_header wdt min_wdt wdt_label hgt min_hgt hgt_label rng_header min_rng min_rng_label max_rng max_rng_label rng_sched lin0_log1 lilo0_label lilo1_label loadbang steady num_label num snd rcv gui_name gn_dx gn_dy gn_f gn_fs bcol fcol lcol"
    while executing
"pdtk_iemgui_dialog .gfxstub25d1b90 |cnv|             ------selectable_dimensions(pix):------ 1 1 size: 0.0 0.0 empty             ------visible_rectang..."
    ("uplevel" body line 2)
    invoked from within
"uplevel #0 $docmds"
~~~

**Comment by umlaeute** [comment] 2020-10-28 12:00
which version of Pd?

i don't think i can reproduce the issue with both Pd-0.51-3test4 and Pd-0.51-2.

however, given that the "numberbox 2" is well hidden, and the selectable area of the `[cnv]` is tiny, i wonder whether I do the same as you do.

could you provide detailed step-by-step instructions on how you trigger the problem?

**Comment by sinewave-sinewave** [comment] 2020-10-28 12:20
It's 0.51-2
![pd-issue](https://user-images.githubusercontent.com/73533352/97435192-62abb480-1920-11eb-8f7e-fee06a656233.gif)

**Comment by Lucarda** [comment] 2020-10-28 12:32
strange. I can't reproduce on Windows Pd 0.51-2.

![Untitled](https://user-images.githubusercontent.com/25239522/97436256-79421380-1900-11eb-8e4b-a505cd3fc096.png)

**Comment by Ant1r** [comment] 2020-10-28 12:38
I could reproduce (Pd 0.51.3-test4).
You can open the properties *before* you drag the number2 (thus changing the canvas label), but once you drag it, then you cannot open the canvas properties anymore.
This seems to be related to internal space escaping with '\'.

**Comment by Ant1r** [comment] 2020-10-28 12:43
FYI, this issue disappears after merging PR https://github.com/pure-data/pure-data/pull/953 (named "gui properties less chars substitution/escaping").

**Comment by Lucarda** [comment] 2020-10-28 12:44
>  but once you drag it, then you cannot open the canvas properties anymore.

Confirmed on Windows.

**Comment by umlaeute** [comment] 2020-10-28 12:53
i'm so absolutely sure that there must be a bug-report explaining this already, but i cannot seem to find it no more...

**Comment by porres** [comment] 2020-10-28 16:27
there's a more general issue on label problems and we already have fixes for ir such as in https://github.com/pure-data/pure-data/pull/948

**Comment by porres** [comment] 2020-10-28 20:04
And anyway, I'm the culprit here, as I was aware of the issue when I made this new example for this new help file, but I also knew we had fixes waiting to be merged, so I went ahead and included the example anyway in my revision. Sorry.

**Comment by porres** [comment] 2021-11-04 23:54
this can be closed now!

**Closed** 2021-11-06 23:05 UTC
Labels: subject:GUI
