### ISSUE TITLE
[samplerate~] in 0.52 outputs 48000 instead of 44100 if dsp is off when you load Pd

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1429] opened 2021-11-02 22:31 UTC
When you load pd and try to get the sample rate with samplerate~ when the dsp is still off, it considers it to be 48000, even though it is actually set as 44100

<img width="457" alt="Screen Shot 2021-11-02 at 19 28 51" src="https://user-images.githubusercontent.com/5360142/139960752-85b36b69-5dbb-462a-b8ba-247bd2da74b2.png">

after you turn dsp on and try again, it correctly outputs 44100

**Comment by Spacechild1** [comment] 2021-11-02 22:58
> after you turn dsp on and try again, it correctly outputs 44100

Well, Pd can't know the sample rate before you turn on the audio. 48000 is just a default value. Note that in Pd 0.52 the default sample rate has changed from 44100 to 48000. Either way, without turning on DSP at least once, `[samplerate~]` doesn't really know what to output, so it could be literally anything.

**Comment by porres** [comment] 2021-11-02 23:10
> Note that in Pd 0.52 the default sample rate has changed from 44100 to 48000.

that explains something, but how come I get 44100 when I open the Pd?

**Comment by Spacechild1** [comment] 2021-11-02 23:18
> but how come I get 44100 when I open the Pd?

I guess you meant "start DSP"? It's probably because you have saved your audio settings with 44.1 kHz. When you start DSP it will recall your audio settings and `[samplerate~]` will output the "real" sample rate.

**Comment by porres** [comment] 2021-11-02 23:21
I completely removed Pd and reinstalled so I can see now that, in this case, it loads 48000 by default.

 don't really get why change it, cause it is more CPU intensive, but anyway, can't pd use this value from what has been saved under preferences and use it as the default value for samplerate~?

**Comment by Lucarda** [comment] 2021-11-02 23:30
how about:
![sr](https://user-images.githubusercontent.com/25239522/139965799-8b4dd87c-bb0e-43ff-9b14-b1c6527a639b.png)

**Comment by Spacechild1** [comment] 2021-11-02 23:32
> can't pd use this value from what has been saved under preferences and use it as the default value for samplerate~?

But why? The value simply is not meaningful unless DSP is turned on. In your patch you should call `[samplerate~]` whenever you need the value. It is always a mistake to call it only once in the beginning. What if the user changes the sample rate while the patch is running?

**Comment by Spacechild1** [comment] 2021-11-02 23:37
If you *really* need to cache the value, you can do `[r pd-dsp-started] -> [samplerate~]`, so it will automatically update whenever the sample rate has changed.

**Comment by porres** [comment] 2021-11-02 23:48
well, I've been using it this way and didn't know I shouldn't. It seems intuitive to me that Pd could tell me what the sample rate is even if I haven't started the DSP.

Now, what I see is that if I open Pd and have the setting at 44100, it won't know and give you 48000 instead. This doesn't look nice, maybe [samplerate~] could not output anything and give a warning instead and say "sorry, I can't know).

Now, what I just learned is that if I don't start the DSP but open the preferences and hit apply, now [samplerate~] will change from 4800 to what's set in the preferences (44100 in my case). So, well, it seems it can really know and get the value from the preferences without the need to turn the DSP on...

**Comment by Spacechild1** [comment] 2021-11-03 00:16
> So, well, it seems it can really know and get the value from the preferences without the need to turn the DSP on...

Yes, it *can* get the values from the preferences. And that's what Pd did up to Pd 0.52.

What happens in Pd 0.52 is that it would read the preferences, cache the audio settings in `audio_nextsettings` and only actually apply them when you start DSP.

I can understand that you feel like Pd should start with the saved audio preferences. And maybe it really should.

However, any patch that only relies on the initial audio settings is fundamentally broken. So in some way the behavior is good because it forces people to fix their patches :-)

**Comment by Spacechild1** [comment] 2021-11-03 00:21
I think you would agree that the output of `[samplerate~]` is useless for a patch that *never* uses DSP. In that case, the output doesn't matter.

Now, if a patch does use DSP, it has to account for the fact that the user might change the audio settings while the patch is running. It can't just cache the initial sample rate and be done. This applies even more to abstractions because they might run in a resampled subpatch (where the sample rate can really change anytime).

**Comment by Spacechild1** [comment] 2021-11-03 00:42
@porres Maybe you can update the helpfile of `[samplerate~]` to make this more clear?

**Comment by porres** [comment] 2021-11-03 01:29
> Yes, it can get the values from the preferences. And that's what Pd did up to Pd 0.52.

it still can, right? Again, if I hit apply in the preferences, it gets updated... and why can't it do it anymore?

well, this change just broke many examples in my tutorial... I get the point for patches and abstractions, but this is something else. Also, I can't use my external now that changes and sets the sample rate, that also ruins things. I'm assuming the sample rate is 44100, preferences says so, but graphs are drawn differently now plus other things. I wonder if we can just keep this functionality :/

**Comment by porres** [comment] 2021-11-03 01:33
> However, any patch that only relies on the initial audio settings is fundamentally broken. So in some way the behavior is good because it forces people to fix their patches :-)

it doesn't necessarily has to **only** rely  on the initial audio settings

**Comment by Spacechild1** [comment] 2021-11-03 01:40
> Again, if I hit apply in the preferences, it gets updated...

That's just an implementation detail.

> well, this change just broke many examples in my tutorial...

Maybe that's a good chance to fix them :-)

> I'm assuming the sample rate is 44100

The thing is, you can't really assume a samplerate. Just because your preferences currently have 44000 Hz doesn't mean that the patch will actually use it. What if the user instead opens the audio settings and changes the sample rate (or chooses another device that doesn't support the current samplerate)?

>> However, any patch that only relies on the initial audio settings is fundamentally broken. So in some way the behavior is good because it forces people to fix their patches :-)

> it doesn't necessarily has to only rely on the initial audio settings

Oh it does. If the patch would either bang `[samplerate~]` whenever it needs the value or connect it to `[r pd-dsp-started]`, there wouldn't be any problems.

Can you give me a concrete example that breaks for you?

**Comment by Spacechild1** [comment] 2021-11-03 01:45
But yeah, I am sure that I also have patches that will break with the new behavior. I'm just not sure if that is a good or a bad thing :-)

**Comment by Lucarda** [comment] 2021-11-03 01:53
These new defines will also break my Pd Albums :) (will have to do updates somehow)	
	
https://github.com/pure-data/pure-data/blob/master/src/s_stuff.h#L83

https://github.com/pure-data/pure-data/blob/master/src/s_stuff.h#L136

The user is supposed to download; install Pd and play it. all the math is on 44100. (now Pd will be running 48k)

**Comment by Spacechild1** [comment] 2021-11-03 01:57
> all the math is on 44100

I once had written an external that accidentally assumed 44.1 kHz. Then I played a show with an audio interface that only support 48 kHz. I was wondering why everything sounded detuned. The next day I found the bug and fixed the external.

The moral of the story: never ever assume sample rates.

**Comment by Lucarda** [comment] 2021-11-03 02:01
how do change Pd's sample reate without using 

````
[audio-dialog $1 0 0 0 2 0 0 0 $1 0 0 0 2 0 0 0 44100 80 -1 64 (
|
[s pd]

````
?

`$1` and `$2` is the soundcard No.

**Comment by Spacechild1** [comment] 2021-11-03 02:02
Actually, I see another problem with the new default sample rate of 48 kHz:

`[readsf~]` can't resample, so the soundfile must match the current sample rate. Many people have been using soundfiles with 44.1 kHz because that was the default sample rate of Pd. If someone opens such a project with Pd 0.52 on a new computer and doesn't look closely, they would accidentally play all the files at the wrong sample rate...

**Comment by porres** [comment] 2021-11-03 02:03
> What if the user instead opens the audio settings and changes the sample rate (or chooses another device that doesn't support the current samplerate)?

my patch takes care of that, my external [sr~] too. It even takes care now when the DSP starts, so the actual 44100 samplerate takes effect. It's just annoying that my precomputations on the tutorial examples thinks the sample rate ought to be something it won't be unless someone goes there and changes to what it wrongly assumed to be...

**Comment by Lucarda** [comment] 2021-11-03 02:03
> accidentally play all the files at the wrong sample rate

that's exactly what i'm facing

**Comment by Spacechild1** [comment] 2021-11-03 02:09
> my patch takes care of that, my external [sr~] too. It even takes care now when the DSP starts, so the actual 44100 samplerate takes effect. It's just annoying that my precomputations on the tutorial examples thinks the sample rate ought to be something it won't be unless someone goes there and changes to what it wrongly assumed to be...

I see.

I actually think that Pd shouldn't change it's default sample rate since many projects implicitly rely on it and sometimes there is not even a way to automatically adapt at all, like in @Lucarda's case.

**Comment by Spacechild1** [comment] 2021-11-03 02:10
@millerpuckette Is there a specific reason why you changed the default sample rate to 48000?

**Comment by porres** [comment] 2021-11-03 02:11
I also don't get why change to 48khz, it just consumes more CPU and it's not that common for files and everything

**Comment by Spacechild1** [comment] 2021-11-03 02:15
> I also don't get why change to 48khz,

One possible explanation ist that it's the default sample rate of Jack. Not that I think it's a good argument :-)

**Comment by Lucarda** [comment] 2021-11-03 02:19
As for my case I could happily live with an internal like [else/sr~]. May be add a method to [samplerate~] to `set` Pd's SR.

**Comment by millerpuckette** [comment] 2021-11-03 02:20
It's also the default sample rate (I think) in both MacOS and Windoze.  If you run Pd at 44k1, the OS then resamples your audio on the way in and out.
48K is technically way better since it's possible to make much better anti-aliasing filters with shorter filter kernels (so less latency).
I like the idea of having samplerate~ have a message to set SR.  Also it would be good to have a way to get notified when it changes.

**Comment by Spacechild1** [comment] 2021-11-03 03:11
> It's also the default sample rate (I think) in both MacOS and Windoze.

Are you sure? At least on Windows, I don't think there is something like a default sample rate. There is just the current system sample rate, which can be 44100, 48000, 96000 or 192000.

I've skimmed through the portaudio and rtaudio code. For all the Windows backends, they would both just iterate over a list of sample rates and check if they are supported. Both prefer 44100 over 48000 as the default sample rate.

> 48K is technically way better since it's possible to make much better anti-aliasing filters with shorter filter kernels (so less latency).

I would claim that this is a bit of a special case :-) If someone wants 48000, they can always choose it.

> I like the idea of having samplerate~ have a message to set SR.

+1

> Also it would be good to have a way to get notified when it changes.

On the one hand, we already have `[r pd-dsp-started]` which is also mentioned in the help patch of `[samplerate~]. On the other hand, having something like a second outlet for change notifications could encourage more users to actually use it :-)

---

The actual problem is that there are projects which rely on the default samplerate of 44100, either because they are slightly buggy or because of certain limitations in Pd, e. g. `[readsf~]` not being able to resample. When shipping such projects to other people, we would now have to tell them to change the sample rate in the audio settings.

I think after 25 years it's better not to touch the default sample rate :-)

**Comment by porres** [comment] 2021-11-03 03:24
it seems it is for macOS indeed, but when using Pd "for real", I use a dedicated sound card and make sure to set it to 44100 ;)

**Comment by porres** [comment] 2021-11-03 04:27
anyway, to me, I still don't get why [samplerate~] can't report what the sample rate is from what's set in the preferences. If the idea is that it isn't reliable because the DSP ain't on, it shouldn't output anything and say so. For now it's just tryng to guess and making a mistake...

**Comment by Spacechild1** [comment] 2021-11-03 04:44
> I still don't get why [samplerate~] can't report what the sample rate is from what's set in the preferences

It just simplifies the implementation to use Pd's default values. And if all our patches were programmed correctly so that they dynamically react to sample rate changes, this wouldn't be a problem at all. Unfortunately, many patches are buggy and would break (including my own). So from a pragmatic point of view I understand your concerns. 

> it shouldn't output anything and say so

Then you would have to guard all `[samplerate~]` objects so that you don't bang them before DSP is started. Many existing patches would be flood the console with red messages. Again, the problem is not banging `[samplerate~]` while DSP is off, the problem is about not adjusting to sample rate changes.

**Comment by danomatika** [comment] 2021-11-03 14:28
Not going into the details, but to me if Pd starts with a sound api and input or output device selected, it should be able to grab the sample rate before starting DSP. With PortAudio I believe you init PA, then can query the connected devices *without* having to start a stream.

**Comment by Spacechild1** [comment] 2021-11-03 14:58
> Not going into the details, but to me if Pd starts with a sound api and input or output device selected, it should be able to grab the sample rate before starting DSP. With PortAudio I believe you init PA, then can query the connected devices without having to start a stream.

Just to be clear: Would you want to start with the default sample rate as shown by portaudio *instead* of the sample rate saved as part of the audio settings? Or rather start with the former and let it be overriden by the latter? Those two can obviously be different.

> I believe it's not good practice to rely on existing "magic numbers" but use [samplerate~]

I think everyone agrees on that. However, there are examples (see above) where a patch really has to run at a certain samplerate, e. g. because all your audio files are rendered and 44.1 kHz and you play them back with `[readsf~]`. In that case, being able to programmatically force the sample rate would be the safest way to achieve that. Of course, existing patches couldn't do that and changing the default sample rate would break them, when running the patch on a new computer. I think we should only change Pd's default sample rate if there is a really good reason to do so.

> so the fix to me is to loadbang [; pd dsp 1 < when the patch starts, probably after a delay of 100 ms to avoid well known setup timing issues when Pd is first started.

I think the real fix is to always recompute sample rate dependant stuff whenever the sample rate changes. At the moment, the only reliable option is to use `[r pd-dsp-started]`, but something like a second outlet to `[samplerate~]` could make it more intuitive.

**Comment by Spacechild1** [comment] 2021-11-17 23:58
fixed with https://github.com/pure-data/pure-data/commit/3c1063f0dee36351be8330856d848ad900b35409

**Closed by Spacechild1** 2021-11-17 23:58 UTC
