### ISSUE TITLE
Double-quotes in label message causes freeze on Ubuntu

### ISSUE THREAD

**Issue by apprentiLAB-Suzanne** [pure-data/pure-data#1972] opened 2023-06-09 12:20 UTC
Hi,
I'm encountering an error when trying to use double-quotes `"` in a label message [label "(
I've tried on MacOS and everything works fine, haven't tested on Windows or other distros (I'm on Ubuntu 22.10 kinetic).

I'm not sure if this should be reported as a bug, or perhaps a feature request to escape double-quotes with backslash ?

Here's the error : 
```
(Tcl) UNHANDLED ERROR: extra characters after close-quote
    while executing
".x55bcea3ad440.c itemconfigure 55bcea3e1980LABEL -text [::pdtk_text::unescape "" "] 
.x55bcea3ad440.c itemconfigure 55bcea3fa280X1 -fill #000000
.x55b..."
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 $docmds".x55bcea3ad440: no such object 
x55bcea3ad440: no such object
x55bcea3ad440: no such object
...
```
it then goes on like this forever and I have to force quit.

**Comment by umlaeute** [comment] 2023-06-12 06:54
unable to reproduce with Pd-0.53-1 (as shipped in Debian/bookworm, Ubuntu/lunar,...)

Ubuntu/kinetic comes with Pd-0.52-1 (and for Pd-0.53 the core/GUI communication was revamped in order to fix various quoting bugs)

**Comment by umlaeute** [comment] 2023-06-12 06:55
closing this as "oudated"

**Closed by umlaeute** 2023-06-12 06:55 UTC
Labels: bug/fix
