### ISSUE TITLE
ALSA MIDI input chokes Pd on Linux

### ISSUE THREAD

**Issue by mxa** [pure-data/pure-data#895] opened 2020-02-17 23:22 UTC
![midi-stall](https://user-images.githubusercontent.com/1220707/74691802-8e4c9b80-51e4-11ea-86cd-206b8061e894.gif)

OS: Linux. ALSA MIDI
The input is just 6 controller values every 8 ms.
Coming from a Sensel Morph. Works for about 15 min or so. Then Pd becomes unresponsive. If the MIDI input is disconnected in the QjackCtl Graph, Pd regains its consciousness and work can continue until the next time it hangs.
Maybe **not** related: https://github.com/pure-data/pure-data/issues/554

**Comment by mxa** [comment] 2020-02-17 23:27
The sensel Morph connected to Pd on windows has the same issue, only that it's much much worse, Pd 0.49 is stalling after 5 seconds of MIDI data already.

**Comment by Spacechild1** [comment] 2020-02-17 23:35
> Pd 0.49 is stalling after 5 seconds of MIDI data already.

#554 was a bug in Pd's portmidi backend (mainly used on Windows and macOS) and has been fixed in Pd 0.50. Can you try again with Pd 0.50 on Windows, so we can see whether this bug is specific to the ALSA backend or is also present with portmidi?

**Comment by mxa** [comment] 2020-02-17 23:42
> > Pd 0.49 is stalling after 5 seconds of MIDI data already.
> 
> #554 was a bug in Pd's portmidi backend (mainly used on Windows and macOS) and has been fixed in Pd 0.50. Can you try again with Pd 0.50 on Windows, so we can see whether this bug is specific to the ALSA backend or is also present with portmidi?

I confirm that it works on Windows with Pd 0.50-2

**Comment by Spacechild1** [comment] 2020-02-17 23:50
Cool. Actually, I doubt this is immediately related to #554 because @umlaeute said he couldn't reproduce the problem on alsamidi:
> at 2ms, i haven encountered any problems.
> going down to 1ms, packages start getting dropped, but they keep getting in.

**Comment by umlaeute** [comment] 2020-02-21 15:36
well, i probably did only run my tests for a couple of minutes, and not for 15 mins.

i also never tested with/use real MIDI hardware.

**Comment by mxa** [comment] 2020-02-22 16:14
This test seems to run fine:
![image](https://user-images.githubusercontent.com/1220707/75095584-b4808b80-5596-11ea-9272-982c024421a6.png)
I wonder what else I could test.

**Comment by mariobuoninfante** [comment] 2020-02-23 20:48
Ubuntu Studio 16.04 - Pd 0.50.0 - Jack settings: SR: 48000 Frame/Period: 256 Frame/Buffer: 3 - in Pd I have 4 MIDI ins/outs
___
Even just sending/receiving 1 byte every 1 msec can cause Pd to get stuck.

**STEPS**
- via Jack connect Pd MIDI OUT 1 to MIDI IN 1
- create a patch that sends 1 byte MIDI msg (ie clock: 248 (0xF8) ) every 1 msec - see attached picture 
- turn ON the metro

**RESULTS**
- Pd becomes unresponsive as in the UI don't respond to user input anymore
- disconnecting MIDI OUT to MIDI IN via jack fixes the issue (this suggests that sending MIDI at that rate is ok, but receiving is not)
- when [metro] is set to anything > 1, the issue is not there (at least doesn't manifest itself in that way, didn't check overall performance of Pd)


![Pd_clock_msg](https://user-images.githubusercontent.com/20879405/75119708-45ca2d80-567d-11ea-9089-c51e0684f936.png)

**Comment by mariobuoninfante** [comment] 2020-02-23 21:05
that said I can't get it stuck sending MIDI from other programs.
I tried sending MIDI (1 and 3 bytes msg) from ChucK to Pd every 1 msec, and everything was alright, Pd was responsive as usual.

**Comment by mariobuoninfante** [comment] 2020-02-23 21:12
Ok I managed to repro sending MIDI from ChucK to Pd.
From ChucK I'm generating 10 note on msg per msec, so 30 bytes per msec.
In Pd I have a new patch with only a number box used to check whether or not Pd is still responsive.
I turn on the ChucK script that sends these msg in loop, and Pd is fine, I stop the script, and the UI in Pd is stuck.
To fix this I then need to disconnect ChucK from Pd (MIDI).

**Comment by mariobuoninfante** [comment] 2020-02-24 09:17
MacOS 10.13.1 - Pd 0.50.2 - MIDI from ChucK to Pd via virtual MIDI port

I can get a similar behavior on MacOS High Sierra where if I send 10 noteon msg from ChucK to Pd every msec, then Pd UI gets stuck. 
The only difference is that here after few seconds, even without doing anything in Pd, the connection _breaks_ and or:
- ChucK stop sending MIDI to Pd
or
- Pd stop receiving  MIDI from ChucK
or
- both

I'll try to spend a bit more time on this, trying different things like with Max and maybe a DAW

**Comment by mariobuoninfante** [comment] 2020-02-24 09:24
same behavior sending MIDI from Max MSP to Pd with the patch showed in the picture
<img width="156" alt="Screen Shot 2020-02-24 at 09 21 39" src="https://user-images.githubusercontent.com/20879405/75140650-37186080-56e7-11ea-8086-704ef279a42a.png">

interestingly though, it seems like Pd is not the only thing affected by this. I get the same behavior sending MIDI from Max to MIDI Monitor.
The latter monitors the MIDI msg, but after few seconds stops.
Now I'm not sure is MIDI Monitor not able to monitor msg or Max not sending msg anymore.

**Comment by umlaeute** [comment] 2020-02-24 09:55
i can reproduce the problem on Linux (Debian/sid).
Running an `strace` on the process, these are the last two lines I see before Pd gets stuck:

~~~strace
read(3, 0x55f4a9e92dd0, 14000)          = -1 ENOSPC (No space left on device)
read(3,
~~~

`ENOSPC` is handled by RtMidi as "MIDI input buffer overrun":


https://github.com/thestk/rtmidi/blob/0b5d67c0f738aa2b0f3e658d26c638434ee518f8/RtMidi.cpp#L1560-L1562

**Comment by mxa** [comment] 2020-02-24 12:35
@umlaeute does this mean we should file an issue there?

**Comment by umlaeute** [comment] 2020-02-24 13:10
no, for alsamidi we are using a native implementation, not RtMidi. i was only mentioning it as a reference about what the error is supposed to tell us)

**Comment by umlaeute** [comment] 2020-02-26 12:58
> i can reproduce the problem on Linux (Debian/sid).

btw, as @mariobuoninfante observed, it's much easier to make Pd hang, if the MIDIout of Pd goes to it's own MIDIin (which is what i tested).
sending data from one Pd instance to another does not stall if a send a note event each millisecond (while i haven't tried sending more data, i expect it to fail eventually, just as with ChuCK vs Pd)

**Comment by mxa** [comment] 2020-02-26 13:25
In the Pd console I read `warning: MIDI timing FIFO overflowed` when I set the metro to 1 in above patch.

**Comment by mxa** [comment] 2020-02-26 23:45
> This test seems to run fine:
> ![image](https://user-images.githubusercontent.com/1220707/75095584-b4808b80-5596-11ea-9272-982c024421a6.png)

I just had these patches running fine for several hours and decided to shut it down. I just closed patch of the sending Pd instance and now the receiving Pd hangs. :question:

**Comment by mxa** [comment] 2020-02-28 17:30
This is reproducible. The patches above run smoothly for hours, but closing the sending patch will freeze the receiving Pd instance. Not every time, but enough to be easily reproducible.

**Comment by mxa** [comment] 2020-03-02 11:46
Francisco Medeiros confirmed the issue with Pd 49.0 on Ubuntu 18.04.4 LTS.

**Comment by mariobuoninfante** [comment] 2020-03-02 21:00
Ubuntu 16.04 64bit - Pd 0.50.0
I tried changing MIDI driver from _seq_ to _raw_ and I got the same results.

**Comment by mxa** [comment] 2020-03-05 13:07
It was recommended to me to try increasing the buffer of ALSA MIDI.
```
sudo modprobe -r snd_seq_midi
sudo modprobe snd_seq_midi input_buffer_size:65536
```
did not change the issue.

**Comment by mxa** [comment] 2020-03-05 21:30
The two patches to test with are included here.
[Pd_ALSA_MIDI-test.zip](https://github.com/pure-data/pure-data/files/4295208/Pd_ALSA_MIDI-test.zip)
Open each patch in a separate instance, connect them vial ALSA MIDI and then activate the metro in Pd1.pd. The close the patch and see if Pd2.pd is still editable or frozen. If not frozen, open Pd1.pd again, activate the metro and close the patch again. repeat until Pd2.pd is frozen. Usually 2-3 times. You can unfreeze the receiving Pd bz disconnecting the ALSA MIDI connection (in the QjackCtl Graph window for example).

**Comment by mxa** [comment] 2020-03-06 15:18
I can confirm that above fix solves the issue. Great work IOhannes, many thanks!

**Closed** 2020-04-16 23:07 UTC
Labels: bug/fix, pending, subject:core
