### ISSUE TITLE
Terminal's font smaller in 0.51-3 test 1 (macOS Mojave)

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1183] opened 2020-10-15 15:56 UTC
Here's a screenshot, left is 0.51-2, right is 0.51-3 test 1

<img width="1028" alt="Screen Shot 2020-10-15 at 12 54 06" src="https://user-images.githubusercontent.com/5360142/96154873-a85e8b00-0ee5-11eb-9806-2c425799b431.png">

Anyway, feels pretty small to me, makes me reach for my glasses :)

**Comment by umlaeute** [comment] 2020-10-15 19:51
why don't you just change the font to whatever you want it to be?

**Comment by porres** [comment] 2020-10-15 20:06
It seems like a bug because new objects are still be created in the font size = 12, the new default. But I see now the font size somehow is defined as "10", even though we create new objects as "12", so yeah, I dunno, something looks werd.

**Comment by porres** [comment] 2020-10-15 20:37
I have to close this as I can't reproduce this anymore. I tried a fresh install for 0.51-2 and then opened a newly downloaded 0.51-3 test 1 and nothing really happened!

I guess the issue may have happened somehow when I was compiling Pd before the test release was available. I noticed the font was smaller/funny but thought that the release would be distributed correctly and was probably some compiling issue (like not carrying the correct tcl/tk version or something, I dunno).

**Comment by umlaeute** [comment] 2020-10-15 20:41
so what exactly is the bug?
- that the default font-size of new objects is not the same as the default font-size of the menu?
but hey, even the *font* (family) is different, so what is the point?
(DejaVuSans looks nice in the console, but a bit weird in the menus;
otoh, i would *love* to have a fixed-width font in both the patches and the console; but i guess the DejaVu lobby and the pixel geeks would see to prevent that)

- or is it, that the font-size of the menu is different compared to the menu font-size in the last iteration of Pd (as your title suggests)?
because for me, it is the other way round (and i'm actually glad about that).
![pdconsole](https://user-images.githubusercontent.com/214034/96183465-32830f80-0f37-11eb-82be-6967bca39f89.png)

**Comment by umlaeute** [comment] 2020-10-15 20:46
also, the underlying reason for the change is, to make the font *much* bigger (and actually readable) on modern displays (retina, hidpi,...)

**Comment by porres** [comment] 2020-10-15 21:36
> or is it, that the font-size of the menu is different compared to the menu font-size in the last iteration of Pd (as your title suggests)?

yeah, it was smaller

> because for me, it is the other way round

like, bigger, right? Weird.

Well, like I said, now for me is the same... so... I'm really lost here... 

And I wouldn't mind that it'd look bigger I guess

**Comment by umlaeute** [comment] 2020-10-16 06:07
anyhow the point is, that now you can change the font-size of the menus and the Pd-console, and the changes will persist.

**Comment by danomatika** [comment] 2020-10-18 21:51
In my opinion, @porres is right and this is a "bug" insofar as I'd consider it a regression: 3c6a3c711abdd74b98f60bde6edc7090ff7496bc

For me on macOS 10.14, Pd 0.50-2 is the larger "correct size\*" while Pd 0.51-3 is "too small". It's clear to see why: Pd 0.50-2 uses font size 12 for the console while Pd.51-3 uses font size 10. Changing to font size 12 gives me the "correct size" again.

\* Correct as in, that's the size I've been looking at for years and would like it to remain so.

**Comment by porres** [comment] 2020-10-18 22:32
ok, I'm reopening this, the thing is that somehow that stopped happening for me... but it did happen though :)

**Comment by umlaeute** [comment] 2020-10-19 07:11
@danomatika well: the problem is "not here".
that is, with Pd-0.51-2 i get a font that is *much* smaller than 12.

e.g. here's a comparision of "Pd-0.51-2" on the left side vs "Pd-0.51-3test1 with fontsize=12":

![pd51_font12](https://user-images.githubusercontent.com/214034/96409840-3a1c1000-11e6-11eb-850c-5886d9754e4a.png)

of course, the one on the left-side is the one I stared at the last couple of years, and which i prefer (actually: i find the right-side barely standable (otoh, the new default (see my [other screenshot](https://github.com/pure-data/pure-data/issues/1183#issuecomment-709578774) is something i can actually work with).

anyhow, let's recap:

### what has changed and why has it changed?

- store (and restore) the font-size entered via font-menu
   - i think this is a clear fix (mostly targeted at people who had a problem with the font-size in older Pd's. now they have to  select a font-size that fits their needs only *once*)
- use non-negative font-sizes for menu/console/...
  - i think using pixel-accurate (aka: negative) font-sizes for menus/console/... is (was) an error in the first place. it is probably fine to use pixel-accurate font-sizes in the patch (which is very graphical; and people get always upset if a line is off by one pixel), but the "surrounding user-interface" should honour things like DPI,...
- use the same font-size for menus and console
 - this might be debatable. it seems a bit weird to have a large menu font and at the same time a tiny (probably illegible) console font. also, how would you change the console-font (if need be?)
    - one possible solution would be to not set the menu font **at all** and leave that to the (operating) system.
      - this *might* give you what you wanted; but might as well not.
    - as i said before, i would much more prefer to have a fixed-width font for the console as well (but i anticipated the howling pack and refrained from doing so)

### and why?
because people are having troubles reading the menu and console on HiDPI screens (right now, i only found #572 (and possibly #1084) in the issue tracker, but i do remember multiple reports).


### but what made the font-size change in the first place?
afaict, it really is the change from pixel font-sizes to point font-sizes.
this is not about `10` vs `12` (and really it is about `10` vs `-12`).
at least on my system (Debian/sid with Xfce) there is *no* point font-size that matches the old pixel font-size.
I chose `10` because it was closest to the original font-size (and 

## Conclusion
if the changes make using Pd on HiDPI a practical and joyful experience, while at the same time introducing a slightly changed default font-size for the, this is a price i would be willing to pay every day.

I think the question is: if you don't like the default font, can you change it to one that you like via the <kbd>Font</kbd>-dialog?
if so, I would ask you to just do it (and I'm sorry to have wasted so much time on this regression issue).

I would rather like to avoid adding more system-specific code ("if the user hasn't chosen a default font-size yet and they are on macOS chose 12, if they are on windows chose 7 and otherwise chose 10").

**Comment by danomatika** [comment] 2020-10-19 09:15
I didn't mean to start a long discussion, my feedback is that the size is different and I'd like it returned. I think the selectable font sizing is GREAT and much needed, I just didn't make that direct connection at first.

>I would rather like to avoid adding more system-specific code ("if the user hasn't chosen a default font-size yet and they are on macOS chose 12, if they are on windows chose 7 and otherwise chose 10").

As far as I am concerned, making macOS default 12, Linux 10, and others whatever (-12?) would fix it. There is already so many platform-specific settings as it is.

In a related note: Changing the font size in the Font dialog updates the text widget sizing in the dialog immediately, however this change isn't appleid to *all* widgets until you cause a manually refresh of the entire dialog by click on it and/or click on another Pd window. I can open another bug / PR for it.

**Comment by umlaeute** [comment] 2020-10-19 09:41
i actually forgot one thing: the straightforward way to fix it would of course be to just use `-12` as the default font-size if none is specified (as used to be the case).

i didn't do that for a simple reason: it's impossible to get back to that setting via the Font-dialog. (because `-12` is not the same as `12` (or `10` or anything else). at least on the systems i tested)

**Comment by danomatika** [comment] 2020-10-19 09:46
I think the "retina" handling in macOS is pretty good. Using 21 as default works fine here, with hide enabled or disabled, internal or external screen.

I agree that having a default which is not part of the available setting selection is a bad idea.

**Comment by danomatika** [comment] 2020-11-19 00:18
@umlaeute so do we mark "won't-fix" and close or....?

**Comment by umlaeute** [comment] 2020-11-19 08:20
dunno.
for me it is rather "wont-fix" and right now i don't see a practical way forward that would fix the issue reported here.
that is: unless the fix is to provide platform-specific defaults (that are also selectable via the font-menu)

and then there's still this: should we really
> use the same font-size for menus and console 

? and i'm not sure about the answer at all (but if it *is* a problem, it should probably be tracked in a separate issue)

**Comment by danomatika** [comment] 2020-11-19 09:05
Honestly, at this point, I'm fine with it since I was able to change the size back to 12. I think it was more an issue that we were surprised by the change.

**Comment by danomatika** [comment] 2020-11-19 10:09
>> use the same font-size for menus and console
> ? and i'm not sure about the answer at all (but if it is a problem, it should probably be tracked in a separate issue)

This is really a preference and would be for keeping the previous default behavior, as I previous discussed. However, it's easily changeable and consistent across the platforms, so it's probably not a big deal in the end.

Honestly, there are *so many* other issues right now, this has taken up too much air.

**Comment by umlaeute** [comment] 2020-11-19 17:22
well let's close it then.

**Closed by umlaeute** 2020-11-19 17:22 UTC

**Comment by danomatika** [comment] 2020-11-19 19:09
As a small follow up, I'd say it might good to note in the manual that the console font size can be changed using the Font dialog when the Pd window is focused.

**Comment by Lucarda** [comment] 2020-11-20 00:38
> but at least it would be there. :)

done with 331513a

**Comment by danomatika** [comment] 2020-11-20 22:21
Thanks
