### ISSUE TITLE
opening help file of vu triggers tcl error

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1746] opened 2022-09-08 17:02 UTC
this is on the current master and yet another iemguis regression

![Screen Shot 2022-09-02 at 14 41 18](https://user-images.githubusercontent.com/5360142/189182401-3d7e6429-ec35-42be-a117-b75dea57eeb3.png)

**Comment by porres** [comment] 2022-09-08 17:03
it seems that if you create the object, all is fine though

**Comment by umlaeute** [comment] 2022-09-09 08:35
unable to reproduce on current `master` (3990e8883511889e6094642b95e223caf4b29f83)

however, the error comes form the `[output~]` module hidden in `[pd example]`. I seem to remember that you wanted to improve that one as well. would you be using a customized  `[output~]`?

it's obviously one of those errors where 

> this is on the current master

which git-commitish?

> it seems that if you create the object, all is fine though

which object?

**Comment by porres** [comment] 2022-09-10 14:31
damn, can't reproduce it anymore :/ 

> the error comes form the [output~] module hidden in [pd example]

oh really? well, not anymore and no, I wasn't using a new one. I guess we can close this

**Comment by porres** [comment] 2022-09-11 05:48
The issue happens with my out~ abstaction from ELSE, which is similar to output~

**Comment by umlaeute** [comment] 2022-09-11 15:51
please provide a minimal working example (preferably a self-contained example that does not require anyone who wants to tackle the bug to install 3rd party externals)

**Comment by umlaeute** [comment] 2022-09-12 06:34
i think it's a simple dupe of https://github.com/pure-data/pure-data/issues/1740 and therefore i'm closing it.

if you think this is an error, please provide a minimal example and we can re-open it.

**Closed by umlaeute** 2022-09-12 06:34 UTC
Labels: bug/fix, regression, subject:GUI

**Comment by porres** [comment] 2022-09-13 04:08
yeah, looks like it
