### ISSUE TITLE
add-to-path in a library's binary doesn't have priority when using [delcare -lib library]

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1179] opened 2020-10-07 21:24 UTC
what do I mean?

Well, some libraries rely on the "add-to-path" message to add a path to preferences=>path. So when you load the binary,  it also loads the path. This is useful if your library also needs a path besides loading the binary and this happens, for instance, if besides a single binary pack you also have abstractions that need the path.

So, GEM uses this I believe,  cyclone too, and now even "ELSE". But the thing is that if you just have [declare -lib library] on your patch, it does not guarantee that the path added via "add-to-path" will have a priority. So if you have other paths that are loaded before by the user in preferences=>path, those will actually have a priority.

I guess this is reasonable as "add-to-path" is more of a trick and not a function inside [declare], but it's a flawed hack if you're using it to save yourself from doing [declare -path library -lib library] as it doesn't do the same job! 

What do you say?

**Comment by umlaeute** [comment] 2020-10-08 07:24
> it does not guarantee that the path added via "add-to-path" will have a priority.

it certainly will have *a* priority; probably not the one you expect though.

please clarify which priority you expect (priority over *what*), and which one you got instead.

**Comment by porres** [comment] 2020-10-08 21:21
> please clarify which priority you expect (priority over what), and which one you got instead.

So, paths listed in preferences => path have an ordered priority, the one listed first gets searched first.

If you use [declare -path libname] you force this path to have a priority over the other ones listed there.

I expected that using [declare -lib libname] with this "add-to-path" "hack" would also force priority over the ones listed there, but it doesn't. Same happens if you use preferences => startup.

**Comment by umlaeute** [comment] 2020-10-09 11:13
> I expected that using [declare -lib libname] with this "add-to-path" "hack" would also force priority over the ones listed there, but it doesn't. Same happens if you use preferences => startup.

ah well, yes.

the order of search paths is like this:
1. search "patch local" paths (that is: paths that are declared to be needed by the patch/abstraction; typically using `[declare -path]`) - these paths are only used for searching objects that are instantiated within the patch/abstraction or any of it's children.
2. global (preferences) search paths (that is: paths that are added in the system preferences (<kbd>File</kbd>-><kbd>Preferences</kbd>-><kbd>Path</kbd>) - these paths are used for searching objects in *any* canvas.
3. global (startup) search paths (that is: paths that are added via the `-path` startup flag) - these paths are used for searching objects in *any* canvas.
3. built-in search paths (`<Pd>/extra` and friends) - these paths are used for searching objects in *any* canvas.

(each item in the above lists can contain multiple paths; they will be ordered, but "how" is not important for the problem at hand).

now, when sending an `add-to-path` message to the `pd` receiver, the path gets added *globally*: after all, `pd` is a global receiver and there's no context for a given patch/abstraction.
because it is a *global* search path, it is added **after** the *patch local* paths.

the only way to raise the search priority to the level of *patch local* search paths, is to actually add it to the *patch local* search paths.
to that, you only need to send a `declare -path <path>` message to the canvas.

**Comment by umlaeute** [comment] 2020-10-09 11:28
i'm closing this as i think it is working as expected (and sending messages to `pd` should never have any patch-local context).

what i'm not sure about is the order of global user-defined search-paths.
right now we the search-order is:

- paths from preferences  (<kbd>File</kbd>-><kbd>Preferences</kbd>-><kbd>Path</kbd>)
  - paths from `add-to-pd` (which is just a way to add paths to the preferences)
- paths from startup flags (`-path ...`)

i think that startup-flags should have precedence over file-based preferences.
but that is a different issue.

also, i just noticed that we still don't have a way to prevent paths added with `add-to-path` from being saved along with the preferences. (that would be PR #510)

**Closed by umlaeute** 2020-10-09 11:28 UTC

**Comment by porres** [comment] 2020-10-09 17:15
> now, when sending an add-to-path message to the pd receiver, the path gets added globally:
> after all, pd is a global receiver and there's no context for a given patch/abstraction.
> because it is a global search path, it is added after the patch local paths.

fair enough

> what i'm not sure about is the order of global user-defined search-paths.
> right now we the search-order is:
> 
> paths from preferences (File->Preferences->Path)
> paths from add-to-pd (which is just a way to add paths to the preferences)

> the only way to raise the search priority to the level of patch local search paths, is to actually
> add it to the patch local search paths. to that, you only need to send a 
> declare -path <path> message to the canvas.

So yeah, in cases like cyclone and Gem, we have to do [declare -lib libname -path libname] as the only way to guarantee it has priority! I guess I need to change the documentation of the externals section in Pd, and I also need to change cyclone's (and else). I guess I can and should just remove the "add-to-path" message from both cyclone and else as it just seems unnecessary to me now that it won't have a first priority effectiveness.

**Comment by porres** [comment] 2020-10-09 17:22
> and since it is added, it comes later in the priorities, I see...

or, as a las ditch effort, what if I was to request that the "add-to-path" message were to add it "first" in line? Instead of appending, it'd prepend it... got it?

**Comment by umlaeute** [comment] 2020-10-09 19:16
>  got it?

got what?
i get that this would
- solve your original problem about as much as the current solution (that is: not)
- have the added benefit of multiple sort-orders, breeding only confusion

no thanks.
(but then, this is just a gut feeling; i haven't actually played through multiple scenarios to see the implications of your suggestion; otoh i also have the gut feeling that your proposal is only based on a gut feeling as well)

**Comment by porres** [comment] 2020-10-09 23:30
not a gut feeling, and I'm also now thinking of adding another argument to the message instead of changing its behaviour. Adding to the path just appends the path on the list, so it has the last priority in that search... I hoped that we could also have the possibility to set it first in line so it could have priorities over the other ones in that list. Seem like a clear idea, not a "gut feeling".

But I see that would be kind of an edge case and something I'm doing instead of just using [declare -path libname -lib libname], so I could just use [declare -lib libname] instead - and for that I'd be using the "add-to-path" message that was supposed to be something for 'deken'. So yeah, feels like pushing it. And there could be other requests as alternatives, like allowing [declare -lib libname] to also add the path???? Or a -libpath flag that would do both???

just asking ;)

**Comment by umlaeute** [comment] 2020-10-10 07:18
@porres 
> Seem like a clear idea, not a "gut feeling".

the "gut feeling" was not at all about the clarity of the idea, but about the implications of its implementation.

how would that idea play out in practice? (with multiple libraries loaded, in when whichever order) would the new behaviour be an improvement overall, or a regression?
