### ISSUE TITLE
error opening audio: Internal PortAudio error

### ISSUE THREAD

**Issue by rickygraham** [pure-data/pure-data#1208] opened 2020-11-04 17:11 UTC
When I switch on DSP using Pd-0.51 (stable build) on macOS Catalina 10.15.7, I get the following error:

    error opening audio: Internal PortAudio error

I have now tried Miller's latest test build 0.51-3test5, which yields the same issue. I tried resetting microphone permissions to no avail. Currently, my operating system does not list Pd as an application which has been granted permissions to use my microphone in system preferences, security settings, etc.

I also removed `~/Library/Application\ Support/com.apple.TCC` and restarted my computer. The latest test build then produced a crash [rg_crashreport.txt](https://github.com/pure-data/pure-data/files/5489444/rg_crashreport.txt) one time but since has not crashed, instead reverting back to the original error: _error opening audio: Internal PortAudio_ error when DSP is switched on.

I'm using a MBP 15-inch 2017 / 3.1 GHz Quad-Core Intel Core i7. I’m attempting to use the built-in audio input and output on the laptop. I do have Blackhole installed, too. No JACK.

Any ideas how to resolve this issue?

**Comment by danomatika** [comment] 2020-11-04 20:58
Related notes which have been tried, but I will add here for reference:

[Reset Microphone privacy settings](https://apple.stackexchange.com/questions/339363/how-can-i-remove-applications-from-security-privacy):

    tccutil reset Microphone org.puredata.pd

or

    tccutil reset Microphone

Or [remove TCC util settings file]( ~/Library/Application\ Support/com.apple.TCC) to reset all permissions, then reboot:

    rm ~/Library/Application\ Support/com.apple.TCC

**Comment by danomatika** [comment] 2020-11-05 10:51
@millerpuckette I will have access to a new machine with 10.15 in a day or two to test. In the meantime, I pushed a small commit to the `develop` which fixes the permissions popup messages: I had accidentally swapped the camera and microphone strings. Doh.

**Comment by rickygraham** [comment] 2020-11-12 17:19
Hi, all. [This gentleman gave me a clue](https://github.com/pure-data/pure-data/issues/1208). Creating a new user account solved the problem but this is far from an ideal solution. It’s totally possible that my experience with this is a freak edge case. I just don't know. Any ideas how we can augment existing user profiles to work under Catalina without having to create a new account?

**Comment by danomatika** [comment] 2020-11-12 17:45
I did a quick test the other day on a MBP 16 running 10.15.7 and everything worked as expected the first time running Pd. I can try further to trigger it by running test builds, etc but I'm not sure what I can do if I don't see it happen.

**Comment by danomatika** [comment] 2020-11-14 07:39
With further tests, I can't reproduce the issue.

On this 10.15.7 system, the following permissions prompts open for Pd releases back to 0.48-2:

* Files and Folders: Documents
* Files and Folders: Desktop
* Microphone

This is after clearing the permissions each time with:

    tccutil reset All org.puredata.pd.pd-gui

The Microphone prompt opens when running DSP for the first time with the machine's mic input selected.


@rickygraham, denying microphone access still allows Pd to render output audio, so I think your issue is something different as you've noted. There is a timeout set before automatically closing audio with Portaudio, but the error message is different.

@millerpuckette At the least, I can confirm that the system permissions stuff does with work Pd, whether we have the

**Comment by danomatika** [comment] 2020-11-14 08:05
@rickygraham It seems you are not alone and some thing similar is happening for other audio applications as well. Some things to try:

* [Max MSP](https://cycling74.com/forums/internal-portaudio-error)
* [Mixxx](https://mixxx.discourse.group/t/macos-catalina-portaudio-errors/18514/7) (with possible fix)

**Comment by danomatika** [comment] 2020-11-14 08:07
@millerpuckette Someone seems to have also found a fix for PortAudio regarding this: https://sourceforge.net/p/sv1/bugs/273/

I can look into this later and try adding the patch.

**Comment by danomatika** [comment] 2020-11-14 22:05
After looking into the portaudio git history (they are [now on Github](https://github.com/PortAudio/portaudio)), we already have the relevant changes mentioned in that sourceforge link.

**Comment by rickygraham** [comment] 2020-11-14 23:19
Yes, it seems that the only available solution is to create a new user account. Bit of a nightmare, frankly.

**Comment by danomatika** [comment] 2020-11-14 23:45
I will close this for now as it's probably not something we can fix within Pd. Please update / reopen when needed.

**Closed by danomatika** 2020-11-14 23:45 UTC
Labels: bug/fix

**Comment by rickygraham** [comment] 2020-12-17 17:29
@danomatika - a Pd user found the solution, [here.](https://forum.pdpatchrepo.info/topic/13049/error-opening-audio-internal-portaudio-error/11).  Development AU plugs are the problem. So, it could be anything from a JUCE tutorial or something like that. Totally unhelpful problem, I'll admit. It makes no sense to me why this would cause a problem for Pd. In any case, I deleted some AU tutorial plugs and a few  AU plugs I was testing for a friend and Pd started working again. No more error!  What a horrible solution!
