### ISSUE TITLE
Request - add inlet for Vanilla receive, so you can change the name dynamically.

### ISSUE THREAD

**Issue by jaffasplaffa** [pure-data/pure-data#944] opened 2020-04-16 10:50 UTC
Hey :) 

Since the Vanilla send objects name can be changed dynamically, I think it would be really nice if the receiver also has that option. It seems odd that only one of them has that option. 

Best wishes, Jakob!

**Comment by Spacechild1** [comment] 2020-04-16 11:31
duplicate of https://github.com/pure-data/pure-data/issues/603

**Closed by Spacechild1** 2020-04-16 11:31 UTC
