### ISSUE TITLE
Bug: Double-click to edit a gatom in a GOP

### ISSUE THREAD

**Issue by ludnny** [pure-data/pure-data#1661] opened 2022-05-08 22:00 UTC
Hello!

I just discovered that you can edit a symbol box by double-clicking. 

Unfortunately, this "double-click to edit" doesn't work in a Graph On Parent
![38](https://user-images.githubusercontent.com/46849877/167317453-4471a729-cac7-43ec-955f-edb694a3b67e.gif)

Tested on 0.52.2 Win64

**Comment by umlaeute** [comment] 2022-05-09 07:05
just for completeness sake: your example shows a `list box` rather than a `symbol box`.

however, the problem appears with all gatoms (`number box`, `symbol box`, `list box`)

**Comment by Ant1r** [comment] 2022-09-15 16:39
also: when `rtext_activate()` sets the `editor.e_textedfor` field, maybe the GOP canvas is used, while it should be the parent canvas:
https://github.com/pure-data/pure-data/blob/ade0160ca291f7fb010ad15c973ed7fce7e1aae5/src/g_rtext.c#L547-L548
(I'm not sure to fully understand the overall process though...)

**Comment by umlaeute** [comment] 2022-09-16 06:46
>  the GOP canvas is used, while it should be the parent canvas:

yes. however it's much more convoluted.

**Comment by millerpuckette** [comment] 2022-09-27 01:36
It looks like I was never able to figure out how to get this working so just suppressed passing the double-click into the GOP object.

**Comment by porres** [comment] 2023-04-08 13:44
> just for completeness sake: your example shows a list box rather than a symbol box.

And for yet more completeness, it seems the restriction is in the Pd guts for whatever any other external that implements a double click feature (that we get from 'w_clickfn' in 't_widgetbehavior') - and I just wrote an external with such a feature and found the same restriction. It's funny, cause other things like shift+click and more work fine, is double click the only odd one out of the picture? What's so troublesome about it?

I am trying to implement a knob box with the same features of VCV's knob and work on some abstractions inspired by modular systems and VCV. In it, you can double click to go to a pre-defined value, like the middle of the knob which can be '0db' for a gain adjustment knob. I want to also add a feature from VCV that you can display the number that the knob is producing when dragging, and double clicking on the number would allow you to also edit the knob value manually by typing a specific number. Since the whole point is to provide external abstractions, it makes the whole deal pointless :( 

Up to now this did mostly affect being able to edit one or more elements from list boxes (as this double click feature was added in these boxes recently specially because of the inclusion of list boxes), but other externals that try to use this are also affected and I am planning to write a few more of them besides this first one. I guess externals that use double click are somewhat rare, can't think of any other that uses it. Nonetheless, not allowing any other object or external to use this feature makes it more of a crucial issue to fix and find a way.

cheers

**Comment by porres** [comment] 2023-04-08 14:03
More info... the ceammc library handles double click in external objects (and they also have a knob) with their own framework/api which seems way over my head to understand or steal... and I'd rather not have to adopt such a major workaround just because we don't have this implemented in Pd's API. The bottom line is that it's not like it's impossible or can't happen, there are externals that do this already, we just should also offer a builtin and simple solution in Pd's framework.

**Comment by porres** [comment] 2023-04-08 14:43
Ok, gave this a go... I simply replaced '0' for 'dbl' in line 1097 of graph c

https://github.com/pure-data/pure-data/blob/master/src/g_graph.c#L1097

This made my external work perfectly now... 

I see that GUI boxes still have issues in their own code so this is not a fix for this issue. I guess I'll open a new issue and propose this simple fix. 

GUI boxes would still be broken in this case, but they already are... so... no difference here.

I wonder if 'dbl' was suppressed at one point, like it was removed because of issues with list box. If so, it wouldn't make no sense to prevent externals to use double click just because of issues in gui boxes...

**Comment by porres** [comment] 2023-04-08 15:02
> I wonder if 'dbl' was suppressed at one point, like it was removed because of issues with list box. If so, it wouldn't make no sense to prevent externals to use double click just because of issues in gui boxes...

As a follow up on this, I went back to 0.48-2, way before list box was added, and I see that double click wasn't supported as well, I guess this wasn't a problem because no one ever needed it... so it's not like it was supported and removed as a safeguard for list boxes (hence, it's not a regression).

for reference, see 

https://github.com/pure-data/pure-data/blob/511f4cfd2a0332bbf3a7654102a1518f3eb95bf6/src/g_graph.c#L1048

Anyway, I opened the new more general issue and finally added the support in a new PR, see https://github.com/pure-data/pure-data/pull/1943

I guess this PR is one step needed in order to fix this more specific issue. I wonder if @umlaeute can take my PR fix for being considered a 'no brainer' and included in the 'develop' branch and then some other PR and fix can be made on top of it for this special case.

**Comment by porres** [comment] 2023-04-09 04:39
So I stared testing with https://github.com/pure-data/pure-data/issues/1942

double clicking happens you can select the whole text, rewrite it, hit enter and it's fine. This is not different than clicking and just retyping though.

The problem starts when you try to select a single element or something. Weird things happen and don't work right. You can't further click and select a portion of the list. Although the backspace key works, using up/down arrows don't work.

**Comment by umlaeute** [comment] 2023-04-11 08:53
i cannot remember the details, but I'm pretty sure that this was *not* the solution (and while allowing double clicks, it would break a number of not-obviously related things).

**Comment by porres** [comment] 2023-04-11 13:04
> but I'm pretty sure that this was not the solution

i didn't think it'd be, but I think it'd be a 1st step

> (and while allowing double clicks, it would break a number of not-obviously related things).

how so?

**Comment by porres** [comment] 2023-04-11 16:05
I think we're talking about different things. I know that allowing double click won't fix this issue, but it won't change anything as it's already broken anyway... The thing is, do you mean that allowing double clicks will break something else?

**Comment by umlaeute** [comment] 2024-12-10 07:35
afaict, this has been fixed with b4ad52871dc5375584d31bec90cd46980f3dde9e

**Closed by umlaeute** 2024-12-10 07:35 UTC
Labels: severity:bug/fix, subject:patching, subject:GUI objects
