### ISSUE TITLE
copy/paste to mouse position

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#2351] opened 2024-06-15 18:41 UTC
I think this was discussed somewhere before, but why not allow copying and pasting to where the mouse position is?

**Comment by umlaeute** [comment] 2024-06-17 06:22
i haven't made up my mind yet, but i think no other program i know will just paste to the current mouse position.
pasting will either be anchored at the current *cursor* position (in programs that have a cursors, e.g. *Notepad* or *LibreOffice Writer*, *Ardour*) or at the document root (when there is no concept of a cursor that is independent of the mouse; e.g. *the GIMP*).

i guess the reason is that the mouse position is unstable and so pasting to the current position will typically put it at the wrong place.

(otoh, it seems that *Inkscape* does paste at the current mouse position)

**Comment by porres** [comment] 2024-06-17 20:52
> i think no other program i know will just paste to the current mouse position.

Plugdata does that, so does Purr Data, not saying they know what they're doing by the way :) MAX, on the other hand, doesn't do it (and I'm not saying it knows what it does either).

I do also like that I can copy something from one window to another and it stays in the exact place, but maybe we can have both ways somehow

**Comment by ben-wes** [comment] 2024-06-17 21:21
just adding from my own experience:

i rarely (never?) leave objects at the position they are at after copy/pasting or duplicating. so the option to have an additional modifier key for these shortcuts to achieve pasting at the cursor position seems like a great enhancement of interactions to me. after all, Pd users are used to floating objects sticking to their mouse position through the mechanism of object creation, i assume?

obviously, i would not expect to just paste and "create" objects at the cursor position, but to have them in the same floating state as when creating them or when dragging a selection of objects. what's not completely clear to me there yet is: where would a selection of several objects be placed relative to the cursor position? but i'm sure there are intuitive solutions for this (most obivous one probably: upper left corner of the bounding rectangle).

not sure if i'm missing anything here, but the `Shift` modifier might be a good option here:
* `Cmd`+`Shift`+`v' to attach the copied selection in floating state to the mouse cursor
* `Cmd`+`Shift`+`d` to achieve the same without a previous `Ctrl`+`c`

... damn, i now see that i missed the fact that these are shortcuts already (i always write out `vsl` and `vradio` for these). well - that's an argument for custom shortcuts, i assume. but to stay backward compatible, it might be an acceptable option to use `Cmd`+`Option`+`v` and `d` instead.

**Comment by Spacechild1** [comment] 2024-06-17 21:30
just to give my 2 cents:

> so the option to have an additional modifier key for these shortcuts to achieve pasting at the cursor position seems like a great enhancement of interactions to me. 

+1 In my experience, both options are equally valid and have their use cases, so they should both be available to the user.

> it might be an acceptable option to use Cmd+Option+v and d instead.

Sounds good to me. Of course, there should also be a corresponding menu entry.

I'd like to point out that word processors or painting apps typically have different kinds of pasting behavior (e.g. "paste without formatting", "paste as new layer", etc.), often with dedicated shortcuts, so why not offer something similar in Pd?

**Comment by porres** [comment] 2024-06-17 21:34
Cmd+Option+v is the shortcut for vertical slider

**Comment by ben-wes** [comment] 2024-06-17 21:41
> Cmd+Option+v is the shortcut for vertical slider

no. Cmd+Shift+v is and i mentioned that. :)  ... Cmd+Option+d might collide with a macOS dock shortcut that i didn't know about though.

anyway: there's still Cmd+Control+... otherwise?

(obviously, i'm currently only checking for macOS)

**Comment by Spacechild1** [comment] 2024-06-17 21:58
> anyway: there's still Cmd+Control+... otherwise?

Only on Macs ;-)

Just as a data point: Libre Office uses "Ctrl + Alt + Shift + V" for "paste without formatting", so we don't need to be afraid of 4-key-shortcuts :)

**Comment by umlaeute** [comment] 2024-06-17 22:06
regarding additional short-cuts: see https://github.com/pure-data/pure-data/issues/2353

**Comment by porres** [comment] 2024-06-18 00:36
yeah, I don't think we should bother with setting shortcuts right now, the thing is what to do. And we can even not add a new shortcut and make it configurable, but we need a new menu entry.

I think we want a new behaviour for pasting, but we also want to keep the old one (try the same spot and disloacate it a bit if it is taken). Maybe the current (or 'old' one) would need a new special paste name and a different menu entry. That is to say we need to think of a way to change the behaviour now.

The way things are, the copied selection is pasted as a 'selection', that is a highlighted section in blue. One can then click on the selection and move it around. We can can change the behaviour to also have the pasted selection bound to the mouse position, just like when you use the "put menu" to add boxes (or their shortcuts).

If we assume that users will paste and then move things around to a new spot, this is convenient because it saves one operation that consists in clicking on one of the selected boxes. And sometimes we make mistakes and miss the click and the whole thing gets deselected, which is quite bad. So yeah, it's a good convenience. Then the user can click to place the selection where desired. This is in fact how Purr data seems to work, and I think it makes good sense. So Control + V would behave like that.

And we can think of a different paste operation, so far without shortcuts, in the edit menu, just like we have 'paste replace' without a shortcut. Not sure how to call it, "paste without draging"? :)

**Comment by ben-wes** [comment] 2024-07-01 22:20
mentioning #864 here since it is obviously connected.

(personally, i wouldn't mind replacing the ctrl+shift+v for vertical sliders as an alternative paste option - but i also got used to creating them by writing out `vsl`, which should probably disqualify my opinion on this)

**Comment by porres** [comment] 2024-07-02 00:29
> mentioning https://github.com/pure-data/pure-data/issues/864 here since it is obviously connected.

so there it is, it's more of a duplicate :)

**Comment by porres** [comment] 2024-07-02 00:29
> i wouldn't mind replacing the ctrl+shift+v 

me neither, but we needed a new shortcut for vertical slider, which would it be?

why not alt+shift+v for this alternate copy operation?

**Comment by umlaeute** [comment] 2024-07-02 06:04
closing as dupe of #864

**Closed by umlaeute** 2024-07-02 06:04 UTC
Labels: duplicate, feature, subject:GUI
