### ISSUE TITLE
expr syntax issue

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#473] opened 2018-09-17 03:25 UTC
this works when creating the object

![screen shot 2018-09-17 at 00 23 11](https://user-images.githubusercontent.com/5360142/45604996-f99ea680-ba0f-11e8-867f-c0eede2f2a43.png)

but when you reopen the patch it gets ruined

![screen shot 2018-09-17 at 00 23 41](https://user-images.githubusercontent.com/5360142/45605000-fefbf100-ba0f-11e8-8798-f4a0ef06e807.png)

I'm running 0.49, but this happens on 0.48, and the workaround is to separate the "/" with spaces. a "1/x_$0" string works, is just when using something like $f1 that this happens

**Comment by danomatika** [comment] 2018-09-17 10:27
This is probably the issue as #402.

**Comment by danomatika** [comment] 2018-09-17 10:29
It's related to the new string handling which escapes $ and other special characters. I suppose the strings in expr shouldn't be escaped (at least in the same way).

**Comment by millerpuckette** [comment] 2018-09-25 02:17
Problem already apparently existed in 0.48-2... putting off dealing with it for now.

**Comment by danomatika** [comment] 2018-09-25 02:18
Closing this as it's a duplicate of #402

**Closed by danomatika** 2018-09-25 02:18 UTC
Labels: bug/fix, duplicate
