### ISSUE TITLE
[arch-linux] problem with extras fiddle~ and bonk~ (undefined symbols)

### ISSUE THREAD

**Issue by the-drunk-coder** [pure-data/pure-data#975] opened 2020-05-05 15:42 UTC
When trying to use [bonk~] or [fiddle~] i get the following errors:

```
/usr/lib/pd/extra/bonk~/bonk~.pd_linux: /usr/lib/pd/extra/bonk~/bonk~.pd_linux: undefined symbol: __exp_finite
/usr/lib/pd/extra/bonk~/bonk~.pd_linux: /usr/lib/pd/extra/bonk~/bonk~.pd_linux: undefined symbol: __exp_finite
/usr/lib/pd/extra/bonk~/bonk~.pd_linux: /usr/lib/pd/extra/bonk~/bonk~.pd_linux: undefined symbol: __exp_finite
 bonk~
... couldn't create
```
Not sure if this is a distribution-specific issue (I'm using latest Arch) or an upstream issue. Anybody else experiences this ?

**Comment by umlaeute** [comment] 2020-05-06 19:21
possibly a case of underlinking against `-lm`.

afaict, `bonk~` doesn't explicitely link against `-lm`, but Pd does and usually this should be enough.

could you please provide the build-logs?

also, does this fix the issue:

~~~diff
diff --git a/extra/bonk~/GNUmakefile.am b/extra/bonk~/GNUmakefile.am
index 7d1e29b4..fb38dbc9 100644
--- a/extra/bonk~/GNUmakefile.am
+++ b/extra/bonk~/GNUmakefile.am
@@ -19,7 +19,7 @@ dist_external_DATA = $(PATCHES) $(OTHERDATA)
 AUTOMAKE_OPTIONS = foreign
 AM_CFLAGS = @EXTERNAL_CFLAGS@
 AM_CPPFLAGS    += -I$(top_srcdir)/src -DPD
-AM_LIBS = $(LIBM)
+bonk__la_LIBADD = $(LIBM)
 AM_LDFLAGS = -module -avoid-version -shared @EXTERNAL_LDFLAGS@ \
     -shrext .@EXTERNAL_EXTENSION@ -L$(top_builddir)/src
~~~

**Comment by the-drunk-coder** [comment] 2020-05-07 17:02
Hmm I didn't build it myself, i installed it from the official Arch repos ...

**Comment by umlaeute** [comment] 2020-05-07 18:41
then you should probably file a bug-report against the arch package.

i'm closing this for now, as it appears to be a packaging problem.

**Closed by umlaeute** 2020-05-07 18:41 UTC

**Comment by the-drunk-coder** [comment] 2020-05-09 12:35
I thought so, just wanted to make sure it's not already a known problem here ... thanks !

**Comment by dvzrv** [comment] 2020-05-09 18:54
This has been built in a pretty standard way (see [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/pd)).

The full build log can be found here:
[pd-0.50.2-2-x86_64-build.log](https://github.com/pure-data/pure-data/files/4604307/pd-0.50.2-2-x86_64-build.log)

I remember seeing the `undefined symbol: __exp_finite` error somewhere else lately and it was related to the glibc upgrad from 2.30 -> 2.31.

Given the date of the build (2020-01-17) it was definitely built using glibc 2.30 (glibc 2.31 was moved to the stable repositories in early February).

**Comment by dvzrv** [comment] 2020-05-09 19:18
I have just recompiled against glibc 2.31 and the problem is gone.

@x42 was so kind to remind me of the issue that I saw: https://github.com/ardour/ardour/commit/83cd796a474f74

It seems certain functions in libm/libc++ have been replaced by macros, which is why this now starts failing with glibc 2.31. A fix for this problem can be found in the aforementioned commit message.

**Comment by Ant1r** [comment] 2020-05-10 16:21
It appears it's not really an Arch specific problem. A colleague of mine reported the same issue on **Ubuntu 20.04** , pd 0.50.2 normally installed from `apt get`:

```
/usr/lib/puredata/tcl/../extra/fiddle~/fiddle~.pd_linux: /usr/lib/puredata/tcl/../extra/fiddle~/fiddle~.pd_linux: undefined symbol: __log_finite
 fiddle~ 1024 1 20 3
... couldn't create
/usr/lib/puredata/tcl/../extra/sigmund~/sigmund~.pd_linux: /usr/lib/puredata/tcl/../extra/sigmund~/sigmund~.pd_linux: undefined symbol: __pow_finite
 sigmund~
... couldn't create
```
I asked him for some information:
 
ldd /usr/bin/pd | grep libmvec :
`libmvec.so.1 => /lib/x86_64-linux-gnu/libmvec.so.1 (0x00007efdb5ae4000)
`

ldd /usr/bin/puredata | grep libmvec :
`libmvec.so.1 => /lib/x86_64-linux-gnu/libmvec.so.1 (0x00007f49b9e56000)
`

ldd /usr/lib/puredata/tcl/../extra/fiddle~/fiddle~.pd_linux :
```
linux-vdso.so.1 (0x00007fff79bec000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa32ebd8000)
/lib64/ld-linux-x86-64.so.2 (0x00007fa32ee04000)
```

locate libmvec :
```
/lib/x86_64-linux-gnu/libmvec-2.31.so
/lib/x86_64-linux-gnu/libmvec.so.1
/usr/lib/debug/lib/x86_64-linux-gnu/libmvec-2.31.so
/usr/lib/x86_64-linux-gnu/libmvec.a
/usr/lib/x86_64-linux-gnu/libmvec.so
```

I'd suggest to re-open this ticket...

**Comment by umlaeute** [comment] 2020-05-11 07:25
@Ant1r afaict the problem seems to be with glibc dropping symbols (and distributions not catching up), rather than a problem on the Pd side.

**Comment by Ant1r** [comment] 2020-05-11 12:55
@umlaeute do you mean distributions are building with libmvec<2.31, then distribute with 2.31? that seems weird...

**Comment by umlaeute** [comment] 2020-05-11 13:07
yes, that seems to be the case. (and this is quite exactly what @dvzrv has described, isn't it?)

**Comment by x42** [comment] 2020-05-12 00:59
To determine this look for symbols (`__expf_finite`, `__exp_finite`, `__powf_finite` etc) via objdump in the shared object: 
```
objdump -T /usr/lib/pd/extra/bonk~/bonk~.pd_linux | grep _finite
```

**Comment by fweimer** [comment] 2020-05-12 10:19
> possibly a case of underlinking against `-lm`.

It is. This a build system issue that needs to be fixed there. It just does not show up on all systems yet, but it seems to be a generic bug.

**Comment by dvzrv** [comment] 2020-05-14 18:20
This has now also been discussed on the glibc mailing list: https://sourceware.org/pipermail/libc-alpha/2020-May/113773.html
