### ISSUE TITLE
Allow default symbol in pack

### ISSUE THREAD

**Issue by sebshader** [pure-data/pure-data#1516] opened 2021-12-15 03:33 UTC
Allow default symbols in ```[pack]``` (similar to float arguments) that aren't already used as type specifiers
The only issue I can think of is future types being added to pack that have the same names.

**Comment by Spacechild1** [comment] 2021-12-15 04:28
duplicate of https://github.com/pure-data/pure-data/issues/990

**Closed by Spacechild1** 2021-12-15 04:28 UTC
