### ISSUE TITLE
"Find" can't find receive symbol in number box

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#2386] opened 2024-07-15 07:32 UTC
If I have a receive name in a iemgui like a bang button, I can search and find it via the "Find..." entry. 

But if we have it in an atom box, it can't be found

**Comment by umlaeute** [comment] 2024-07-15 07:58
duplicate of https://github.com/pure-data/pure-data/issues/2011

**Closed by umlaeute** 2024-07-15 07:58 UTC
