### ISSUE TITLE
Cursor offset on fullscreen OSX

### ISSUE THREAD

**Issue by MaxGi** [pure-data/pure-data#935] opened 2020-04-13 22:28 UTC
The cursor has an offset when you enter fullscreen on osx.

**Comment by porres** [comment] 2020-04-13 22:46
confirmed, if I try the help file of savestate, when dragging the atom box for "bandwith", I end up changing "frequency" instead.

**Comment by megrimm** [comment] 2020-07-16 16:19
same as this no? https://github.com/pure-data/pure-data/issues/370

**Comment by megrimm** [comment] 2020-07-16 16:56
Someone I am working with remotely is having this issue. I guess it only occurs after having a canvas as a tab (which i didn't even know we could do) and dragging it away from the console to its own window. He says the behavior is as expected why patch "tabbed".
![Screen Recording 2020-07-16 at 12 23 52 PM_1](https://user-images.githubusercontent.com/134831/87699726-4914a180-c763-11ea-9563-3427b0dc11de.gif)

**Comment by megrimm** [comment] 2020-07-16 17:41
tabbed behavior related to this: https://github.com/pure-data/pure-data/issues/353
so that looks like macOS pref issue. the the pixel offset is a little different than the fullscrreen behavior in that the window is never in fullscreen but pixel offset happens after un-tabing a window from the console.

**Comment by danomatika** [comment] 2020-12-17 09:42
This is a duplicate of #353. Please move further discussion there. Reopen if I'm wrong.

Also, tabbing is not explicitly supported and should not be used. We can look into disabling it for now.

**Comment by danomatika** [comment] 2020-12-17 09:43
This should be fixed in 0.51-3 and the upcoming 0.51.4 as both now use Tk 8.6.10 which improves Tks usage of the Cocoa API.

**Closed by danomatika** 2020-12-17 09:42 UTC
