### ISSUE TITLE
using `donecanvasdialog` switches to edit-mode

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#623] opened 2019-05-09 04:04 UTC
Hi, there's some bug now in Pd-0.49 that weren't there before.

The test patch explains itself. The thing is that 'donecanvasdialog' seems to force Pd to get into edit mode. 

This is not just an annoyance, it's hard for me to isolate the issue yet, but this can also make Pd crash and "blow up" (meaning, Pd closes and disappears immediately). I know I also had this when working on this test patch, but I couldn't replicate it. On the other hand I can easily see Pd crash with [else/mtx.ctl].

I'm abusing a lot of these features to design GUIs as externals  in ELSE. The [mtx.ctl] object is one of them and every time I open a patch it's contained in, the patch opens in Edit mode. And if I try to cut and paste the object => Booom! 

But all works fine in Pd-0.48-2 for instance

Anyway, here's the test patch.

[bug-edit.pd.zip](https://github.com/pure-data/pure-data/files/3160305/bug-edit.pd.zip)

and here is how it looks 
<img width="619" alt="Screen Shot 2019-05-09 at 01 04 05" src="https://user-images.githubusercontent.com/5360142/57426637-5dbbe800-71f6-11e9-9a2c-95c03726d8fb.png">

**Comment by umlaeute** [comment] 2019-05-09 07:53
- how do you trigger the "Boom" behaviour? assuming with "Boom" you mean a crash, i cannot reproduce this (or anything else really).
- what is the "donecanvasdialog" supposed to do in your "other bug"? can it be removed?

**Comment by umlaeute** [comment] 2019-05-09 08:50
the problem is a side-effect of the *infinite undo*.

the relevant code is near https://github.com/pure-data/pure-data/blob/0.49-0/src/g_editor.c#L2138

**Comment by umlaeute** [comment] 2019-05-09 09:08
on closer inspection:

- with the `donecanvasdialog` message you are actually modifying the patch.
- *typically*, any action that triggers a modification of the patch changes the patch's mode to "edit-mode".
- therefore i think it is (should be) actually *intended* behaviour to switch to edit-mode. (although previous versions of Pd did not exhibit this behaviour; but that was more a bug in the previous versions)

i acknowledge that there seem to be a couple of exceptions to the "'modifications of the patch' equals 'edit mode'", e.g. `obj 100 100 float` will create an object and not change the mode of the patch.
however,
- `donecanvasdialog` is an editor-command (that is: this message is typically sent from the GUI to the core to indicate a user-triggered action; your patch abuses (as you rightly put it) this internal editor-command to your own needs), and Pd has no way of distinguishing such scripted action from a user-triggered action)
- otoh, `obj 100 100 float` is *not* an editor-command (the GUI never sends this message), so it doesn't trigger the switch to edit-mode (probably; i'm just making this conclusion up).

so the solution is really to switch the patch to the desired state after you make changes to it.

**Comment by umlaeute** [comment] 2019-05-09 09:44
assuming the use of a subpatch in your example is motivated mainly to keep the number of files low and still trigger the same(looking) behaviour, i re-open this.

attached is a (i think) better example to trigger the problem ([donecanvas.zip](https://github.com/pure-data/pure-data/files/3161343/donecanvas.zip)).

I don't see any problem with "clear (another bug)".



PS: please also use a meaningful description of the bug in your subject, so it's easier to guess what you actually mean (i'm sure there are plenty of bugs introduced in Pd-0.49, but imagine we had 20 bug-reports with that same title; the version where the bug was introduced is usually important enough to go into the description, but it's not related to what the bug actually does.)

**Comment by umlaeute** [comment] 2019-05-09 09:58
there's also the side-effect that Pd crashes if you hit <kbd>Undo</kbd> in the containing patch.

afaict, this is really the same issue (attaching the `donecanvas`-modification to the wrong canvas)

**Comment by umlaeute** [comment] 2019-05-09 10:32
ok, so i think one solution is pretty easy, but i don't know whether is good:

- changes to the GOP-state are attached to the canvas that received the `donecanvasdialog` message (e.g. the subpatch), rather than the containing canvas.
  - this makes the containing patch not switch to edit-mode
  - this adds an <kbd>Undo apply</kbd> menu to the GOPified canvas (but *not* to the containing patch), which actually works and does not crash.

the drawbacks are:
- inconsistent places for action and it's undo:
  - the `donecanvasdialog` message might be *triggered from the containing patch* (e.g. right-click an object, select properties,...)
  - but can no longer be *undone from the containing patch*
- inconsistent with `resize`
  - if you interactively resize a GOP (dragging the right corner of the GOP on the containing canvas), this will be recorded as an event in the containing canvas (and can only be undone there)

**Comment by umlaeute** [comment] 2019-05-09 10:33
maybe @danomatika , @Spacechild1 or someone else has an opinion on this.

**Comment by umlaeute** [comment] 2019-05-09 12:01
as another data-point: i checked with Pd-l2ork, and it seems that it also switches to <kbd>Edit</kbd>-mode (although it seems it mostly does that, when switching from GOP to non-GOP rather than the other way around)

**Comment by danomatika** [comment] 2019-05-09 12:23
This might be a case where adding an explicit option would help, ie. revert to previous behavior where it ignores undo chain and add an option for new behavior.

After skimming the issue, my first though is that it "under the hood" changes like this should avoid the undo stack as they are mostly for creating GUIs. For generating a patch then save, it wouldn't be that big a deal to add a message which flips the edit mode / dirty flag manually.

**Comment by danomatika** [comment] 2019-05-09 12:24
...as with all of the recent major changes to Pd, it's too bad this did not come up during the testing / commenting phase.

**Comment by umlaeute** [comment] 2019-05-09 12:53
what's the "previous behaviour" (what's the reference point to define "previous"?).

if the reference point is "now" (and thus "previous behaviour" refers to 0.49-[01]), then there is a real problem to fix (a crash!, not just an annoying switch to edit-mode)

if the reference point is the introduction of infinite undo (so "previous behaviour" refers to <=0.48), then... i don't know.
the problem with *infinite undo* is, that it requires a fairly complete picture of the world. you cannot just exclude a single thing from the <kbd>Undo</kbd>-queue, as this would make the queue inconsistent.

> changes like this should avoid the undo stack as they are mostly for creating GUIs

hmm, not sure i understand what you mean with "changes like this"?
@porres seems to be trying to dynamically create a GUI-object. due to lack of better means, they are abusing the GUI->core protocol, tricking Pd into thinking that the user did something manually (which is exactly where we do want <kbd>Undo</kbd>).

**Comment by danomatika** [comment] 2019-05-09 12:59
"previous" = before unlimited undo

I was thinking "creating GUIs" as in dynamic patching, but it looks like this is abusing the dialog messaging system. I'd say then that this is not really a bug but falls under unexpected behavior.

If the crash is fixed, great, but I don't think the behavior should be changed to allow for edge case uses like this as it was never really guaranteed before. That and it would pollute the infinite undo system...

**Comment by umlaeute** [comment] 2019-05-09 13:06
i think we agree. i'd still like my fix (#625) to be applied, as it resolves untested (and thus buggy) code - and as a side-effect fixes this issue :-)

**Comment by porres** [comment] 2019-05-09 20:26
> If the crash is fixed, great, but I don't think the behavior should be changed to allow for edge case uses like this as it was never really guaranteed before.

I verified and can confirm that #625 fixes the issue with going into edit mode, and also the crash I was having with [else/mtc.ctl]!

**Comment by Spacechild1** [comment] 2019-05-10 21:38
although I'm a proponent of dynamic patching, I don't know why people advertized using [donecanvasdialog( instead of [coords(... with the latter you can do the very same things but it doesn't have the issues of the former. also it's much more stable because it's used in Pd patch files. the only problem is that [coords( doesn't automatically redraw the parent patch, but [map 0, map 1( takes care of that.

**Comment by danomatika** [comment] 2019-05-10 22:35
I think it would be good to have some sort of guidelines help patch for this in the manual. Sort of like the old pd-msgs folder from extended and include notes against using/abusing dialog messages while suggesting alternatives when there are any.

I know some would say that dynamic patching had never been officially supported, but it’s been successfully used for many years at this point. It might be good to at least document the suggested objects/approaches and discourage others.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by porres** [comment] 2019-05-10 23:04
> the only problem is that [coords( doesn't automatically redraw the parent patch, but [map 0, map 1( takes care of that.

you also cannot set x/y units

**Comment by porres** [comment] 2019-05-10 23:06
> I think it would be good to have some sort of guidelines help patch for this in the manual. 

I'm up for that. I've been actually working on something like this in https://github.com/porres/Live-Electronic-Music-Tutorial - but it's not icluded yet, will be in the next version!

**Comment by Spacechild1** [comment] 2019-05-11 07:09
> you also cannot set x/y units

the x/y units in [donecanvasdialog( are only relevant when GOP is disabled and they simply correspond to the bounds width/height. you can simply set them with the [bounds( message, e.g.:
```
X units per pixel: 2
Y units per pixel: -4
```
corresponds to `[bounds 0 0 2 4(` (note that y is inverted!)

**Comment by Spacechild1** [comment] 2019-05-11 12:31
@porres I was wrong, `[donecanvasdialog(` also needs a `[map 0, map 1(`, so it's just inferior in any way :-)

But I think what we actually need is something like this:
https://github.com/pure-data/pure-data/pull/627

**Comment by umlaeute** [comment] 2019-06-03 16:06
sidenote: a fix for this is included in the `update/0.50` branch

**Closed** 2019-07-20 20:29 UTC
Labels: bug/fix, pending
