### ISSUE TITLE
regression bug in 0.52-1

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1589] opened 2022-03-23 19:11 UTC
There's a quite annoying new bug introduced in 0.52 where if you open a patch that has a subpatch whose window is opened you cannot see the mouse cursor when editing text in comments, messages and objects in the subpatch. You need to close the window and reopen it.

Now, when dealing with data structures, if the data structure window is opened when you load the patch as in the example I'm sending here, you can't see the cursor when editing text in the parent window and there's nothing you can do...

[bug.zip](https://github.com/pure-data/pure-data/files/8335864/bug.zip)

**Comment by umlaeute** [comment] 2022-03-23 20:32
duplicate of https://github.com/pure-data/pure-data/issues/1395 (and already fixed in current `master`)

**Closed by umlaeute** 2022-03-23 20:32 UTC

**Comment by porres** [comment] 2022-03-26 19:20
really glad this annoying bug is fixed :) thanks!
