### ISSUE TITLE
[print] adds a backlash

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#615] opened 2019-05-02 16:42 UTC
Hi, when using '\' to escape a character like ',' or something, the [print] object actually adds another backlash that's not in there. I think this is a bug, right? Or is there a reason why it has to be this way?

<img width="325" alt="Screen Shot 2019-05-02 at 13 41 01" src="https://user-images.githubusercontent.com/5360142/57091641-0a223980-6ce0-11e9-8deb-17144c98a6e9.png">

**Comment by porres** [comment] 2019-05-03 18:12
hmm, on the other hand, if not treated as a symbol, the backlash is lost instead of adding yet another one.

<img width="335" alt="Screen Shot 2019-05-03 at 15 12 07" src="https://user-images.githubusercontent.com/5360142/57156985-d7e30b80-6db5-11e9-919c-3a18cb5fb75c.png">

**Comment by Spacechild1** [comment] 2019-05-03 18:26
I think this is a bug in `[print]`. backslash handling is not consistent and I think there are already similar bug reports (or was it only on the list)? just compare `[symbol \$(` and `[symbol \\(`. the first one prints the literal $ characters, while the second gives you 4 backslashes although I would only expect 1...

btw, you don't have to escape commas and semicolons in creations arguments for objects other than message boxes: `[symbol ,]` works just as fine (this is done so that objects like [expr] work seemlessly).

**Comment by umlaeute** [comment] 2019-05-09 09:13
i think it's not a bug in `[print]`, but in the tcl/tk-console (or even more likely: the communication protocol between core and GUI)
e.g. compare the output when starting Pd  with `-stderr`

**Comment by umlaeute** [comment] 2019-06-03 16:08
this is fixed with fc68cd87b3b68884d5385d53d162893a6028271a in the PR #647

**Comment by umlaeute** [comment] 2019-07-21 18:38
merged with c037533e2f3515598f17c0a339f54e1258c32c0a

**Closed by umlaeute** 2019-07-21 18:38 UTC
Labels: pending, subject:GUI

**Comment by porres** [comment] 2020-04-16 16:47
thanks, just tested this!
