### ISSUE TITLE
Pd can't expand "~" when writing

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#2220] opened 2024-03-15 16:09 UTC
This affects [soundfiler] and [writesf~]

**Comment by umlaeute** [comment] 2024-03-15 19:13
Duplicate of #2214 (and already forces in devel)

**Comment by porres** [comment] 2024-03-15 20:05
> I've had already fixed both before the ticket was split

ok, didn't realize

**Comment by umlaeute** [comment] 2024-03-15 21:40
no problem, i didn't mention it in my comments (preferred to write code over writing comments :-))

**Closed** 2024-04-07 06:45 UTC
Labels: pending, subject:core, improvement
