### ISSUE TITLE
netsend/netreceive memory leak on Pd 0.47.1 for OS X and Pd 0.46.2 for Raspbian 

### ISSUE THREAD

**Issue by toniarnold** [pure-data/pure-data#190] opened 2017-08-17 11:56 UTC
Although Pd 0.46.2 for Raspbian (Jessie) seems to leak much more memory than Pd 0.47.1 for OS X (Snow Leopard), the problem is easily reproducible with both netsend and netreceive in the stress test patches, no matter whether both ends are running on a single machine or separated: both objects leak on heavy traffic. 

https://github.com/toniarnold/mmba/tree/master/issues/2

For non-local test, adjust the target host name in netreceive.pd, let the pair run for a while and watch memory consumption grow, steadily and fast on Pd 0.46.2 for Raspbian, slower and minimally curvy on Pd 0.47.1 for OS X:

    pd -nogui -noaudio netsend.pd >/dev/null 2>&1
    pd -nogui -noaudio netrecieve.pd >/dev/null 2>&1

The related issue toniarnold/mmba#2 is literally a showstopper for the client/server architecture of my Modular MyStrom Bulb App: When sending LFO signals from Pd (running as a system service) through sockets via an intermediary Python3 server to some IoT WiFi light bulbs, sooner or later the light show respectively the whole Raspberry PI server grinds to a halt.

**Comment by umlaeute** [comment] 2017-08-17 15:01
confirmed for 0.48-0

the problem is that the `socketreceiver` allocated through `[netsend]`s `[connect(` message (e,g, in [s_inter.c:459](https://github.com/pure-data/pure-data/blob/eafd4341fb7554bf352cfd7637fe0c076199c3ec/src/x_net.c#L263-L265)) is never freed.

**Comment by toniarnold** [comment] 2017-08-21 08:50
The stability issue mentioned in toniarnold/mmba#2 after the commit are reproducible with the test patches, even quicker when running the metro at 1 kHz. After a continuous stream interspersed with an occasional `Bad address`, netreceive dies with a memory access error:

    /usr/bin/pd-0.48.0  -nogui -noaudio netreceive.pd
    error: Ignoring invalid font-metrics from GUI!
    disabling real-time priority due to missing pd-watchdog (/usr/lib/pd/bin/pd-watchdog)
    netreceive[0x43ff58]connectpoll[0]: 0x430cc8
    netreceive[0x43ff58]connectpoll[1]: 0x43fe30
    netreceive: 0
    netreceive[0x43ff58]connectpoll[2]: 0x430ce8
    netreceive_notify[0x43ff58] 10
    netreceive[0x43ff58]notify[10]: 0x43fe30
    netreceive[0x43ff58]connectpoll[2]: 0x43fe30
    netreceive: 1
    netreceive: 2
    netreceive[0x43ff58]connectpoll[3]: 0x443cc0
    netreceive_notify[0x43ff58] 11
    netreceive[0x43ff58]notify[11]: 0x430ce8
    netreceive: 3
    .
    .
    .
    netreceive: 120
    netreceive_notify[0x43ff58] 10
    netreceive[0x43ff58]notify[10]: 0x443dd8
    recv: Bad address (14)

    netreceive_notify[0x43ff58] 11
    netreceive[0x43ff58]notify[11]: (nil)
    netreceive[0x43ff58]connectpoll[0]: 0x451098
    netreceive[0x43ff58]connectpoll[1]: 0x443dd8
    netreceive: 121
    .
    .
    .
    netreceive: 228
    netreceive_notify[0x43ff58] 13
    netreceive[0x43ff58]notify[13]: 0x4513a0
    netreceive: 230
    netreceive_notify[0x43ff58] 10
    netreceive[0x43ff58]notify[10]: 0x4513d0
    netreceive_notify[0x43ff58] 11
    netreceive[0x43ff58]notify[11]: (nil)
    netreceive[0x43ff58]connectpoll[0]: 0x4513d0
    netreceive[0x43ff58]connectpoll[1]: 0x443dd8
    netreceive: 231
    netreceive_notify[0x43ff58] 10
    netreceive[0x43ff58]notify[10]: 0x443dd8
    netreceive: 229
    netreceive_notify[0x43ff58] 11
    netreceive[0x43ff58]notify[11]: (nil)
    Speicherzugriffsfehler

**Comment by umlaeute** [comment] 2017-08-21 10:03
this is supposedly fixed in #191, please check

**Comment by toniarnold** [comment] 2017-08-23 07:16
> this is supposedly fixed in #191, please check

Was the fix for the memory access error pushed? Can't see any further changes in `x_net.c` on branch update/0.48.0 after ccad7db22c97de452aefdc960d88d63f4ae289b2 from Aug 17, the memory leak itself might be fixed, but the memory access error crashes remain.

**Comment by umlaeute** [comment] 2017-08-23 07:21
this issue is about "netsend/netreceive memory leak". it's not about memory access problems. if there are any such problems, please open another issue

(and please understand that we cannot follow an unrelated issue tracker like toniarnold/mmba#2 for problems with pure-data)

**Comment by toniarnold** [comment] 2017-08-23 07:37
This is a misunderstanding: My followup is not about an unrelated memory access problem, it is a *new* problem introduced by commit ccad7db22c97de452aefdc960d88d63f4ae289b2 for #190 *itself*. Also, the debug output shown above is created with explicit `post("netreceive[%p]listen: %p", x, x->x_ns.x_receiver);` statements which should probably be removed before merging into master.

**Comment by umlaeute** [comment] 2017-08-23 07:40
in any case, the followup is a new problem, so please open a new issue.

**Closed** 2017-10-01 15:13 UTC
Labels: bug/fix, pending
