### ISSUE TITLE
Browser not showing new externals added with Deken (w32) Pd-0.48.test7

### ISSUE THREAD

**Issue by Lucarda** [pure-data/pure-data#177] opened 2017-08-11 23:02 UTC
Externals added with Deken only show-up on the **Browser's** "externals" sub-folder.
After a restart they show-up in the **Browser's** main column.

Tested on win8.1 & win10.

**Comment by danomatika** [comment] 2017-08-11 23:16
Ok, so the issue is the browser doesn't refresh after using deken?

**Comment by Lucarda** [comment] 2017-08-11 23:26
New path gets added to the prefs but those show up on the main column of the Browser on the next Pd's restart.

**Comment by danomatika** [comment] 2017-08-11 23:49
Fixed with https://github.com/pure-data/pure-data/pull/178/commits/92d28a5092b8fa2642df70735bceb2efde75ef6d#diff-e1a0eae582fc93e43f36d5b646ebf02bR560

**Closed by danomatika** 2017-08-11 23:49 UTC
