### ISSUE TITLE
No pure-data image in jack connection kit

### ISSUE THREAD

**Issue by oscarsantis** [pure-data/pure-data#1369] opened 2021-08-29 20:34 UTC
When I run the compiled version of PD, downloaded from this repository, it does not appear in the Qjackctl audio connections graph. However it is seen in alsa-midi and can be heard. This does not happen with compilation of the latest stable version (0.51-4) available as source code on the Miller Puckette site.
I use Ubuntustudio 20.04, Kernel 5.11
To compile the source code of this repository I used the following configuration:

~~~sh
./configure --enable-jack --enable-fftw --enable-libpd
~~~

**Comment by reduzent** [comment] 2021-08-30 08:10
When you run:

```./configure --enable-jack --enable-fftw --enable-libpd```

do you see that Jack is enabled / output like this:

```
    fftw:                 no
    wish(tcl/tk):         wish
    audio APIs:           PortAudio JACK ALSA OSS 
    midi APIs:            ALSA OSS 
    libpd:                no

```

(Jack should be listed in the audio APIs)

**Comment by umlaeute** [comment] 2021-08-30 08:13
> When I run the compiled version of PD, downloaded from this repository

I don't know of any "compiled versions of Pd" to be "downloaded from this repository".

so please provide some details on how you came to your binary.

**Comment by Spacechild1** [comment] 2021-08-30 10:05
@umlaeute I'm pretty sure "downloaded from this repository" refers to the sources, not binaries. He built Pd from source.

**Comment by reduzent** [comment] 2021-08-30 10:17
I cannot reproduce. When I compile current master (571ad348c ) and use `--enable-jack`, I end up with a binary that connects with JACK just fine and also appears as client QJackCtl.

**Comment by umlaeute** [comment] 2021-08-30 12:40
@Spacechild1 probably (but i wanted to make sure).

i think in this case, the "issue" is, that Pd only registers itself as a jack-client when DSP is turned on.

this was in introduced in 95b614656cd62214d6779014e5173d8af697814b, and while i don't think it was fully intentional, i also think that there's nothing wrong with the current behaviour, so I'm closing this.

**Closed by umlaeute** 2021-08-30 12:40 UTC

**Comment by oscarsantis** [comment] 2021-08-30 13:52
> @Spacechild1 probably (but i wanted to make sure).
> 
> i think in this case, the "issue" is, that Pd only registers itself as a jack-client when DSP is turned on.
> 
> this was in introduced in [95b6146](https://github.com/pure-data/pure-data/commit/95b614656cd62214d6779014e5173d8af697814b), and while i don't think it was fully intentional, i also think that there's nothing wrong with the current behaviour, so I'm closing this.

That's right @Spacechild1, when I turn on DSP Pure Data is visible.
I downloaded sources from here.
Thanks

**Comment by reduzent** [comment] 2021-08-31 06:37
> i think in this case, the "issue" is, that Pd only registers itself as a jack-client when DSP is turned on.

I see. One important detail: It doesn't disappear after turning DSP off. That's good!

**Comment by matthewbrandi** [comment] 2021-08-31 09:54
On 31/08/2021 07:37, Roman Haefeli wrote:
>     i think in this case, the "issue" is, that Pd only registers itself as a jack-client
>     when DSP is turned on.
> 
> I see. One important detail: It doesn't disappear after turning DSP off. That's good!

I don’t think it is /quite/ right to say Pd only registers itself as a JACK client when 
DSP is turned on —— although I have been wrong before and will be again.

I am running Pd 0.51.4 compiled from source (on Linux). I usually start Pd from a bash 
script and hadn’t seen the reported failure to show up in qjackctl, so I started taking 
flags out of the Pd command to see what made the difference. Sure enough, the following 
shows the reported behaviour:

   #!/bin/bash
   /usr/local/bin/pd &

However, either of the following seem to start Pd registered as a JACK client but with DSP 
turned off:

   #!/bin/bash
   /usr/local/bin/pd -jack &

   #!/bin/bash
   /usr/local/bin/pd -jackname somename &

I guess that is what one would expect and certainly what one would want.

Is DSP turned on and off again in the background before the Pd GUI shows up (with DSP box 
unticked), or is turning on DSP just /one/ way to get Pd to show up in JACK?

Apologies if I have gotten hold of the wrong end of the stick … again.

Yours

m
-- 
matthew brandi
