### ISSUE TITLE
Issue creating GUI objects using shortcuts on Mac (Pd Compiled from source)

### ISSUE THREAD

**Issue by mariobuoninfante** [pure-data/pure-data#678] opened 2019-07-11 13:46 UTC
tested on MacOS Sierra and HighSierra - Pd compiled from source (0.49)

STEPS TO REPRO
1. launch Pd
2. create a new patch
3. use shortcut to create a BANG (cmd+shift+b)
4. exit EDIT mode
5. click on the GUI objects

ACTUAL OUTCOME
- no visual feedback. that's because 2 BANG objects have been created, one on top of the other. This doesn't happen if you create the object from the Menu, or typing [bng]
- the same with the other GUI objects

**Comment by fdch** [comment] 2019-07-11 13:59
Can't reproduce on macOS Mojave 10.14.5
tried with my pd compiled from source using Tk 8.6.9
and with (i think @umlaeute 's ) Pd-0.49.1 ("") compiled 11:21:16 Jun  6 2019, using Tk 8.5.19

**Comment by mariobuoninfante** [comment] 2019-07-19 06:43
I'm using Tk 8.5.9

**Comment by mariobuoninfante** [comment] 2019-07-19 06:46
Here's a quick video that shows the issue (there I create the GUI objects via keyboard shortcut)
[Pd_issue_creating_GUI.zip](https://github.com/pure-data/pure-data/files/3409807/Pd_issue_creating_GUI.zip)

**Comment by umlaeute** [comment] 2019-07-23 21:46
i haven't looked at the video, but is the problem solely that whenever you create an object via the shortcuts, the object is created *doubly*? (i seem to remember something like this before)

- do you also get this, when just creating a new object (<kbd>Cmd</kbd>-<kbd>1</kbd>)?

- do you have any GUI-plugins installed? does the problem persist if you uninstall/deactivate *all* of them?

- what's the output of something like:

~~~
pd -d 2 2>&1 | sed -e '/^[[:space:]]*$/d' -e '/ motion /d'
~~~

**Comment by mariobuoninfante** [comment] 2019-07-23 23:46
no issues when using CMD+1.
the output I'm getting is:
pd init /Users/mariobuoninfante 0  8 4 11 9 6 12 12 7 16 14 8 19 21 13 28 33 20 44 17 10 22 19 11 26 24 14 32 29 17 38 43 26 58 65 39 86;

What do you mean with GUI-plugins?

**Comment by umlaeute** [comment] 2019-07-24 07:35
> no issues when using CMD+1.

weird.

> the output I'm getting is:
> pd init /Users/mariobuoninfante 0 8 4 11 9 6 12 12 7 16 14 8 19 21 13 28 33 20 44 17 10 22 19 11 26 24 14 32 29 17 38 43 26 58 65 39 86;

this is what you get during startup.
however, i would like to know what you get when you create one of the problematic GUI objects (e.g. by pressing <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>b</kbd>)

> What do you mean with GUI-plugins?

"externals" for the Pd-GUI (things like: the completion-plugin, the kiosk-plugin, the search-plugin, ...)

**Comment by mariobuoninfante** [comment] 2019-07-24 10:12
ok gotcha.
No external plugins are involved.
that's the output when I just launch Pd, open a new patch and create a bang, then click to 'drop somewhere in the patch' one of the 2 created:

pd init /Users/mariobuoninfante 0  8 4 11 9 6 12 12 7 16 14 8 19 21 13 28 33 20 44 17 10 22 19 11 26 24 14 32 29 17 38 43 26 58 65 39 86;
pd key 1 ?? 0;
pd menunew Untitled-1 /Users/mariobuoninfante/Documents/Pd;
pd key 0 110 0;
.x7fbe59c35150 setbounds 0 22 1 23;
.x7fbe59c35150 setbounds 0 22 450 322;
.x7fbe59c35150 setbounds 0 23 450 323;
.x7fbe59c35150 map 1;
.x7fbe59c35150 key 0 ?? 0;
.x7fbe59c35150 mouse 191.0 106.0 1 0;
.x7fbe59c35150 mouseup 191.0 106.0 1 0;
.x7fbe59c35150 key 1 ?? 1;
.x7fbe59c35150 key 1 ?? 1;
.x7fbe59c35150 bng;
.x7fbe59c35150 bng;
.x7fbe59c35150 key 0 98 1;
.x7fbe59c35150 key 0 ?? 1;
.x7fbe59c35150 key 0 ?? 0;
.x7fbe59c35150 mouse 135.0 121.0 1 0;
.x7fbe59c35150 mouseup 135.0 121.0 1 0;

**Comment by umlaeute** [comment] 2019-07-24 13:41
so you get each key-down event twice.

and you can type normally? i mean, if you create an object with <kbd>Cmd</kbd>+<kbd>1</kbd>, and then start typing the object-name, don't you get repeats?

**Comment by mariobuoninfante** [comment] 2019-07-24 14:31
nope, everything else seems fine

**Comment by mariobuoninfante** [comment] 2019-07-24 14:38
this is what I get when launching Pd opening a new patch and creating an [osc~ 100] connected to a [dac]

pd init /Users/mariobuoninfante 0  8 4 11 9 6 12 12 7 16 14 8 19 21 13 28 33 20 44 17 10 22 19 11 26 24 14 32 29 17 38 43 26 58 65 39 86;
pd key 1 ?? 0;
pd menunew Untitled-1 /Users/mariobuoninfante/Documents/Pd;
.x7fc4974028b0 setbounds 0 22 1 23;
.x7fc4974028b0 setbounds 0 22 450 322;
.x7fc4974028b0 setbounds 0 23 450 323;
.x7fc4974028b0 map 1;
.x7fc4974028b0 key 0 110 0;
.x7fc4974028b0 key 0 ?? 0;
.x7fc4974028b0 key 1 ?? 0;
.x7fc4974028b0 obj 0;
.x7fc4974028b0 key 0 49 0;
.x7fc4974028b0 key 0 ?? 0;
.x7fc4974028b0 key 1 111 0;
.x7fc4974028b0 key 0 111 0;
.x7fc4974028b0 key 1 115 0;
.x7fc4974028b0 key 0 115 0;
.x7fc4974028b0 key 1 99 0;
.x7fc4974028b0 key 0 99 0;
.x7fc4974028b0 key 1 ?? 1;
.x7fc4974028b0 key 1 126 1;
.x7fc4974028b0 key 0 126 1;
.x7fc4974028b0 key 0 ?? 0;
.x7fc4974028b0 key 1 32 0;
.x7fc4974028b0 key 0 32 0;
.x7fc4974028b0 key 1 49 0;
.x7fc4974028b0 key 0 49 0;
.x7fc4974028b0 key 1 48 0;
.x7fc4974028b0 key 0 48 0;
.x7fc4974028b0 key 1 48 0;
.x7fc4974028b0 key 0 48 0;
.x7fc4974028b0 key 1 ?? 0;
.x7fc4974028b0 obj 0;
.x7fc4974028b0 key 0 ?? 0;
.x7fc4974028b0 key 0 49 0;
.x7fc4974028b0 key 1 100 0;
.x7fc4974028b0 key 1 97 0;
.x7fc4974028b0 key 0 100 0;
.x7fc4974028b0 key 0 97 0;
.x7fc4974028b0 key 1 99 0;
.x7fc4974028b0 key 0 99 0;
.x7fc4974028b0 key 1 ?? 1;
.x7fc4974028b0 key 1 126 1;
.x7fc4974028b0 key 0 126 1;
.x7fc4974028b0 key 0 ?? 0;
.x7fc4974028b0 mouse 173.0 99.0 1 0;
.x7fc4974028b0 mouseup 173.0 99.0 1 0;

**Comment by mariobuoninfante** [comment] 2019-07-24 14:38
but no objects have been created twice, and I don't have issues typing as well

**Comment by umlaeute** [comment] 2019-07-25 06:37
while i still have no idea what exactly is going on: what happens i you type a capital letter, e.g. a comment `Hello`?

**Comment by mariobuoninfante** [comment] 2019-07-25 07:46
everything is fine also when I write capital letters.
The only thing I've noticed, is it normal that when I use the compiled version and I press or release SHIFT on the keyboard this appears as:
key 0 ?? 0

while on the MacOS app version is:
key 0 Shift_L 0

**Comment by mariobuoninfante** [comment] 2019-07-25 07:58
it seems like everything that gets SHIFT involved happens twice.
It is true for GUI objects but also if I use the shortcut for SAVE AS, the dialog appears twice.
Just few considerations from what I'm experiencing
1. the issue could be with SHIFT
2. the issue could be with SHIFT and CMD, since that is displayed __key 0 ?? 0__ as well, like SHIFT
3. the issue could be with shortcuts that need more than 2 keys held

**Comment by mariobuoninfante** [comment] 2019-07-25 08:05
Here's the last discovery.
The following is the outcome of:

1. launch Pd
2. create a new patch
3. show Pd console using CMD+R
4. click on the patch to bring it to the front
5. try to create a [bng] using CMD+SHIFT+B

pd init /Users/mariobuoninfante 0  8 4 11 9 6 12 12 7 16 14 8 19 21 13 28 33 20 44 17 10 22 19 11 26 24 14 32 29 17 38 43 26 58 65 39 86;
pd key 1 ?? 0;
pd menunew Untitled-1 /Users/mariobuoninfante/Documents/Pd;
.x7fa091c14050 setbounds 0 22 1 23;
.x7fa091c14050 setbounds 0 22 450 322;
.x7fa091c14050 setbounds 0 23 450 323;
.x7fa091c14050 map 1;
.x7fa091c14050 key 0 110 0;
.x7fa091c14050 key 0 ?? 0;
.x7fa091c14050 key 1 ?? 0;
pd key 0 114 0;
pd key 0 ?? 0;
pd key 1 ?? 1;
pd key 1 ?? 1;
pd key 0 98 1;
pd key 0 ?? 1;
pd key 0 ?? 0;
.x7fa091c14050 mouse 154.0 59.0 1 0;
.x7fa091c14050 mouseup 154.0 59.0 1 0;

Right after using CMD+R, I'm not able to create any object in the patch, doesn't matter what I do in terms of shortcuts, plus the PUT menu is greyed out, I can't select anything.
The only way to snap out of it is to exit and then enter EDIT mode (I've done it using the keyboard shortcut)

**Comment by danomatika** [comment] 2019-08-07 20:34
>I'm using Tk 8.5.9

NO NO NO NO NO -> https://github.com/pure-data/pure-data/blob/master/INSTALL.txt#L260

**Comment by danomatika** [comment] 2019-08-10 23:27
Also, as it says in the readme, unless you install a newer Tcl/Tk two your system build the PD app bundle. Since the default Wish.app used to generate the Pd app bundle has been updated, this means simply calling `make app` after `make`. Do *not* `make install` Pd to you system if you have the default Tk 8.5.9 for now. Hopefully Apple will upgrade this with macOS 10.15...

**Comment by danomatika** [comment] 2019-08-11 01:55
I'm going to close this for now and assume `make app` is working on your system.

**Closed by danomatika** 2019-08-11 01:55 UTC
