### ISSUE TITLE
loadbang in clone is loaded later

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#242] opened 2017-10-31 15:47 UTC
maybe there's no way around it and this is known, but I'm here to point it out and discuss anyway.

<img width="643" alt="screen shot 2017-10-31 at 13 44 31" src="https://user-images.githubusercontent.com/5360142/32233483-a4dc764c-be41-11e7-9451-29215b599155.png">

here you see that the loadbang from an abstraction is "superceeded" by the loadbang from the parent patch. But if the abstraction is loaded inside clone, it is fired later than the parent patch. 

This is problematic if you have an abstraction that loads arguments or default values that need to be superceeded by incomming messages.

I was able to solve this by using [initbang] inside the abstraction instead of [loadbang]. Seems like a solution if nothing else can be done, but this would mean that vanilla really needed something like [initbang]

cheers

**Comment by umlaeute** [comment] 2017-10-31 18:48
no need for `[initbang]`.

simply make sure that whatever should get loadbanged will also get triggered the first time something is received in the *inlet* (filtering out duplicates).

note: i'm not saying that the current behaviour is not a bug; but i don't think it warrants the introduction of `[initbang]` (this is a separate issue)

**Comment by porres** [comment] 2017-10-31 20:24
> simply make sure that whatever should get loadbanged will also get triggered the first time something is received in the inlet (filtering out duplicates).

sorry, I don't undesrtand

**Comment by danomatika** [comment] 2017-12-01 14:24
>>simply make sure that whatever should get loadbanged will also get triggered the first time something is received in the inlet (filtering out duplicates).
>
>sorry, I don't understand

I think he is suggesting to use something like a spigot which bangs the [f $1] on the first message the object receives and then closes afterward, something like:

![screen shot 2017-12-01 at 3 22 13 pm](https://user-images.githubusercontent.com/480637/33486853-b47e4ea4-d6ab-11e7-9416-37d7e2cc3cf8.png)

Also, you could create a control inlet to send the value. I mainly use [clone] this way and without the object arguments.

**Comment by porres** [comment] 2017-12-01 15:36
> I think he is suggesting to use something like a spigot which bangs the [f $1] on the first message the object receives and then closes afterward, something like:

But that would mean changing the whole patch/abstraction. And I don't wanna do that. Say it is from an external library and I don't wanna mess with it. 

And anyway, I'm not looking for hacks or ways around this. I'm already dealing with this my own way... The only point is that I think this is a bug, and this is just a bug report then. 

Now, is there any opposition to the idea this is a bug? 

cheers

**Comment by danomatika** [comment] 2017-12-01 15:38
Wrap it up with a custom abstraction to adapt to a slightly different behavior? How is that a hack?

**Comment by pierreguillot** [comment] 2017-12-02 10:23
@porres 
> Now, is there any opposition to the idea this is a bug?

I wouldn't say it's a bug because there is no ideal behavior for this. If the loadbang of [clone] happens before the loadbang of the parent patch, you can encounter the inverse problem. 

In this case, imagine the abstraction loaded by [clone] sends a message to its outlet, the parent patch will receive this message before it has received the loadbang (and perhaps before it has been well initialized). 

For me the current implementation is more suitable (perhaps because I've never encountered your problem before...)

**Comment by porres** [comment] 2017-12-02 14:01
> I wouldn't say it's a bug because there is no ideal behavior for this.

I don't know about "ideal", what should be the subjective notion of an ideal behaviour is not what I'm discussing. And, ideal or not, there should be expected behaviour. And like it or not, the specified and expected behaviour for Pd has always been that an abstraction will have a loadbang before the loadbang from a parent patch. That's how it is and how it works, as exemplified in the example I gave. And yes, this means it sends a message to its outlet and the parent patch will receive this message before it has received the loadbang, and what's the problem there? As it's always worked like that for Pd? 

> (and perhaps before it has been well initialized).

But "perhaps" how? Your argument is that pehaps that might not be good? well, again, it's already like that and I see no problem, as the abstraction needs to be initialized first, before the parent patch is initialized. Like, for instance, it loads default arguments that will be rewritten via messages from the parent patch. Totally fine. In years of Pd that never got me into trouble, now, on the other hand, if you have values that will overwrite an abstraction but that doesn't happen, that's a problem!

And now, with the new [clone] object, if that abstraction is in a patch that's called via clone, we have a conflicting behaviour, where it won't receive the loadbang first. That unexpected or conflicting behaviour can generate issues that would be solved if it just behaved consistently. That's how and why I came here, facing issues that led me to report a bug.

>  For me the current implementation is more suitable (perhaps because I've never encountered your problem before...)

well, it still exists :)

> Wrap it up with a custom abstraction to adapt to a slightly different behavior? How is that a hack?

I guess the point is wether this different and comflicting behaviour is a bug or not. As I see it as a bug, I consider any workaround that is not fixing this behaviour a hack, because it doesn't involve in fixing the issue and just relies on me dealing with it.

cheers

**Comment by pierreguillot** [comment] 2017-12-02 14:22
> And like it or not, the specified and expected behaviour for Pd has always been that an abstraction will have a loadbang before the loadbang from a parent patch.

I've never noticed sorry (I've always used only one [loadbang] for a whole project). So, yep I vote for a bug :)

**Comment by fdch** [comment] 2017-12-02 19:07
I'm not sure if it is directly related, but in case there is a revision of loadbang/clone: https://github.com/pure-data/pure-data/issues/261

**Comment by danomatika** [comment] 2017-12-02 21:17
Maybe [clone] could have a flag to force loading before the parent ie. "-l".

**Comment by umlaeute** [comment] 2017-12-03 12:07
hmm, i don't see the point of having such a  "-nobug" flag.

the normal behaviour in Pd is, that child canvases fire their `[loadbang]'s before the parent.
`[clone]` should adhere to that as well.

**Comment by porres** [comment] 2017-12-03 19:16
hey, another related issue! https://github.com/pure-data/pure-data/issues/49

**Comment by cuinjune** [comment] 2018-03-26 18:12
Hey, I just realized this problem with Pd-0.48-1 and I hope this could be fixed.

**Comment by Spacechild1** [comment] 2018-03-26 19:32
I have a PR which includes a fix for this: https://github.com/pure-data/pure-data/pull/310

**Comment by umlaeute** [comment] 2018-08-05 21:27
it seems that this has been fixed with 06e4bd4cb6d0c7d5606b8cf3c0f94f8bd947a3a6

**Closed by umlaeute** 2018-08-05 21:27 UTC
Labels: bug/fix
