### ISSUE TITLE
Properties issue

### ISSUE THREAD

**Issue by MrcRmg** [pure-data/pure-data#898] opened 2020-02-22 10:38 UTC
When I open the properties box of a GUI object (it doesn t matter whether of sliders, canvas and so on..) for a second time pd freezes. 
I had never had this problem with Ubuntu 16...any hints?

I am on Ubuntu 18.04 and Pd 0.50

**Comment by MrcRmg** [comment] 2020-02-22 11:04
Update: if press the Alt key, then the properties Box and pd come back to normal.

**Comment by umlaeute** [comment] 2020-02-25 09:34
unable to reproduce.
please provide step-by-step instructions on how to trigger the problem (starting from a fresh patch).

do you have any gui-plugins installed?
how did you install Pd (iirc, bionic comes with Pd-0.48)?

**Comment by MrcRmg** [comment] 2020-02-25 10:34
I have no gui-plugins installed and  compiled Pd (0.50) in Ubuntu 18.04.
Yesterday it happened the same with another program and i fixed it the same way, so I guess it has nothing to do with pd itself but with Ubuntu.
I get this message on PD start-up: 
TCL_LIBRARY="/usr/local/lib/pd/lib/tcl/library" TK_LIBRARY="/usr/local/lib/pd/lib/tk/library"   wish "/usr/local/lib/pd/tcl//pd-gui.tcl" 5400

**Comment by umlaeute** [comment] 2020-02-25 10:38
the printout is perfectly ok.
your step-by-step instructions less so :-)

if you agree that this is an issue with your desktop-manager/..., can we close this?

**Comment by MrcRmg** [comment] 2020-02-25 10:48
ok, thank u!

**Closed** 2020-02-25 10:49 UTC
