### ISSUE TITLE
macOS keyboard shortcut for adding bang

### ISSUE THREAD

**Issue by boonier** [pure-data/pure-data#1289] opened 2021-03-18 15:54 UTC
I was trying to add a bang gui object and the key shortcut didn't work...

Did it recently change from `Command+Shift+B` to `Command+Shift+Alt+B`?

The Put menu still says `Command+Shift+B`

pd-0.51-4
macOS 10.14.6

cheers

**Comment by boonier** [comment] 2021-03-22 16:02
weirdly, this seems to only affect my laptop

iMac is fine with the `Command+Shift+B`

same Pd version, something I changed?

**Comment by umlaeute** [comment] 2021-04-30 06:59
it seems the problem is not reproducible even by the OP.

> same Pd version, something I changed?

hard to tell, without being you  :-)


i'm closing this for now as inactable upon.
if you find more hints, just add them here so we can re-open the ticket.

**Closed by umlaeute** 2021-04-30 06:59 UTC
