### ISSUE TITLE
[text define] cmd+s doesn't save text changes when editing window (and closing the text window won't ask you to save changes)

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1230] opened 2020-11-25 02:02 UTC
here on my mac, [text define] asks you if you want to save changes if you click on the "x" to close the window after you edited it. But if I do "control+w" it doesn't and my changes are lost.

**Comment by Spacechild1** [comment] 2020-11-25 06:56
The issue title was a bit vague and as a non-macOS user it took me a while to figure out what you meant. So the problem is that [text define] won't ask if you want to save changes *if you close the patch*. You might update your issue description as well.

> I guess I could also request that changes get saved when I save the patch, but this also seems important.

Hmmm... I don't think that saving the patch should automatically save [text define]. Showing the dialog when closing the patch should be sufficient.

**Comment by porres** [comment] 2020-11-25 07:52
I  mean the [text define] window

**Comment by Spacechild1** [comment] 2020-11-25 07:55
Ok, then I've accidentally found another bug :-) Will open a new issue

**Comment by Spacechild1** [comment] 2020-11-25 07:56
> I guess I could also request that changes get saved when I save the patch, but this also seems important.

This is irrelevant to the issue at hand. Maybe remove it from the issue description.

**Comment by Spacechild1** [comment] 2020-11-25 08:05
On Windows 7, I definitely get the dialog even when closing the window with Ctrl + W, but I notice that I get the following error messages in the console after closing Pd:

`called Tcl_FindHashEntry on deleted table`

**Comment by Spacechild1** [comment] 2020-11-25 08:43
@danomatika Can you confirm this on macOS?

**Comment by umlaeute** [comment] 2020-11-25 09:51
on Linux, i get a confirmation dialog in any/all of the three cases:
- using the shortcut <kbd>Ctrl</kbd>+<kbd>w</kbd>
- using the shortcut <kbd>Alt</kbd>+<kbd>F4</kbd>
- closing the window via the ✖ icon

**Comment by danomatika** [comment] 2020-11-25 10:11
@porres Which version of macOS and which version of Pd?

On my macOS 10.14 system with both Pd 0.51-3 and Pd 0.50-2, closing with via close button or CMD+W shows the confirmation dialog. I get the same behavior on another system running macOS 10.15 with Pd 0.51-3. I'm not seeing the behavior you describe.

**Comment by danomatika** [comment] 2020-11-25 10:15
...and on the 10.15 system, Pd 0.48-2 and Pd 0.49-1 show the dialog in both cases (close button & CMD+W).

**Comment by porres** [comment] 2020-11-25 15:55
After questioning my own sanity when I tested again and saw that cmd+w did in fact aske me t save changes, I was able to remember the steps I did in order to reproduce the issue which made me lose an hour of work yesterday... sorry for the confusion.

In the editing window I had this habit of hitting "cmd+s" with the intuition that it would save its contents. And If I do that while editing the text window, I don't see anything in the console saying that it saved the patch, so it seems I was saving the contents. Anyway, so, **AFTER** you save with cmd+s, it doesn't matter if you close it via the icon or with the shortcut. It won't ask you if you want to save changes and you'll lose your work :)

**Comment by umlaeute** [comment] 2020-11-25 16:02
@porres i think it would be better to open a new issue, as this one already had gained a bit of traction and i think it's only confusing to change it's topic (as most people obviously understood it; rather than what you intended)

**Comment by Spacechild1** [comment] 2020-11-25 16:02
> Anyway, so, AFTER you save with cmd+s, it doesn't matter if you close it via the icon or with the shortcut. It won't ask you if you want to save changes and you'll lose your work :)

??? If you save the text content with `cmd + s`, why should you get a dialog when closing the text window? And how do you lose your work?

**Comment by danomatika** [comment] 2020-11-25 16:05
Short Answer: Yup. Make sure you click on the window before saving if you are working in another window in the meantime. The little * next to the editor title should be your indicator.

Long Answer:

I see this, but only if the window is not focused. The save action is sent and the menu flashes but the text editor window does not receive it. It is similar to when you cycle windows with CMD+`, you have to first click on the window to send key events to it.

This is a general issue with Tk on macOS since moving to Cocoa via Tk 8.5 and not really a bug the Pd GUI can fix within itself without lots of platform-specific hacks (which we mostly avoid) for now.

A general fix in the core might be to check if the extra window is still in an edit state but I'm sure the it does that already. The problem is probably that is relies on receiving the close event but doesn't get it due to the aforementioned bug.

**Comment by danomatika** [comment] 2020-11-25 16:12
Hmm weird. I saw it happening and now I cannot make it reoccur. I think we needs step by step instructions in how you can reproduce it, ie.:

1. create patch window
2. create `[text define]` object
3. click on `[text define]` object to open editor
4. type text into editor
...

**Comment by porres** [comment] 2020-11-25 21:04
- click to open the sequence;
- in the edit window, delete some lines;
- hit cmd/ctr + S;
- close the window with comd/ctr + W;
- close the patch;
- reopen and see that changes were not saved.

see example
[test.pd.zip](https://github.com/pure-data/pure-data/files/5599257/test.pd.zip)

**Comment by Lucarda** [comment] 2020-11-25 21:50
Bug confirmed on Windows with test patch.

**Comment by umlaeute** [comment] 2022-01-12 15:09
i think this is mainly a problem of bad naming:
- the text-editor of `[text define]` never actually *saves* any data (to disk)
  - when it asks you to "*Save* changes" it really means "*Accept* changes" (so the `[text define]` object *sees* them)
  - when you decline, `[text define]` won't be updated
- changing the text in `[text define]` does not dirty the patch
  - similarily, changing the data in a numberbox does not dirty the patch
- saving the patch (rather than the text-editor window) (after you've accepted the changes!), will store the text on disk.


i think it would be complicated have <kbd>Ctrl</Kbd>+<kbd>S</Kbd> both *accept* the data and *save* the patch - and i'm not sure whether this is what we want in *all* cases anyhow.

probably the best course of action would be to:
- change the wording of the warning (so it doesn't save `save`)
- use a different shortcut for *accepting* the data

**Closed** 2023-02-08 17:02 UTC
Labels: bug/fix, pending, subject:GUI
