### ISSUE TITLE
[example-once] in bng-help is buggy (as in: not reentrant safe)

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#1436] opened 2021-11-07 21:48 UTC
as mentioned in https://github.com/pure-data/pure-data/issues/1097#issuecomment-664497822 the `[bng]`-help contains an example implementation of a simple `[once]`-like patch (for bangs only), and that people should be encouraged to "copy and paste" it.

unfortunately, I think the implementation is a bad example of how to do `[once]`, as it is not re-entrant safe: if you feed back the output of the object to its inlet, it will loop "forever" (until the stack depth is exhausted).

please fix this.

(ping @porres as you're the one most likely to tackle such things)

**Comment by abreubacelar** [comment] 2021-11-08 13:18
sorry, i don't know how to do a pr, but a solution could be something simple like this?
[del 0] forces the [t b b] to bang the two outlets, making the patch re-entrant

![Captura de tela de 2021-11-08 10-16-56](https://user-images.githubusercontent.com/16086370/140748625-30f22e05-0747-450b-9706-7b4c980d4248.png)

**Comment by Spacechild1** [comment] 2021-11-08 13:23
@abreubacelar This indeed makes the patch reentrant, but the problem is that the output is always delayed. So this is not a solution.

**Comment by abreubacelar** [comment] 2021-11-08 13:23
actually, thinking further, this would make once break any trigger tree outside of it, creating even buggier patches... 

a more cleaner solution... sorry for the noise with a wrong answer...

![Captura de tela de 2021-11-08 10-22-56](https://user-images.githubusercontent.com/16086370/140749505-1b7a5fd8-c346-46ac-a137-bb9e9ea18817.png)

**Comment by Spacechild1** [comment] 2021-11-08 13:25
@abreubacelar this is the right solution :-)

**Comment by porres** [comment] 2021-11-08 14:43
doing it

**Comment by porres** [comment] 2021-11-17 19:18
hi, we can close this as my documentation branch got merged and included this

**Closed** 2021-11-17 19:21 UTC
Labels: documentation, improvement
