### ISSUE TITLE
more than one [jmmmp/jp.preset] object hangs pd

### ISSUE THREAD

**Issue by sebshader** [pure-data/pure-data#1041] opened 2020-05-29 01:08 UTC
This seems to be a different bug than #850 , in this case trying to create a second jp.preset causes the "pd" process to go up to 100% cpu (no new windows can be opened etc.) and it must be force-quit.. most likely something having to do with data-structures
tested on OSX 10.14, pd 0.51.0test1

**Comment by jmmmp** [comment] 2020-05-30 11:01
The problem doesn't happen when msgfile is replaced with textfile, so it seems that it's again an incompatibility with zexy and pd.
windows 10, pd 0.51.0test1

**Comment by umlaeute** [comment] 2020-05-30 11:33
which (in)compatibility between zexy and Pd?

also, i'm closing this bug, as it is not a bug in Pd but in jmmmp (which might in turn be triggered by a bug in zexy; but that's yet another topic)

**Closed by umlaeute** 2020-05-30 11:33 UTC

**Comment by jmmmp** [comment] 2020-05-30 12:20
the bug happens when 2 different text files are opened in 2 different [msgfile]s at loadbang. This doesn't happen with [textfile]. I just created a new patch to test this, so it's not a problem of jmmmp (which is 100% abstractions).

Also [jp.preset] exists for several years, and only recently this start to happen. [jp.preset] didn't change during all these years, so the bug has nothing to do with jmmmp. But I'm changing it now to remove msgfile from it, so it's not my problem anymore.

**Comment by jmmmp** [comment] 2020-05-30 12:38
the bug happens when [msgfile] cr-reads a text file without an empty line (or a cr) at the end. This doesn't happen with [textfile] or [text]. I just created a new patch to test this, so it's not a problem of jmmmp (which is 100% abstractions).

Also [jp.preset] exists for several years, and only recently this start to happen. [jp.preset] didn't change during all these years, so the bug has nothing to do with jmmmp. But I'm changing it now to remove msgfile from it, so it's not my problem anymore. case closed, anyway.

**Comment by umlaeute** [comment] 2020-05-30 12:50
please note that this is not the issue-tracker of zexy, but of Pd.

if you think you found a bug in zexy, discuss it [over there](https://git.iem.at/pd/zexy).
