### ISSUE TITLE
issue saving patches that contain the word "Untitled"

### ISSUE THREAD

**Issue by mariobuoninfante** [pure-data/pure-data#762] opened 2019-09-30 18:45 UTC
MacOS High Sierra 10.13.1 - Pd 0.50.0

**STEPS TO REPRO**
1. launch Pd
2. create a new patch
3. save it some where on your machine using the default name "Untitled.pd"
4. close the patch
5. re-open the patch
6. press CMD+S to save

**ACTUAL OUTCOME**
- when pressing CMD+S, 'save as' dialog appears - it is not possible to just save the patch
- this seems to happen with all the patches that start with the word 'Untitled' (ie Untitled.pd, Untitled_test.pd, Untitled test.pd, etc.)

**Comment by umlaeute** [comment] 2019-10-01 14:28
duplicate of https://github.com/pure-data/pure-data/issues/156

**Closed by umlaeute** 2019-10-01 14:28 UTC
