### ISSUE TITLE
Please fix the newline-in-comments thing

### ISSUE THREAD

**Issue by php4fan** [pure-data/pure-data#1925] opened 2023-03-18 22:44 UTC
I haven't used Pure Data in the last 10 years or more (I had been using it pretty heavily in the previous 10) and now that I try it again, I can't believe this issue still exists.

I'm pretty sure it's super well known:

To reproduce:

1. create a comment
2. write several lines in it, using the Enter key
3. save the patch, close
4. reopen the patch.

Expected:
Either newlines are not allowed in comments (for which I don't remember a good reason existing, and I can't think of one now). In this case, emit a warning *when I attempt* to create a comment with newlines (or don't let me type them in the first place), and don't allow me to create a comment with them.
Or newlines are allowed. In which case they should be saved correctly, and they should still be there when I open the patch after saving and closing it.

Observed:
Allows me to create comments with newlines in them. I may create a huge patch with thousands of comment boxes with beautifully crafted texts containing hundreds of newlines. After I save, close, and reopen the patch, all my the newlines in my comments will be gone, my patch will be unreadable, and I will have wasted hours of work.

Obviously that didn't happen to me. I went to create a multi-line comment, and at some point, instinctively, without thinking, I created multiple comments, one per line, each one below the previous one, which is something that evidently I got accustomed to do 10+ years ago when I used Pd extensively. So suddenly I remembered, and tried, and boom: yep, the issue exists and is still there.

**Comment by porres** [comment] 2023-03-18 23:27
Note that even though newlines are not supported, as the current help file of comments show, you can use semicolons to break lines and I believe this has been there since the beginning of times. It's certainly in the last version of Pd-Extended (already more than a decade old) and its help file also had this information.

I wouldn't call this an "issue" of "bug" to be fixed (I would definitely not call it a "thing"). Instead I'd call for a feature request to support 'newlines' as well as semicolons. By the way, I don't see a formal feature request for newlines support or a Pull Request just sitting there for someone to say "I can't believe this hasn't happened yet".

Anyway, I guess most of us just got used to doing so when needed and didn't think of it as a major annoyance in order to file a feature request or work on a PR.

**Comment by php4fan** [comment] 2023-03-18 23:47
> I wouldn't call this an "issue" of "bug" to be fixed

That a workaround exists that people are willing to live with, doesn't make it any less of a bug. It's wrong and unjustifiable behavior. Unless you want to make a distinction between a bug and a design flaw, in which case it may be a design flaw. To me that's a pointless distinction (it's only useful if it changes who needs to fix it). Either way it's something objectively wrong that needs fixing. It's not subject to personal taste, it doesn't have pros and cons.

I'm talking about the the fact that you can create the comment with the newlines, you SEE the newlines, and you don't know that they are going to be lost until you close. If you don't want to support newlines without a semicolon, fine, *that* you can argue is a feature request. But then the newlines should be removed the moment the comment is created (or better yet, be discarded as you type, because if you write a huge comment with many lines you are going to be p**sed, although less than if you write dozens of them).

**Comment by Spacechild1** [comment] 2023-03-19 00:30
@php4fan Don't worry, you're not the only one who is annoyed by the behavior of the "comment" object. The underlying reason is that comment text is parsed as a Pd message, so newlines and other non-significant whitespace is removed and the semicolon gets special treatment. This is a simple and elegant solution from a technical point of view, but it is not best solution UX wise...

Anyway, this is basically duplicate of https://github.com/pure-data/pure-data/issues/1291.

**Comment by porres** [comment] 2023-03-19 00:42
> I'm not talking about the fact that newlines (without semicolons) are not supported to begin with. 

You did talk about it though, as one of the options

> That part is a choice and changing that would be a feature request.

cool, then we agree.

Note I don't mean to diminish the issue by saying it's a feature request and sorry, but it is and was unclear what you really want. I think that supporting new lines in comments would be the best way to go. I know I have manifested this wish occasionally, but not strongly enough to open a formal feature request for it (hence, I'm not opposing). I am also the author of a tutorial with about 500 examples with lots of text and have lived ok with this restriction. I don't even use ";"... It'd be in my priority list to allow text justification, adjustable size, weight and color to be honest, but I'm trying to solve this with an external.

**Comment by php4fan** [comment] 2023-03-19 11:17
> You did talk about it though, as one of the options

Yes, what I meant was: when I say this is a bug and not a feature request, I'm talking about the part where the behavior is inconsistent.

> but it is and was unclear what you really want

All I "want" is to not have inconsistent behavior. Starting from there, there are several options and I don't care which one you choose.

> I think that supporting new lines in comments would be the best way to go. 

Sure, that would be more desirable.
But the bare minimum is that you don't allow the user to create an object (in this case a comment) that has invalid content, and  visualize it in a manner that would never be possible with valid content, and only stays that way during the current session, until you reload the patch.

> The underlying reason is that comment text is parsed as a Pd message, so newlines and other non-significant whitespace is removed and the semicolon gets special treatment.

Ok so the text is parsed, and the parsed version is saved, right? Then the parsed version of the text, not the raw version, should be used to create the object on-screen.
That should be pretty trivial. If it's not, then the "simple and elegant" solution is not that elegant, even from a "technical" standpoint.

That still wouldn't be perfect UX-wise, because the user would still be allowed to waste their time and effort crafting _one_  beautiful multi-line comment just to see it destroyed the moment it is "committed" (i.e. when they click outside of the box and the comment is created), but that's way, way better than being encouraged to create _a hundred_ more and see them destroyed at the next reload.

**Comment by porres** [comment] 2023-03-19 13:58
> Then the parsed version of the text, not the raw version, should be used to create the object on-screen.

The thing is that the object has been created already... same is true for message boxes by the way. Only objects are created after you type in, so that happens. Objects also get recreated if you edit them so one thing could be to recreate message/comments as well, but it doesn't seem like a good idea.

**Comment by php4fan** [comment] 2023-03-19 14:39
> The thing is that the object has been created already... 

But after you type, the text content is changed. So why can't it be set to the parsed version (which is the one that gets stored and saved) instead of the raw version?

**Comment by danomatika** [comment] 2023-06-20 20:32
> Anyway, this is basically duplicate of #1291.

Closing this as it is a duplicate. Please move discussion there and.or to any related PRs.

**Closed by danomatika** 2023-06-20 20:32 UTC
