### ISSUE TITLE
Confusion between objects while resizing them

### ISSUE THREAD

**Issue by pierreguillot** [pure-data/pure-data#82] opened 2017-07-03 07:50 UTC
On MacOs with Pd 0.47.1

When I try to resize an object close to another one (but doesn't overlaps it visually), there is a confusion between the objects about which one must be resized. 
I think this happens when one is above another, when you want to resize the one at the bottom this is the one at the top that is resized. 
I guess the good object to select can be found easily because it is selected anyway - even if the wrong object is resized.
See the example with comments:

![giphy](https://user-images.githubusercontent.com/1409918/27783001-d2d07704-5fd4-11e7-9e45-00a6fe446427.gif)

**Comment by danomatika** [comment] 2017-07-09 13:10
Looks like even though the comments seems to be separate, there is a slight overlap and the first one receives the change probably because it's earlier in the graph order.

**Comment by pierreguillot** [comment] 2017-07-10 08:00
I tried again and you're right it's slight but there is an overlap ! Nevertheless, for me it's still a strange behavior because I really expect the 2nd comment to be resized. And it seems that the current width of the objects is not considered by the resizing operation. Here another example if it helps...
![giphy](https://user-images.githubusercontent.com/1409918/28007962-d0022a82-6555-11e7-9df2-1dbb7ff0633f.gif)

**Comment by pierreguillot** [comment] 2017-07-11 10:44
And what about resizing several objects depending on the selection (like Max)? 
![ezgif-3-573ab5a01e](https://user-images.githubusercontent.com/1409918/28064846-678c3a2e-6636-11e7-98a7-c72e77bda3e5.gif)
Here my [branch](https://github.com/pierreguillot/pure-data/tree/dev/obj-multi-resize) (I can create a PR if you want it)

**Comment by Ant1r** [comment] 2017-07-11 15:15
> I can create a PR if you want it

I'd say : please do it :-)

**Comment by Spacechild1** [comment] 2020-04-18 23:11
the issue at hand has been fixed with #99

**Closed by Spacechild1** 2020-04-18 23:11 UTC
Labels: bug/fix

**Comment by pierreguillot** [comment] 2020-04-19 10:24
In fact, the issue is not fixed. I will create another MR to fix it ASAP. If it's ok for you, please reopen the issue.

**Comment by Spacechild1** [comment] 2020-04-19 10:25
Are you sure? I've actually tried and couldn't reproduce the problem, so I assumed it has been fixed already. Can you double check?

**Comment by pierreguillot** [comment] 2020-04-19 10:38
You're right. Sorry, I get confused with the #254 I think.
