### ISSUE TITLE
fails to build on OpenBSD

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#1598] opened 2022-03-28 09:23 UTC
- build of utilities fails with unknown `FD_SET` (and friends)

~~~console
cc -DPACKAGE_NAME=\"pd\" -DPACKAGE_TARNAME=\"pd\" -DPACKAGE_VERSION=\"0.52.2\" -DPACKAGE_STRING=\"pd\ 0.52.2\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"pd\" -DVERSION=\"0.52.2\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_FCNTL_H=1 -DHAVE_LIMITS_H=1 -DHAVE_NETDB_H=1 -DHAVE_NETINET_IN_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_IOCTL_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SOCKET_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_ALLOCA=1 -DHAVE_FORK=1 -DHAVE_VFORK=1 -DHAVE_WORKING_VFORK=1 -DHAVE_WORKING_FORK=1 -DHAVE_MALLOC=1 -DHAVE_REALLOC=1 -DRETSIGTYPE=void -DHAVE_DUP2=1 -DHAVE_GETCWD=1 -DHAVE_GETHOSTBYNAME=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MEMMOVE=1 -DHAVE_MEMSET=1 -DHAVE_REGCOMP=1 -DHAVE_SELECT=1 -DHAVE_SOCKET=1 -DHAVE_STRCHR=1 -DHAVE_STRERROR=1 -DHAVE_STRRCHR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -I.  -DNDEBUG    -I/usr/local/include -DSTUPID_SORT -ffast-math -funroll-loops -fomit-frame-pointer -O3  -g -O2 -MT pdreceive-u_pdreceive.o -MD -MP -MF .deps/pdreceive-u_pdreceive.Tpo -c -o pdreceive-u_pdreceive.o `test -f 'u_pdreceive.c' || echo './'`u_pdreceive.c
u_pdreceive.c:366:5: error: use of undeclared identifier 'fd_set'
    fd_set readset, writeset, exceptset;
    ^
u_pdreceive.c:367:5: warning: implicit declaration of function 'FD_ZERO' is invalid in C99 [-Wimplicit-function-declaration]
    FD_ZERO(&writeset);
    ^
u_pdreceive.c:367:14: error: use of undeclared identifier 'writeset'; did you mean 'writev'?
    FD_ZERO(&writeset);
             ^~~~~~~~
             writev
/usr/include/sys/uio.h:94:9: note: 'writev' declared here
ssize_t writev(int, const struct iovec *, int);
        ^
u_pdreceive.c:368:14: error: use of undeclared identifier 'readset'
    FD_ZERO(&readset);
             ^
u_pdreceive.c:369:14: error: use of undeclared identifier 'exceptset'
    FD_ZERO(&exceptset);
             ^
u_pdreceive.c:371:5: warning: implicit declaration of function 'FD_SET' is invalid in C99 [-Wimplicit-function-declaration]
    FD_SET(sockfd, &readset);
    ^
u_pdreceive.c:371:21: error: use of undeclared identifier 'readset'
    FD_SET(sockfd, &readset);
                    ^
u_pdreceive.c:375:33: error: use of undeclared identifier 'readset'
            FD_SET(fp->fdp_fd, &readset);
                                ^
u_pdreceive.c:377:9: warning: implicit declaration of function 'select' is invalid in C99 [-Wimplicit-function-declaration]
    if (select(maxfd+1, &readset, &writeset, &exceptset, 0) < 0)
        ^
u_pdreceive.c:377:26: error: use of undeclared identifier 'readset'
    if (select(maxfd+1, &readset, &writeset, &exceptset, 0) < 0)
                         ^
u_pdreceive.c:377:36: error: use of undeclared identifier 'writeset'
    if (select(maxfd+1, &readset, &writeset, &exceptset, 0) < 0)
                                   ^
u_pdreceive.c:377:47: error: use of undeclared identifier 'exceptset'
    if (select(maxfd+1, &readset, &writeset, &exceptset, 0) < 0)
                                              ^
u_pdreceive.c:385:17: warning: implicit declaration of function 'FD_ISSET' is invalid in C99 [-Wimplicit-function-declaration]
            if (FD_ISSET(fdpoll[i].fdp_fd, &readset))
                ^
u_pdreceive.c:385:45: error: use of undeclared identifier 'readset'
            if (FD_ISSET(fdpoll[i].fdp_fd, &readset))
                                            ^
u_pdreceive.c:387:31: error: use of undeclared identifier 'readset'
        if (FD_ISSET(sockfd, &readset))
                              ^
u_pdreceive.c:392:13: warning: implicit declaration of function 'FD_ISSET' is invalid in C99 [-Wimplicit-function-declaration]
        if (FD_ISSET(sockfd, &readset))
            ^
u_pdreceive.c:392:31: error: use of undeclared identifier 'readset'
        if (FD_ISSET(sockfd, &readset))
                              ^
5 warnings and 12 errors generated.
*** Error 1 in /home/vagrant/pure-data/src (Makefile:3549 'pdreceive-u_pdreceive.o')
~~~

also, it seems that OpenBSD does not provide `qsort_r`, so we should automatically define `STUPID_SORT` on that platform (even better: detect whether `qsort_r` is available, and define `STUPID_SORT` if it is not)

**Comment by umlaeute** [comment] 2022-03-28 09:24
for the `FD_SET` problem, it is enough to add `#include <sys/select.h>`

**Comment by danomatika** [comment] 2022-03-29 00:34
Is this a duplicate of #1596?

**Closed** 2023-06-04 14:19 UTC
Labels: bug/fix
