### ISSUE TITLE
Canvasses do not open if Pd-console is invisible (but pdwindow is not)

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#215] opened 2017-08-29 18:08 UTC
In Pd 0.48-0, when the Pd main window is made small enough, so that no white area is visible anymore, no canvasses can be opened, neither through menu "File" -> "New", nor by clicking on a subpatch or sending `vis 1` to a canvas. It seems as if the internal messages are blocked as long as the Pd main window is small. When increasing the Pd main window, so that some white area becomes visible, all windows suddenly appear.

This [Screencast](http://romanhaefeli.net/ramsch/pd_window_bug.mkv) illustrates the problem.

**Comment by reduzent** [comment] 2017-08-30 08:23
I should have been more precise. Above behavior is exhibited on Ubuntu 16.04 with Pd 0.48.0. I cannot reproduce this with the same version of Pd on macOS  (10.11) or Windows (Windows 10).

**Comment by reduzent** [comment] 2017-08-30 08:40
Maybe this is related: On Windows, I found another weird behavior. The menu item "File" -> "New" does not work until I toggle DSP. The same menu works when accessed from non-main windows. 

Attached [screencast](http://romanhaefeli.net/ramsch/pd_window_bug_windows.mkv) illustrates the problem.

**Comment by umlaeute** [comment] 2017-08-30 14:48
the problem is [pdwindow.tcl:448](https://github.com/pure-data/pure-data/blob/master/tcl/pdwindow.tcl#L448)

**Comment by umlaeute** [comment] 2017-09-28 17:58
f7dc020 is supposed to fix this

(the issue will be automatically closed if the commit gets accepted)

**Comment by reduzent** [comment] 2017-09-28 19:20
Thanks, IOhannes. It works for me.

(I leave it open, then)

**Comment by umlaeute** [comment] 2017-10-01 16:16
hmm, miller  merged in the `update/0.48.0` branch about the same time as a added the fix to the branch, so the fix for this issue has not been merged (accidentally, i assume).

@millerpuckette: please also include the f7dc020420b55764b4d1962d0a46dfe693cb144d in the upcoming `0.48-1` release, either by re-merging (currently there's only this single pending commit) or by cherry-picking it.

**Comment by millerpuckette** [comment] 2017-10-01 16:44
Ok should be re-merged now.

**Closed** 2017-10-01 16:43 UTC
Labels: bug/fix
