### ISSUE TITLE
atom boxes are loosing inlets/outlets

### ISSUE THREAD

**Issue by 60-hz** [pure-data/pure-data#2154] opened 2023-12-01 07:28 UTC
atom boxes GUI object are loosing their inlet/outlet when specify a send and receive name in the property panel.
Can break patches and is inconsistent with other GUI (tgl, bang, hslider...)

MacOS Sonoma 14
pd-0.54-1

**Comment by umlaeute** [comment] 2023-12-01 09:38
duplicate of https://github.com/pure-data/pure-data/issues/1005

**Closed by umlaeute** 2023-12-01 09:38 UTC
Labels: duplicate

**Comment by porres** [comment] 2023-12-01 18:24
more like a dupe of https://github.com/pure-data/pure-data/issues/1344
