### ISSUE TITLE
with dpi144, fontsize 8 is bigger than 10 - Linux

### ISSUE THREAD

**Issue by mxa** [pure-data/pure-data#1285] opened 2021-03-07 14:00 UTC
![font_weirdness](https://user-images.githubusercontent.com/1220707/110242309-ca6cae80-7f55-11eb-9681-abb073a20a2f.gif)

**Comment by mxa** [comment] 2021-03-07 16:01
Trying out zooming (ctl+, ctl-)
![font_weirdness2](https://user-images.githubusercontent.com/1220707/110246153-c09f7700-7f66-11eb-8bc7-bd7eb9d76b7f.gif)

**Comment by umlaeute** [comment] 2021-03-07 19:45
unable to reproduce (using the Debian package of Pd-0.51-4

**Comment by mxa** [comment] 2021-03-07 19:56
I have the fonts system wide set to 144 dpi because otherwise everything is super tiny on the 4k screen. Is that the issue?
However, why aren't the IEMGUI labels changing the size and why is 8>10?

**Comment by umlaeute** [comment] 2021-03-07 22:37
1. well on my system it doesn't matter if I use Pd as packaged in Debian or current git.
2. i dunno. i use the default of 96dpi. could you try with the default settings (i figure you see enough to be able to press the font-size buttons and see there effects)
3. the iemguis are special and don't follow the normal Pd font standards (e.g .you can specify which font you want to use, and there are many more possibilities to set the size,... this is all possible because iemguis just do their own font stuff (this might be considered an inconsistency bug - but it's unlikely to change without breaking everything)
4. 8 is not greater than10

**Comment by umlaeute** [comment] 2021-04-30 07:21
i tried to set my display to 144dpi (see the terminal window), but I still cannot reproduce this.

https://user-images.githubusercontent.com/214034/116661683-26234900-a995-11eb-8cd7-0727979b94dc.mp4


can we close this?

**Comment by mxa** [comment] 2021-04-30 08:31
> i tried to set my display to 144dpi (see the terminal window), but I still cannot reproduce this.
> fonts.mp4

You set your screen resolution to 144 dpi, I wrote that I set my font to 144 dpi. It's a different thing.

![image](https://user-images.githubusercontent.com/1220707/116669753-3c360700-a99f-11eb-8474-cd3fddaa838e.png)

**Comment by umlaeute** [comment] 2021-04-30 08:59
ah i see. i obviously missed that.
i can confirm the issue then. (i'm not sure whether it's a Pd thing thought)

**Closed** 2021-07-12 22:12 UTC
Labels: bug/fix, pending, subject:GUI
