### ISSUE TITLE
cursor pointer update when entering edit mode with command-e

### ISSUE THREAD

**Issue by sevdh** [pure-data/pure-data#1197] opened 2020-10-28 11:06 UTC
When I'm not in edit mode and press command-e to enter edit mode the cursor pointer doesn't switch to the edit icon until I move the cursor. I think it would be nice and helpful to see the cursor icon change immediately.
Btw. the cursor pointer does change icon immediately when I leave edit mode using command-e. I'm suggesting the same behavior for entering edit mode.

I'm running pd0.51-3test4 on mac os x.

**Comment by umlaeute** [comment] 2020-10-28 11:50
thanks for reporting.

this is a known bug on macOS (only).

i'm closing this as a duplicate of #267

**Closed by umlaeute** 2020-10-28 11:50 UTC
