### ISSUE TITLE
Fail to start pd 0.49-0 on Raspberry Pi zero W

### ISSUE THREAD

**Issue by emviveros** [pure-data/pure-data#584] opened 2019-04-16 17:48 UTC
Hello I'm tried start pd in Raspbian stretch in a Raspberry Pi zero W model without success. 

I'm using a self compiled pd 0.49-0 (source downloaded from Miller's site) and tried to with pd from raspbian repository to with the same error:

```
priority 8 scheduling failed.
Pd: signal 4
pdsend errorname >>error writing "sock22adc20": broken pipe<<
```
In Raspberry pi 3B I was capable to run Pd without problems... pdsend error only occurs when I run it in Raspberry Pi zero model.

Some advice?

**Comment by umlaeute** [comment] 2019-04-22 19:43
do you have a GUI (X11,...)?
if not, start Pd with `-nogui`?

**Comment by emviveros** [comment] 2019-04-26 12:09
`pd -nogui ` return here:

```
priority 6 scheduling failed; running at normal priority
Pd: signal 4 
priority 8 scheduling failed
Instrução ilegal 
```

**Comment by umlaeute** [comment] 2019-04-29 08:24
you probably need to get a backtrace of the crash: see https://wiki.debian.org/HowToGetABacktrace for basic information about this. (and don't forget to pass `-nrt` to the Pd-startup flags before running through *gdb*).

Did you pass any special flags to the build process?
could you post the build logs (either the entire log, zipped/compressed; or "almost-duplicate" lines removed (during compilation, where the only difference are input/output filenames; only one of these lines is needed))

**Comment by umlaeute** [comment] 2019-04-29 08:25
and did you try the Debian packages for Pd-0.49?

**Comment by emviveros** [comment] 2019-04-29 15:05
First, thanks for help!! :)

> and did you try the Debian packages for Pd-0.49?

No. (before you talk)
(Now) yes.

I tried it from debian backports. To install Pd 0.49 from backports I did:
```
$ sudo apt install dirmngr
$ gpg --keyserver hkp://pgpkeys.mit.edu:80 --recv-key 8B48AD6246925553
$ gpg -a --export 8B48AD6246925553 | sudo apt-key add -
$ gpg --keyserver hkp://pgpkeys.mit.edu:80 --recv-key 7638D0442B90D010
$ gpg -a --export 7638D0442B90D010 | sudo apt-key add -
$ echo "deb http://ftp.debian.org/debian stretch-backports main" | sudo tee /etc/apt/sources.list.d/backports.list
$ sudo apt update
$ sudo apt-get -t stretch-backports install puredata
```
When i tried to run pd in terminal it returns:
```
Instrução ilegal
```
Ilegal instruction.

**Comment by umlaeute** [comment] 2019-05-08 15:18
so i've bought an `Raspberry Pi zero W` and it works.

### using the stock Debian package (0.47.1-3)
works

### backports (Pd-0.49.0-3)
as mentioned [above](https://github.com/pure-data/pure-data/issues/584#issuecomment-490458840), you cannot use [backports.debian.org](https://backports.debian.org/), because it requires a newer CPU than the RPi-zero provides.

### self-compiled Debian package

~~~bash
sudo sed -i -e 's/^# *deb-src/deb-src/' /etc/apt/sources.list /etc/apt/sources.list.d/*
sudo apt-get build-dep puredata
dget http://deb.debian.org/debian/pool/main/p/puredata/puredata_0.49.0-3.dsc
cd puredata-0.49.0
dpkg-buildpackage -d
~~~

After that you should have some `.deb` files in the `..` directory, which you can install with `dpkg -i` (you'll need to install most of them, except for the *-dbgsym* packages).

Unfortunately the build-process failed to create packages for me (most likely because a newer `debhelper` version is required to successfully build). However, the binaries were usable.

### self-compiled binaries

this is pretty much your workflow:

~~~bash
sudo apt install build-essential autoconf automake libtool gettext libasound2-dev libjack-jackd2-dev libfftw3-dev tk
wget http://msp.ucsd.edu/Software/pd-0.49-0.src.tar.gz
tar xvf pd-0.49-0.src.tar.gz
cd pd-0.49-0

./autogen.sh
./configure --enable-jack --enable-fftw
make

src/pd -nrt
~~~

## conclusion


The error you get (`Illegal instruction`) hints, that you are using a binary that was compiled for a (slightly) different architecture, e.g. `armv7`.

This could happen mostly because:
- the binaries were compiled on a Raspberry Pi 2 (or 3)
- the binaries were cross-compiled

If this is not the case, you might have configured Pd to load some external at startup. If the external has been compiled for `armv7`, you might get a crash when running on `armv6`.

Anyhow: Since everything seems to work, I'm closing this issue as *unable to reproduce*.

**Closed by umlaeute** 2019-05-08 15:18 UTC

**Comment by emviveros** [comment] 2019-05-08 15:36
I tried to run pd with gdb and I have some error message with something correlated to Cyclone lib... But after I disabled  cyclone startup lib pd runs like a charm in RPi zero. So are no problem to run or compile pure data in Raspberry Pi zero. My only problem are cyclone library which result in Ilegal instruction message.

Thanks for all and sorry for noise..  If anyone wants any more information or test of Pd in RPi zero just ask that I am at disposal.

**Comment by porres** [comment] 2019-05-08 15:54
@emviveros , you can try and compile cyclone for armv6 ;) should be easy!

**Comment by umlaeute** [comment] 2019-05-08 17:14
@porres probably cyclone should be compiled for armv6 instead of armv7.
i don't know the performance impact (so you should do some benchmarking), but at least the raspbian folks think it is small enough so they only offer armv6 binaries (but then: they mostly don't deal with signal processing)

**Comment by emviveros** [comment] 2019-05-09 16:17
> @emviveros , you can try and compile cyclone for armv6 ;) should be easy!

Yep @porres !!! I will see that this week..!

**Comment by porres** [comment] 2019-05-09 16:20
If you have a regular raspberry pi, you can then use both binaries and perform some tests, I'll help you :) - i dont have it and can't test it
