### ISSUE TITLE
packed floats to select object changes the select value

### ISSUE THREAD

**Issue by ma4u** [pure-data/pure-data#1146] opened 2020-09-20 12:41 UTC
undocumented behaviour of the select object in pd
if you send 2 packed floats to [sel $1], the second one actually changes the select value! 

I can't think of a single instance in which anyone would actually rely on the sel object working this way.

**Comment by sebshader** [comment] 2020-09-20 14:43
it is documented because lists are distributed across inlets in the absence of a "list" method for the 1st inlet, though it's not widely realized it seems.
referencing section 2.6.4 of the Documentation:
http://msp.ucsd.edu/Pd_documentation/x2.htm#s3.3
>Unless they arrange otherwise by defining a "list" method, objects respond to the "list" message by distributing the >arguments of the message to their inlets, except for the first argument which is passed as a "float" or "symbol" message >to the object proper.

**Comment by porres** [comment] 2020-09-20 14:52
> I can't think of a single instance in which anyone would actually rely on the sel object working this way.

The object is clear that it needs to receive either floats or symbols, it does not have a list mode so you can't assume that a list will work or behave in some way, other than this which is a common behavior.

> it is documented because lists are distributed across inlets in the absence of a "list" method for the 1st inlet, though it's not widely realized it seems.

I also document this in my tutorial, so I second that this is documented. And I'm not sure we should change the help file of every object that does not have a list method and more than one inlet (maybe?).

**Comment by Spacechild1** [comment] 2020-09-21 10:07
> And I'm not sure we should change the help file of every object that does not have a list method and more than one inlet (maybe?).

probably not ;-) In fact, the default behavior is clearly documented in `2. control.examples/04.messages.pd`:

> If you send a list to an object with more than one inlet, the items in the list are spread out over the inlets, as seen in the 5+6 example above.

@ma4u If the object's help patch doesn't explicitly mention a list method, you have to assume the default list method. This is true for *many* other objects, e.g. `[+]`, `[expr]`, `[metro]`, `[delay]`, `[line]`, etc.

I'm closing this because it is not a bug but expected behavior.

**Closed by Spacechild1** 2020-09-21 10:07 UTC
