### ISSUE TITLE
Control+click contextual menu not working in macOS on secondary monitor

### ISSUE THREAD

**Issue by brianlindgren** [pure-data/pure-data#1807] opened 2022-10-29 21:19 UTC
Contextual menu not accessible on secondary (external) monitor with control+click. Makes accessing 'open', 'properties' or 'help' difficult when working with 2 displays.

**Comment by Lucarda** [comment] 2022-10-29 21:57
It's a known issue https://github.com/pure-data/pure-data/issues/1303

**Comment by brianlindgren** [comment] 2022-10-29 22:21
thank you

**Comment by umlaeute** [comment] 2022-10-31 11:44
closing as duplicate (please add any additional information to the original report #1303).

i wonder though: since #1303 is rather old and we have had two reports about the same issue in the last week (#1807 and #1802), is there some (additional) regression?

**Closed by umlaeute** 2022-10-31 11:44 UTC
Labels: duplicate, subject:GUI, os:macOS
