### ISSUE TITLE
Verified downloads for deken

### ISSUE THREAD

**Issue by muziker** [pure-data/pure-data#587] opened 2019-04-19 07:27 UTC
I'd like to suggest that uploads to the repository be signed and hashed by the creator of the repo and verified by the deken plugin upon download. 

Even if the author does not have a private key, the script could auto generate and submit one. This helps in determining who uploaded the file. Even if the author does not provide a good email, the use of a signature itself helps in trusting the provenance of the download.

**Comment by umlaeute** [comment] 2019-04-22 19:41
this is essentially a duplicate of https://github.com/pure-data/deken/issues/208.
since the deken-plugin (the package downloader) is developed in the [deken repository](https://github.com/pure-data/deken/) and later integrated into Pd, let's move all discussion to that ticket.

**Closed by umlaeute** 2019-04-22 19:41 UTC
