### ISSUE TITLE
Odd behaviour when opening a patch made on an earlier version (on Windows)

### ISSUE THREAD

**Issue by bazilmuzik** [pure-data/pure-data#1805] opened 2022-10-27 21:35 UTC
So I just installed version 0-53 and I noticed that when I open patches I recently made (99.9% of them), the window doesn't show up.
Instead, I have to hover my mouse on the Pd icon in the toolbar (bottom of my screen), right click on the patch window and then choose the option "maximize" in order to see my patch. See attached image (the patch I opened and which doesn't show up right away is named sequence_wt.pd)
And even after that, I have to do the exact same thing when I try to open a subpatch.

![Windows_issue](https://user-images.githubusercontent.com/50770917/198402678-a4284ec5-dc11-4ff1-9bd1-fde7f91c603b.jpg)

**Comment by Lucarda** [comment] 2022-10-28 09:09
Hi,

Strange. I can't reproduce on Win11 with Pd-0.53.

Does the console print something?

Can you share a patch that exhibits the problem? (compress it to ZIP and upload in the comment)

**Comment by umlaeute** [comment] 2022-10-28 09:28
Weird. I don't recall any changes to the windowing code...

**Comment by ben-wes** [comment] 2022-10-28 09:37
Direct follow-up since I was curious now and connected a second screen ... I think I was wrong with my assumption that it's related to patches that were edited on the primary screen. This behaves correctly here - at least for new patches (will have to check older ones later). But if I save a patch with its patch window on the second screen and close/reopen it, I get the weird behavior we're reporting here. This was not the case before.

Here's the resulting file for a test patch I saved on the second screen:
```
#N canvas 681 -770 450 300 12;
#X text 49 49 test on second screen above secondary screen;
```

**Comment by ben-wes** [comment] 2022-10-28 09:48
I just reinstalled Pd0.52-2 to compare. If I open the little sample patch above, it's getting displayed correctly at the position where I edited it. Seems like it's an issued of correctly displaying windows with negative coordinates maybe?

**Comment by ben-wes** [comment] 2022-10-28 10:21
Tested a bit more on Pd-0.53 with 2 vertically aligned screens. This file here appears again partly on the primary screen at the bottom:
```
#N canvas 0 -1200 453 301 12;
```
... so if I understand the behavior of Pd correctly here, it looks like this to me:
* for Pd-0.53, if window coordinates are outside the available display size (including both screens), the position is wrapped for the available width and height. This causes the issue because it gets obviously wrapped around the total height, which is 2160px for me, but my display y coordinates range from -1080 to 1080. So the window gets positioned at an invisible area for patches with a y-position between -1 and -1080 (resulting in an actual positioning between 2159 and 1081, I guess).
* Pd-0.52-2 doesn't seem to have this "wrapping" mechanism. Patches that were saved at some coordinate that's not visible when reopening them, are just not visible.

So I really like the approach of the new version with the wrapping! It just doesn't seem to work for setups where the upper left coordinate of the available total display is negative. But it actually looks like a bug in a new feature and not a regression to me.

**Comment by ben-wes** [comment] 2022-10-28 10:21
... so if I understand the behavior of Pd correctly here, it looks like this to me:
* for Pd-0.53, if window coordinates are outside the available display size (including both screens), the position is wrapped for the available width and height. This causes the issue because it gets obviously wrapped around the total height, which is 2160px for me, but my display y coordinates range from -1080 to 1080. So the window gets positioned at an invisible area for patches with a y-position between -1 and -1080 (resulting in an actual positioning between 2159 and 1081, I guess).
* Pd-0.52-2 doesn't seem to have this "wrapping" mechanism. Patches that were saved at some coordinate that's not visible when reopening them, are just not visible.

So I really like the approach of the new version with the wrapping! It just doesn't seem to work for setups where the upper left coordinate of the available total display is negative. But it actually looks like a bug in a new feature and not a regression to me.

**Comment by ben-wes** [comment] 2022-10-28 10:53
Could this be related to the changes in this context maybe? https://github.com/pure-data/pure-data/commit/10191a67f6d7bd77d82ee08838f92b299c45fa8a
Also wanted to add: if I use my upper screen as primary screen, everything works fine - with a range from (0, 0) to (1920, 2160). But ovbiously (and unfortunately), these negative coordinates are not uncommon (at least for Windows).

**Comment by Lucarda** [comment] 2022-10-28 11:20
@ben-wes thnks for your findigs.

Can you do some test?

backup (make a copy of) `pd-0.53-0/tcl/pdtk_canvas.tcl` to `pd-0.53-0/tcl/pdtk_canvas.tcl.bak` or something you like.

then edit `pd-0.53-0/tcl/pdtk_canvas.tcl` line 66-69 to:


```
        set x [ expr $x % $width]
        set y [ expr $y % $height]
        if {$x < [lindex [wm minsize .] 0]} {set x 0}
        if {$y < [lindex [wm minsize .] 1]} {set y 0}
```

save the file and restart Pd. Then please do all kinds of tests. I think this fix will handle all situations.

**Comment by ben-wes** [comment] 2022-10-28 14:38
@Lucarda Thanks for the snippet! Unfortunately, it didn't solve the problem. I tried to find some documentation on this Tcl stuff concerning the case with negative screen coordinates to test around a bit myself ... that was a bit of a pain - but in the end, these lines here seem to work well for all my tested configurations (handling a negative offset correctly for negative screen origin coordinates):

```
        set xmin [winfo vrootx .]
        set ymin [winfo vrooty .]
        set x [expr ($x - $xmin) % $width + $xmin] 
        set y [expr ($y - $ymin) % $height + $ymin] 
```

**Comment by Lucarda** [comment] 2022-10-28 14:46
@ben-wes fantastic, I was just reading about `winfo vrootx/y`

I'm going to test your code but surely it works :)

**Comment by Lucarda** [comment] 2022-10-28 15:40
@ben-wes this lookg totally good for me. (only tested it with a single monitor)

I think you already test with dual monitor. 

Do you feel ok to do a PR? (you know how to use git and all that?)

In case you don't want to do the PR just tell me and I'll do it.

**Comment by ben-wes** [comment] 2022-10-28 16:29
Good to hear, @Lucarda ! ... I tested with a single monitor and two in different layouts. Can do some additional testing with irregular layouts though! And are the names `xmin` and `ymin` alright for the screen origin? I haven't really checked other conventions there.

And I'll happily do a PR - although I never did that before, I admit. But maybe it's good to start at some point. :)

Will do both (more tests and PR) later today or tomorrow though since I'm currently not at home, ok?

**Comment by Lucarda** [comment] 2022-10-28 16:37
@ben-wes sure no trouble and no rushing.

I'll try to do more tests in the mean time. Also I might be away from my computers in the weekend.

Feel free to ask here whatever. You might also read this https://github.com/pure-data/pure-data/wiki/Pull-Requests . Your PR  fit to be aimed at `develop` branch.

**Comment by Lucarda** [comment] 2022-10-28 16:51
oops I did some multi-monitor tests and failed. We will have to dig more.

**Comment by Lucarda** [comment] 2022-10-28 17:22
false alarm to my post above :)

I was testing with an incorrect `pdtk_canvas.tcl`. The good news is that I had tested with with multi-monitor connected and it seems good with all settings.

**Comment by ben-wes** [comment] 2022-10-28 17:22
haha, ok... maybe it's not gonna be the first PR for me. ;) ... do you have any details on how you were testing? resolution of the screens and how they were aligned?

**Comment by ben-wes** [comment] 2022-10-28 17:23
ah! ok... thanks! anyway - I'll do some tests with untypical monitor configurations.

**Comment by Lucarda** [comment] 2022-10-28 17:27
![monitors](https://user-images.githubusercontent.com/25239522/198696639-2260681d-0eb4-4bbc-a88c-5300e68be377.png)


positioning the 2nd monitor at north, east, south or west from 1st monitor.

**Comment by ben-wes** [comment] 2022-10-28 22:11
Tested a bit more now. Of course, it's still possible to hide the patch window with a setup like this:

![image](https://user-images.githubusercontent.com/1923787/198740043-1859b431-f8a3-46fa-aed5-578984abdf0d.png)

... but I assume that's expected?

Besides that, I found the following things which might be acceptable - but still wanted to mention these before proceeding here:
* x coordinate in my 1920x1080 screen setup only wraps at 1924px
* y coordinate already wraps at 1041px
* it's becoming a mess when screens have different system zoom settings (although this seems logical, but pixels are not handled as actual pixels anymore then obviously)
* fullscreen mode is not getting saved. When reloaded, this gets set back to the last positioned/scaled window properties (it's the same for the current version and acceptable imho - but not exactly what I would expect)

If there's no need to work on these other points, I'll do the PR tomorrow.

**Comment by Lucarda** [comment] 2022-10-28 22:51
@ben-wes  thanks for working on this.

> If there's no need to work on these other points, I'll do the PR tomorrow.

I'm not sure if any of us knows how to deal with those points. If you ask me: go ahead with the PR: we surely need that change in the code.

PS: remember to create your new branch on top of `develop` 

```
git pull --all

git checkout develop

git checkout -b <you-name-it>

...

```

later you can target `develop` instead of `master` when you create the PR via the webrowser from your fork.

-
-
image
-
-
![pr](https://user-images.githubusercontent.com/25239522/198747474-320549cf-029d-4488-b1d0-91bfdcb4b7f6.png)

**Comment by ben-wes** [comment] 2022-10-29 17:15
Thanks for your help anc documentation here, @Lucarda ! I just created the PR. I'm not quite sure if I did it all correctly concerning how issue and PR are linked now. Possibly not. Hope, this can be handled correctly anyway.

**Comment by Lucarda** [comment] 2022-10-29 18:42
@ben-wes  the PR looks perfectly good. Well done!.

I'll only suggest that you add more info in the description like:

------------------------
This PR is to be merged into `develop` branch`

Closes: #1805

....

------------------

**Comment by ben-wes** [comment] 2022-10-29 18:53
Thanks for your feedback @Lucarda ! I updated the description accordingly.

**Comment by Lucarda** [comment] 2022-10-29 19:04
&#128077;

**Comment by bazilmuzik** [comment] 2022-10-31 14:41
Thanks to all of you for looking at that, I wouldn't have been able to dig that deep into the issue :)

**Comment by ben-wes** [comment] 2022-10-31 17:22
Thanks for opening the issue, @bazilmuzik ! I was glad to see your report here when I was actually about to create one myself - because then I realized I was not the only one experiencing this weird behavior and it motivated me to look deeper into it since it was obviously Pd and not my system (which I wasn't sure about in the beginning).

**Closed** 2022-11-27 17:44 UTC
Labels: pending, regression, subject:GUI, os:windows
